import { Ionicons } from "@expo/vector-icons";
import React, { createContext, useCallback, useContext, useMemo, useState } from "react";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useLanguage } from "@/src/providers/LanguageProvider";
import { useTheme } from "@/src/providers/ThemeProvider";

type Kind = "success" | "error" | "info" | "warning";
type Notice = { id: number; kind: Kind; title: string; message?: string };
type ConfirmOptions = { title: string; message: string; confirmLabel?: string; cancelLabel?: string; danger?: boolean };
type ContextValue = { notify: (kind: Kind, title: string, message?: string) => void; success: (title: string, message?: string) => void; error: (title: string, message?: string) => void; info: (title: string, message?: string) => void; warning: (title: string, message?: string) => void; confirm: (options: ConfirmOptions) => Promise<boolean> };
const Context = createContext<ContextValue | null>(null);
let sequence = 0;
const colors: Record<Kind, string> = { success: "#12a071", error: "#e5484d", info: "#1258e8", warning: "#f59e0b" };
const icons: Record<Kind, keyof typeof Ionicons.glyphMap> = { success: "checkmark-circle", error: "alert-circle", info: "information-circle", warning: "warning" };

export function NotificationProvider({ children }: { children: React.ReactNode }) {
  const { colors: theme } = useTheme(); const { direction, isRTL } = useLanguage(); const insets = useSafeAreaInsets();
  const [notices, setNotices] = useState<Notice[]>([]); const [confirmation, setConfirmation] = useState<(ConfirmOptions & { resolve: (answer: boolean) => void }) | null>(null);
  const notify = useCallback((kind: Kind, title: string, message?: string) => { const id = ++sequence; setNotices((current) => [...current.slice(-2), { id, kind, title, message }]); setTimeout(() => setNotices((current) => current.filter((item) => item.id !== id)), kind === "error" ? 6500 : 4200); }, []);
  const confirm = useCallback((options: ConfirmOptions) => new Promise<boolean>((resolve) => setConfirmation({ ...options, resolve })), []);
  const value = useMemo(() => ({ notify, success: (t: string, m?: string) => notify("success", t, m), error: (t: string, m?: string) => notify("error", t, m), info: (t: string, m?: string) => notify("info", t, m), warning: (t: string, m?: string) => notify("warning", t, m), confirm }), [confirm, notify]);
  return <Context.Provider value={value}><View style={{ flex: 1 }}>{children}<View pointerEvents="box-none" style={[styles.stack, { top: insets.top + 10, direction }]}>{notices.map((notice) => <View key={notice.id} style={[styles.notice, { backgroundColor: theme.surface, borderColor: theme.border, flexDirection: isRTL ? "row-reverse" : "row" }]}><Ionicons name={icons[notice.kind]} size={23} color={colors[notice.kind]} /><View style={styles.copy}><Text style={[styles.title, { color: theme.text }]}>{notice.title}</Text>{notice.message ? <Text style={[styles.message, { color: theme.textSoft }]}>{notice.message}</Text> : null}</View><Pressable onPress={() => setNotices((current) => current.filter((item) => item.id !== notice.id))}>  <Ionicons name="close" size={18} color={theme.textSoft} /></Pressable></View>)}</View></View><Modal visible={Boolean(confirmation)} transparent animationType="fade" onRequestClose={() => { if (confirmation) { confirmation.resolve(false); setConfirmation(null); } }}><View style={[styles.backdrop, { backgroundColor: theme.overlay, direction }]}><View style={[styles.dialog, { backgroundColor: theme.surface }]}><View style={[styles.mark, { backgroundColor: confirmation?.danger ? `${theme.danger}1A` : `${theme.primary}1A` }]}><Ionicons name={confirmation?.danger ? "warning" : "help-circle"} size={27} color={confirmation?.danger ? theme.danger : theme.primary} /></View><Text style={[styles.dialogTitle, { color: theme.text }]}>{confirmation?.title}</Text><Text style={[styles.dialogMessage, { color: theme.textSoft }]}>{confirmation?.message}</Text><View style={[styles.actions, { flexDirection: isRTL ? "row-reverse" : "row" }]}><Pressable style={[styles.action, { borderColor: theme.border }]} onPress={() => { confirmation?.resolve(false); setConfirmation(null); }}><Text style={{ color: theme.text, fontWeight: "800" }}>{confirmation?.cancelLabel || "إلغاء"}</Text></Pressable><Pressable style={[styles.action, { backgroundColor: confirmation?.danger ? theme.danger : theme.primary, borderColor: "transparent" }]} onPress={() => { confirmation?.resolve(true); setConfirmation(null); }}><Text style={{ color: "#fff", fontWeight: "800" }}>{confirmation?.confirmLabel || "تأكيد"}</Text></Pressable></View></View></View></Modal></Context.Provider>;
}

export function useNotifications() { const value = useContext(Context); if (!value) throw new Error("NotificationProvider is missing"); return value; }

const styles = StyleSheet.create({ stack: { position: "absolute", left: 12, right: 12, zIndex: 1000, gap: 9 }, notice: { alignItems: "center", gap: 10, padding: 13, borderWidth: 1, borderRadius: 17, shadowColor: "#071127", shadowOpacity: .18, shadowRadius: 18, shadowOffset: { width: 0, height: 7 }, elevation: 8 }, copy: { flex: 1, gap: 2 }, title: { fontSize: 14, fontWeight: "800" }, message: { fontSize: 12, lineHeight: 18 }, backdrop: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20 }, dialog: { width: "100%", maxWidth: 430, borderRadius: 26, padding: 25, alignItems: "center" }, mark: { width: 56, height: 56, borderRadius: 18, alignItems: "center", justifyContent: "center", marginBottom: 13 }, dialogTitle: { fontSize: 20, fontWeight: "900", textAlign: "center" }, dialogMessage: { marginTop: 8, fontSize: 14, lineHeight: 23, textAlign: "center" }, actions: { width: "100%", gap: 10, marginTop: 23 }, action: { flex: 1, minHeight: 48, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center" } });
