import React, { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useLocalSearchParams, router } from "expo-router";
import { Pressable, ScrollView, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { AppHeader } from "@/src/components/AppHeader";
import { ScaledText as Text } from "@/src/components/ScaledText";
import { AppButton, Card, Field, Screen, LoadingState } from "@/src/components/ui";
import { READER_INFORMATION } from "@/src/lib/reader-guide";
import { api, DIRECT_COMMERCE_ENABLED } from "@/src/lib/api";
import { FAQ_CATEGORIES, type InformationContent } from "@/src/lib/information-contract";
import { useTheme } from "@/src/providers/ThemeProvider";
export default function Information() {
  const { colors } = useTheme(); const params = useLocalSearchParams<{ page?: string }>();
  const [page, setPage] = useState(params.page === "faq" ? "faq" : "about"); const [category, setCategory] = useState("all"); const [search, setSearch] = useState(""); const [open, setOpen] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["public-information"], queryFn: ({signal}) => api<{content: InformationContent}>("/api/public/information", {signal}), staleTime: 30_000, enabled: DIRECT_COMMERCE_ENABLED });
  const text = { color: colors.text, fontSize: 16, lineHeight: 28, textAlign: "right" as const };
  const subtitle = { ...text, color: colors.textSoft, fontSize: 15 };
  if (DIRECT_COMMERCE_ENABLED && query.isLoading) return <Screen><AppHeader title="دليل مراس" back/><LoadingState/></Screen>;
  if (DIRECT_COMMERCE_ENABLED && !query.data) return <Screen><AppHeader title="دليل مراس" back/><Text style={text}>تعذر تحميل المحتوى المنشور.</Text><AppButton title="إعادة المحاولة" onPress={() => void query.refetch()}/></Screen>;
  const content = DIRECT_COMMERCE_ENABLED ? query.data!.content : READER_INFORMATION;
  const rows = content.faq.filter(item => (category === "all" || item.category === category) && `${item.question} ${item.answer}`.includes(search.trim()));
  return <Screen keyboard><AppHeader title={page === "faq" ? "الأسئلة الشائعة" : content.about.title} subtitle="معرفة أوضح. تجربة أقرب." back/><View style={{ flexDirection: "row-reverse", gap: 10, marginBottom: 18 }}><AppButton full={false} title="عن مراس" variant={page === "about" ? "primary" : "soft"} onPress={() => setPage("about")}/><AppButton full={false} title="الأسئلة الشائعة" variant={page === "faq" ? "primary" : "soft"} onPress={() => setPage("faq")}/></View>
    {page === "about" ? <View style={{ gap: 16 }}><Card style={{ gap: 12, backgroundColor: colors.surfaceAlt }}><Ionicons name="sparkles-outline" color={colors.primary} size={32}/><Text style={{ ...text, fontSize: 24, fontWeight: "800" }}>دراسة أقل تشتتًا</Text><Text selectable style={subtitle}>{content.about.intro}</Text></Card><Card style={{ gap: 12 }}><Text style={{ ...text, fontWeight: "800", fontSize: 21 }}>رسالتنا</Text><Text selectable style={subtitle}>{content.about.mission}</Text><Text style={{ ...text, fontWeight: "800", fontSize: 21 }}>رؤيتنا</Text><Text selectable style={subtitle}>{content.about.vision}</Text></Card><Text style={{ ...text, fontWeight: "800", fontSize: 22 }}>لماذا تختار مراس؟</Text>{content.about.why.map((item,i) => <Card key={i} style={{ gap: 10 }}><Text style={{ color: colors.primary, fontSize: 18, fontWeight: "800" }}>{String(i+1).padStart(2,"0")}</Text><Text style={{ ...text, fontWeight: "800", fontSize: 19 }}>{item.title}</Text><Text selectable style={subtitle}>{item.body}</Text></Card>)}<Text selectable style={subtitle}>مراس خدمة تعليمية مساندة، وليست بديلًا عن الجامعة أو ضمانًا للنتيجة الدراسية. راجع تفاصيل المادة وشروط استخدام الخدمة.</Text></View> : <View style={{ gap: 14 }}><Field label="ابحث في الأسئلة" value={search} onChangeText={setSearch} placeholder="اشتراك، ملف، إحالة…"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, flexDirection: "row-reverse", paddingVertical: 6 }}>{Object.entries({all:"الكل",...FAQ_CATEGORIES}).map(([key,label]) => <Pressable accessibilityRole="button" accessibilityState={{selected:category===key}} key={key} onPress={() => setCategory(key)} style={{ borderRadius: 30, paddingHorizontal: 16, paddingVertical: 10, borderWidth: 1, borderColor: category === key ? colors.primary : colors.border, backgroundColor: colors.surface }}><Text style={{ color: category === key ? colors.primary : colors.text, fontSize: 14 }}>{label}</Text></Pressable>)}</ScrollView><Text accessibilityLiveRegion="polite" style={subtitle}>{rows.length} إجابات</Text>{rows.map(item => <Card key={item.id} style={{gap:10}}><Pressable accessibilityRole="button" accessibilityState={{expanded:open===item.id}} onPress={() => setOpen(open === item.id ? null : item.id)} style={{ flexDirection:"row-reverse",gap:10,alignItems:"center",minHeight:44 }}><Text style={{...text,flex:1,fontWeight:"700"}}>{item.question}</Text><Ionicons name={open===item.id?"remove":"add"} size={23} color={colors.primary}/></Pressable>{open===item.id && <Text selectable style={subtitle}>{item.answer}</Text>}</Card>)}{!rows.length && <Text style={subtitle}>جرّب كلمة أخرى أو اختر كل التصنيفات.</Text>}</View>}
    <Card style={{gap:12,marginTop:24}}><Text style={{...text,fontWeight:"800"}}>سؤال خاص بحسابك؟</Text><Text style={subtitle}>تابع تذكرتك من حسابك، ولا تشارك كلمة المرور أو رموز التحقق.</Text><AppButton title="الدعم الفني" onPress={() => router.push("/support")}/><AppButton title="قنوات التواصل" variant="soft" onPress={() => router.push("/contact")}/></Card>
  </Screen>;
}
