import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import React, { useEffect, useState } from "react";
import { Animated, Easing, Pressable, StyleSheet, Text, View } from "react-native";
import { BrandMark } from "@/src/components/Brand";
import { AppButton, Card, Screen } from "@/src/components/ui";
import { api } from "@/src/lib/api";
import { useAuth } from "@/src/providers/AuthProvider";
import { useTheme } from "@/src/providers/ThemeProvider";

const steps = [
  { icon: "sparkles-outline" as const, kicker: "أهلًا بك في مراس", title: "تعلّمك يبدأ من مكانك", text: "نبني لك بداية هادئة وواضحة، ثم نقرّب المواد والخدمات التي تحتاجها في مسارك الجامعي.", points: ["توصيات حسب جامعتك وتخصصك", "حساب واحد على كل أجهزتك"] },
  { icon: "school-outline" as const, kicker: "اكتشاف أسرع", title: "مواد تخصصك أولًا", text: "ستظهر المواد الأقرب إليك في الواجهة، ويمكنك تغيير الفلاتر والبحث في كل الجامعات والتخصصات متى رغبت.", points: ["فلترة تلقائية قابلة للتغيير", "بحث كامل في كتالوج مراس"] },
  { icon: "play-circle-outline" as const, kicker: "تعلّم بلا انقطاع", title: "واصل من آخر ثانية", text: "جرّب الدرس المجاني، وبعد الاشتراك يحفظ المشغل تقدمك لتكمل من أي جهاز بأمان.", points: ["حفظ التقدم تلقائيًا", "جلسة مشاهدة خاصة ومحمية"] },
  { icon: "cloud-upload-outline" as const, kicker: "مادتك غير موجودة؟", title: "اطلبها وتابعها", text: "ارفع السلايدات أو توصيف المقرر، وسيتولى المشرف متابعة الطلب وإشعارك عند توفر المادة.", points: ["مرفقات داخل حسابك", "تحديثات وإشعارات مباشرة"] },
  { icon: "shield-checkmark-outline" as const, kicker: "أنت جاهز", title: "كل أدواتك في مكان واحد", text: "استكشف، اشترِ، احفظ، تواصل، واسأل مساعد مراس. رحلتك الجامعية أصبحت أكثر ترتيبًا.", points: ["دعم مرتبط بحسابك", "دفع وإشعارات من الخادم"] },
];

export default function Onboarding() {
  const { colors } = useTheme(); const { refresh } = useAuth(); const [index, setIndex] = useState(0); const [busy, setBusy] = useState(false); const step = steps[index]!;
  const [opacity] = useState(() => new Animated.Value(1)); const [translate] = useState(() => new Animated.Value(0));
  useEffect(() => { opacity.setValue(0); translate.setValue(14); Animated.parallel([Animated.timing(opacity, { toValue: 1, duration: 240, easing: Easing.out(Easing.cubic), useNativeDriver: true }), Animated.timing(translate, { toValue: 0, duration: 260, easing: Easing.out(Easing.cubic), useNativeDriver: true })]).start(); }, [index, opacity, translate]);
  const finish = async () => { setBusy(true); try { await api("/api/profile/onboarding", { method: "POST" }); await refresh(); router.replace("/(tabs)"); } finally { setBusy(false); } };
  const next = () => { if (index < steps.length - 1) setIndex(index + 1); else void finish(); };
  const skip = async () => { setBusy(true); try { await api("/api/profile/onboarding", { method: "POST" }); await refresh(); router.replace("/(tabs)"); } finally { setBusy(false); } };
  return <Screen scroll={false} style={styles.page}><View style={styles.topbar}><BrandMark size={62} whiteTile /><Pressable accessibilityRole="button" onPress={() => void skip} disabled={busy}><Text style={[styles.skip, { color: colors.textSoft }]}>تخطي</Text></Pressable></View><View style={styles.intro}><Text style={[styles.overline, { color: colors.primary }]}>مرحبًا بك في مراس العلم</Text><Text style={[styles.heading, { color: colors.text }]}>بداية مصممة لك</Text><Text style={[styles.counter, { color: colors.textSoft }]}>{index + 1} من {steps.length}</Text></View><View style={styles.progressRow}>{steps.map((_, item) => <View key={item} style={[styles.progressTrack, { backgroundColor: colors.border }, item <= index && { backgroundColor: colors.primary }, item === index && styles.progressActive]} />)}</View><Animated.View style={[styles.content, { opacity, transform: [{ translateY: translate }] }]}><View style={[styles.hero, { backgroundColor: colors.primary }]}><View style={[styles.heroOrb, { backgroundColor: colors.primary }]} /><View style={[styles.heroIcon, { backgroundColor: colors.surface }]}><Ionicons name={step.icon} size={44} color={colors.primary} /></View><Text style={styles.heroNumber}>{String(index + 1).padStart(2, "0")}</Text><Text style={styles.heroLabel}>مراس العلم</Text></View><Card style={styles.card}><Text style={[styles.kicker, { color: colors.primary }]}>{step.kicker}</Text><Text style={[styles.title, { color: colors.text }]}>{step.title}</Text><Text style={[styles.copy, { color: colors.textSoft }]}>{step.text}</Text><View style={styles.points}>{step.points.map((point) => <View key={point} style={styles.point}><Ionicons name="checkmark-circle" size={17} color={colors.success} /><Text style={[styles.pointText, { color: colors.text }]}>{point}</Text></View>)}</View></Card></Animated.View><View style={styles.footer}><AppButton title={index === steps.length - 1 ? "ابدأ استخدام مراس" : "التالي"} icon={index === steps.length - 1 ? "rocket-outline" : "arrow-back"} loading={busy} onPress={next} /><Text style={[styles.secure, { color: colors.textSoft }]}><Ionicons name="shield-checkmark-outline" size={14} color={colors.success} /> بياناتك محفوظة بأمان</Text></View></Screen>;
}

const styles = StyleSheet.create({ page: { paddingHorizontal: 20, paddingBottom: 22 }, topbar: { width: "100%", flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14 }, skip: { fontSize: 12, fontWeight: "800", padding: 10 }, intro: { width: "100%", alignItems: "flex-end" }, overline: { width: "100%", fontSize: 11, fontWeight: "800", textAlign: "right" }, heading: { width: "100%", fontSize: 29, fontWeight: "900", textAlign: "right", marginTop: 4 }, counter: { width: "100%", fontSize: 11, textAlign: "right", marginTop: 3 }, progressRow: { width: "100%", flexDirection: "row-reverse", gap: 5, marginTop: 18, marginBottom: 18 }, progressTrack: { flex: 1, height: 4, borderRadius: 4, opacity: 0.75 }, progressActive: { flex: 2, opacity: 1 }, content: { width: "100%", gap: 14 }, hero: { minHeight: 192, borderRadius: 28, overflow: "hidden", alignItems: "center", justifyContent: "center", position: "relative" }, heroOrb: { width: 240, height: 240, borderRadius: 120, position: "absolute", top: -100, right: -62, opacity: 0.32 }, heroIcon: { width: 92, height: 92, borderRadius: 28, alignItems: "center", justifyContent: "center" }, heroNumber: { position: "absolute", bottom: 13, left: 17, color: "rgba(255,255,255,.38)", fontSize: 43, fontWeight: "900" }, heroLabel: { color: "rgba(255,255,255,.75)", fontSize: 10, fontWeight: "800", marginTop: 10 }, card: { width: "100%", padding: 20 }, kicker: { fontSize: 11, fontWeight: "900", textAlign: "right" }, title: { fontSize: 23, fontWeight: "900", textAlign: "right", marginTop: 7 }, copy: { fontSize: 13, lineHeight: 23, textAlign: "right", writingDirection: "rtl", marginTop: 9 }, points: { gap: 9, marginTop: 17, paddingTop: 14, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(100,116,139,.22)" }, point: { flexDirection: "row-reverse", alignItems: "center", gap: 7 }, pointText: { fontSize: 11, fontWeight: "700", textAlign: "right" }, footer: { width: "100%", marginTop: 18, gap: 12 }, secure: { textAlign: "center", fontSize: 10, fontWeight: "700" }, });
