import { Ionicons } from "@expo/vector-icons";
import { Redirect, router, useLocalSearchParams } from "expo-router";
import React, { useEffect, useMemo, useState } from "react";
import { ScaledText as Text } from "@/src/components/ScaledText";
import { Animated, Easing, Pressable, StyleSheet, View } from "react-native";
import { BrandMark } from "@/src/components/Brand";
import { useAuthRestoreState } from "@/src/components/AuthRestoreState";
import { AppButton, Card, LoadingState, Screen } from "@/src/components/ui";
import { authGateHref, resolveAuthReturnRoute } from "@/src/lib/authReturnRoute";
import { completeGuestOnboarding, syncOnboardingCompletion } from "@/src/lib/onboardingSync";
import { useTheme } from "@/src/providers/ThemeProvider";
import { usePlatformControls } from "@/src/components/PlatformControls";

const steps = [
  { icon: "sparkles-outline" as const, kicker: "أهلًا بك في مراس", title: "تعلّمك يبدأ من مكانك", text: "نبني لك بداية هادئة وواضحة، ثم نقرّب المواد والخدمات التي تحتاجها في مسارك الجامعي.", points: ["توصيات حسب جامعتك وتخصصك", "حساب واحد على كل أجهزتك"] },
  { icon: "school-outline" as const, kicker: "اكتشاف أسرع", title: "مواد تخصصك أولًا", text: "ستظهر المواد الأقرب إليك في الواجهة، ويمكنك تغيير الفلاتر والبحث في كل الجامعات والتخصصات متى رغبت.", points: ["فلترة تلقائية قابلة للتغيير", "بحث كامل في كتالوج مراس"] },
  { icon: "play-circle-outline" as const, kicker: "تعلّم بلا انقطاع", title: "واصل من آخر ثانية", text: "جرّب الدرس المجاني، وبعد الاشتراك يحفظ المشغل تقدمك لتكمل من أي جهاز بأمان.", points: ["حفظ التقدم تلقائيًا", "جلسة مشاهدة خاصة ومحمية"] },
  { icon: "cloud-upload-outline" as const, kicker: "مادتك غير موجودة؟", title: "اطلبها وتابعها", text: "ارفع السلايدات أو توصيف المقرر، وسيتولى المشرف متابعة الطلب وإشعارك عند توفر المادة.", points: ["مرفقات داخل حسابك", "تحديثات وإشعارات مباشرة"] },
  { icon: "shield-checkmark-outline" as const, kicker: "أنت جاهز", title: "كل أدواتك في مكان واحد", text: "استكشف، اشترِ، احفظ، تواصل، واسأل مساعد مراس. رحلتك الجامعية أصبحت أكثر ترتيبًا.", points: ["دعم مرتبط بحسابك", "دفع وإشعارات من الخادم"] },
];

export default function Onboarding() {
  const { colors } = useTheme(); const { user, refresh, authReady, restoration } = useAuthRestoreState({ title: "البداية التعريفية", loadingLabel: "نجهّز جولتك التعريفية...", scroll: false, footer: false }); const controls = usePlatformControls(); const [index, setIndex] = useState(0); const [busy, setBusy] = useState(false); const step = steps[index]!;
  const { return_to: returnToParam } = useLocalSearchParams<{ return_to?: string | string[] }>(); const returnRoute = useMemo(() => resolveAuthReturnRoute(returnToParam), [returnToParam]);
  const [opacity] = useState(() => new Animated.Value(1)); const [translate] = useState(() => new Animated.Value(0));
  useEffect(() => { opacity.setValue(0); translate.setValue(14); Animated.parallel([Animated.timing(opacity, { toValue: 1, duration: 240, easing: Easing.out(Easing.cubic), useNativeDriver: true }), Animated.timing(translate, { toValue: 0, duration: 260, easing: Easing.out(Easing.cubic), useNativeDriver: true })]).start(); }, [index, opacity, translate]);
  useEffect(() => { if (authReady && controls.ready && !controls.enabled("onboarding")) router.replace(user ? (user.profileCompleted ? returnRoute?.href || "/(tabs)" : authGateHref("/complete-profile", returnRoute)) : "/(auth)/welcome"); }, [authReady, controls, returnRoute, user]);
  const finish = async () => { if (!authReady || controls.loading) return; setBusy(true); try { let currentUser = user; if (user) { const synced = await syncOnboardingCompletion(user); if (synced) currentUser = await refresh() || user; } else await completeGuestOnboarding(); router.replace(currentUser ? (currentUser.profileCompleted ? returnRoute?.href || "/(tabs)" : authGateHref("/complete-profile", returnRoute)) : "/(auth)/welcome"); } finally { setBusy(false); } };
  const next = () => { if (index < steps.length - 1) setIndex(index + 1); else void finish(); };
  if (restoration) return restoration;
  if (controls.loading) return <Screen scroll={false} footer={false}><LoadingState label="نجهّز جولتك التعريفية..." /></Screen>;
  if (!user && returnRoute) return <Redirect href={{ pathname: "/(auth)/login", params: { return_to: returnRoute.path } }} />;
  return <Screen scroll={false} footer={false} style={styles.page}><View style={styles.topbar}><BrandMark size={66} whiteTile /><Pressable accessibilityRole="button" accessibilityLabel="تخطي التعريف" onPress={() => void finish()} disabled={busy}><Text style={[styles.skip, { color: colors.textSoft }]}>تخطي</Text></Pressable></View><View style={styles.intro}><Text style={[styles.overline, { color: colors.primary }]}>مرحبًا بك في مراس العلم</Text><Text style={[styles.heading, { color: colors.text }]}>بداية مصممة لك</Text><Text style={[styles.counter, { color: colors.textSoft }]}>{index + 1} من {steps.length}</Text></View><View style={styles.progressRow}>{steps.map((_, item) => <View key={item} style={[styles.progressTrack, { backgroundColor: colors.border }, item <= index && { backgroundColor: colors.primary }, item === index && styles.progressActive]} />)}</View><Animated.View style={[styles.content, { opacity, transform: [{ translateY: translate }] }]}><View style={[styles.hero, { backgroundColor: colors.primary }]}><View style={[styles.heroOrb, { backgroundColor: colors.violet }]} /><View style={[styles.heroIcon, { backgroundColor: colors.surface }]}><Ionicons name={step.icon} size={44} color={colors.primary} /></View><Text style={styles.heroNumber}>{String(index + 1).padStart(2, "0")}</Text><Text style={styles.heroLabel}>مراس العلم</Text></View><Card style={styles.card}><Text style={[styles.kicker, { color: colors.primary }]}>{step.kicker}</Text><Text style={[styles.title, { color: colors.text }]}>{step.title}</Text><Text style={[styles.copy, { color: colors.textSoft }]}>{step.text}</Text><View style={styles.points}>{step.points.map((point) => <View key={point} style={styles.point}><Ionicons name="checkmark-circle" size={17} color={colors.success} /><Text style={[styles.pointText, { color: colors.text }]}>{point}</Text></View>)}</View></Card></Animated.View><View style={styles.footer}><View style={styles.navigation}>{index > 0 ? <Pressable accessibilityRole="button" accessibilityLabel="الخطوة السابقة" onPress={() => setIndex((value) => Math.max(0, value - 1))} style={[styles.previous, { borderColor: colors.border, backgroundColor: colors.surface }]}><Ionicons name="arrow-forward" size={18} color={colors.primary} /><Text style={[styles.previousText, { color: colors.primary }]}>السابق</Text></Pressable> : null}<View style={styles.next}><AppButton title={index === steps.length - 1 ? "ابدأ استخدام مراس" : "التالي"} icon={index === steps.length - 1 ? "rocket-outline" : "arrow-back"} loading={busy} onPress={next} /></View></View><Text style={[styles.secure, { color: colors.textSoft }]}><Ionicons name="shield-checkmark-outline" size={14} color={colors.success} /> بياناتك محفوظة بأمان</Text></View></Screen>;
}

const styles = StyleSheet.create({ page: { paddingHorizontal: 20, paddingBottom: 22 }, topbar: { width: "100%", flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 14 }, skip: { fontSize: 12, fontWeight: "800", padding: 10 }, intro: { width: "100%", alignItems: "flex-end" }, overline: { width: "100%", fontSize: 11, fontWeight: "800", textAlign: "right" }, heading: { width: "100%", fontSize: 29, fontWeight: "900", textAlign: "right", marginTop: 4 }, counter: { width: "100%", fontSize: 11, textAlign: "right", marginTop: 3 }, progressRow: { width: "100%", flexDirection: "row-reverse", gap: 5, marginTop: 18, marginBottom: 18 }, progressTrack: { flex: 1, height: 4, borderRadius: 4, opacity: 0.75 }, progressActive: { flex: 2, opacity: 1 }, content: { width: "100%", gap: 14, flex: 1 }, hero: { minHeight: 168, borderRadius: 28, overflow: "hidden", alignItems: "center", justifyContent: "center", position: "relative" }, heroOrb: { width: 240, height: 240, borderRadius: 120, position: "absolute", top: -100, right: -62, opacity: 0.32 }, heroIcon: { width: 86, height: 86, borderRadius: 27, alignItems: "center", justifyContent: "center" }, heroNumber: { position: "absolute", bottom: 13, left: 17, color: "rgba(255,255,255,.38)", fontSize: 43, fontWeight: "900", textAlign: "left" }, heroLabel: { color: "rgba(255,255,255,.75)", fontSize: 10, fontWeight: "800", marginTop: 10, textAlign: "center" }, card: { width: "100%", padding: 18 }, kicker: { fontSize: 11, fontWeight: "900", textAlign: "right" }, title: { fontSize: 22, fontWeight: "900", textAlign: "right", marginTop: 7 }, copy: { fontSize: 12, lineHeight: 21, textAlign: "right", writingDirection: "rtl", marginTop: 8 }, points: { gap: 8, marginTop: 13, paddingTop: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(100,116,139,.22)" }, point: { flexDirection: "row-reverse", alignItems: "center", gap: 7 }, pointText: { fontSize: 10, fontWeight: "700", textAlign: "right" }, footer: { width: "100%", marginTop: 14, gap: 10 }, navigation: { flexDirection: "row-reverse", alignItems: "center", gap: 9 }, next: { flex: 1 }, previous: { minHeight: 50, borderRadius: 15, borderWidth: 1, paddingHorizontal: 14, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 6 }, previousText: { fontSize: 11, fontWeight: "900" }, secure: { textAlign: "center", fontSize: 10, fontWeight: "700" }, });
