import { Ionicons } from "@expo/vector-icons";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import * as DocumentPicker from "expo-document-picker";
import { router } from "expo-router";
import React, { useState } from "react";
import { ScaledText as Text } from "@/src/components/ScaledText";
import { ScaledTextInput as TextInput } from "@/src/components/ScaledTextInput";
import { Pressable, StyleSheet, View } from "react-native";
import { AppHeader } from "@/src/components/AppHeader";
import { AppButton, Card, EmptyState, Field, LoadingState, Screen, SectionTitle } from "@/src/components/ui";
import { api, ApiError } from "@/src/lib/api";
import { assetMimeType } from "@/src/lib/file-types";
import { useAuth } from "@/src/providers/AuthProvider";
import { useTheme } from "@/src/providers/ThemeProvider";
import type { Dashboard, PublicSettings } from "@/src/types";

type Picked = DocumentPicker.DocumentPickerAsset;
const MAX_FILES = 100;
const MAX_TOTAL_FILE_BYTES = 100 * 1024 * 1024;

export default function Requests() {
  const { user } = useAuth(); const { colors } = useTheme(); const queryClient = useQueryClient();
  const dashboard = useQuery({ queryKey: ["dashboard", user?.id], queryFn: () => api<Dashboard>("/api/mobile/dashboard"), enabled: Boolean(user) });
  const settings = useQuery({ queryKey: ["settings"], queryFn: () => api<{ settings: PublicSettings }>("/api/public/settings"), staleTime: 5_000 });
  const [courseName, setCourseName] = useState(""); const [courseCode, setCourseCode] = useState(""); const [notes, setNotes] = useState(""); const [files, setFiles] = useState<Picked[]>([]); const [sending, setSending] = useState(false); const [message, setMessage] = useState("");
  if (!user) return <Screen><AppHeader title="طلب مادة" back /><EmptyState title="الحساب مطلوب" text={settings.data?.settings.student_registration_enabled === "false"?"سجّل الدخول إلى حسابك الحالي حتى ترتبط الخدمة بجامعتك وتخصصك.":"سجّل الدخول أو أنشئ حسابًا وأكمل جامعتك وتخصصك حتى يصل الطلب للمشرف الصحيح."} action={<View style={styles.guestActions}><AppButton title="تسجيل الدخول" onPress={() => router.push("/(auth)/login")} />{settings.data?.settings.student_registration_enabled !== "false"?<AppButton title="إنشاء حساب" variant="soft" onPress={() => router.push("/(auth)/register")} />:null}</View>} /></Screen>;
  if (settings.data?.settings.course_requests_enabled === "false") return <Screen><AppHeader title="طلبات المواد" back /><EmptyState icon="construct-outline" title="طلبات المواد متوقفة مؤقتًا" text="أوقفت الإدارة استقبال الطلبات الجديدة حاليًا. ستصلك التحديثات عند إعادة تفعيل الخدمة." action={<AppButton title="العودة للرئيسية" onPress={() => router.replace("/(tabs)")} />} /></Screen>;
  const pick = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "application/vnd.ms-powerpoint", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "image/png", "image/jpeg"], multiple: true, copyToCacheDirectory: true }); if (result.canceled) return; const next = [...files, ...result.assets]; if (next.length > MAX_FILES) { setMessage(`يمكن إرفاق ${MAX_FILES} ملف كحد أقصى`); return; } const total = next.reduce((sum, file) => sum + (file.size || 0), 0); if (total > MAX_TOTAL_FILE_BYTES) { setMessage("إجمالي حجم المرفقات يجب ألا يتجاوز 100 ميجابايت"); return; } setMessage(""); setFiles(next); };
  const submit = async () => { setSending(true); setMessage(""); try { const form = new FormData(); form.append("courseName", courseName); form.append("courseCode", courseCode); form.append("notes", notes); form.append("notify", "1"); files.forEach((file) => form.append("files", { uri: file.uri, name: file.name, type: assetMimeType(file, "application/octet-stream") } as unknown as Blob)); await api("/api/course-requests", { method: "POST", body: form, timeoutMs: 180_000 }); setCourseName(""); setCourseCode(""); setNotes(""); setFiles([]); setMessage("تم إرسال الطلب والمرفقات إلى المشرف"); await queryClient.invalidateQueries({ queryKey: ["dashboard"] }); } catch (reason) { setMessage(reason instanceof ApiError ? reason.message : "تعذر إرسال الطلب"); } finally { setSending(false); } };
  return <Screen keyboard><AppHeader title="طلبات المواد" subtitle={`${dashboard.data?.requests.length || 0} طلبات سابقة`} back /><Card><Text style={[styles.formTitle, { color: colors.text }]}>مادة غير موجودة؟</Text><Text style={[styles.formCopy, { color: colors.textSoft }]}>أرسل اسمها وارفع السلايدات أو توصيف المقرر، وسيتم ربط الطلب بجامعتك وتخصصك تلقائيًا. حتى {MAX_FILES} ملف بإجمالي 100MB.</Text><Field label="اسم المادة" value={courseName} onChangeText={setCourseName} placeholder="مثال: الهياكل المتقطعة" /><Field label="رمز المادة — اختياري" value={courseCode} onChangeText={setCourseCode} placeholder="CS 230" autoCapitalize="characters" /><TextInput multiline value={notes} onChangeText={setNotes} placeholder="ملاحظات للمشرف أو تفاصيل المحتوى المطلوب" placeholderTextColor={colors.textSoft} style={[styles.notes, { color: colors.text, backgroundColor: colors.surfaceAlt, borderColor: colors.border }]} textAlign="right" /><AppButton title={`إرفاق ملفات (${files.length})`} variant="soft" icon="attach-outline" onPress={pick} />{files.map((file, index) => <View key={`${file.uri}-${index}`} style={[styles.file, { borderColor: colors.border }]}><Pressable onPress={() => setFiles((rows) => rows.filter((_, item) => item !== index))}><Ionicons name="close-circle" size={20} color={colors.danger} /></Pressable><Text numberOfLines={1} style={[styles.fileName, { color: colors.text }]}>{file.name}</Text><Ionicons name="document-outline" size={18} color={colors.primary} /></View>)}{message ? <Text style={[styles.message, { color: message.startsWith("تم") ? colors.success : colors.danger }]}>{message}</Text> : null}<AppButton title="إرسال الطلب" loading={sending} disabled={courseName.trim().length < 3} icon="send-outline" onPress={submit} /></Card><SectionTitle title="متابعة الطلبات" subtitle="تتحدث الحالة من لوحة المشرف" />{dashboard.isLoading ? <LoadingState /> : dashboard.data?.requests.length ? dashboard.data.requests.map((row) => <Card key={row.id} style={styles.request}><View style={styles.requestHead}><Status status={row.status} colors={colors} /><Text style={[styles.requestTitle, { color: colors.text }]}>{row.courseName}</Text></View><Text style={[styles.requestMeta, { color: colors.textSoft }]}>#{row.id} · {new Date(row.createdAt).toLocaleDateString("ar-SA")} · {row.attachmentsCount} مرفقات</Text></Card>) : <EmptyState title="لا توجد طلبات سابقة" text="سيظهر طلبك هنا فور إرساله." />}</Screen>;
}
function Status({ status, colors }: { status: string; colors: ReturnType<typeof useTheme>["colors"] }) { const label = ({ new: "جديد", assigned: "مسند", reviewing: "قيد المراجعة", planned: "مخطط له", producing: "قيد الإنتاج", available: "متاح", declined: "متعذر" } as Record<string, string>)[status] || status; return <View style={[styles.status, { backgroundColor: `${status === "available" ? colors.success : colors.primary}18` }]}><Text style={{ color: status === "available" ? colors.success : colors.primary, fontSize: 9, fontWeight: "900" }}>{label}</Text></View>; }
const styles = StyleSheet.create({ guestActions: { width: "100%", gap: 9 }, formTitle: { fontSize: 19, fontWeight: "900", textAlign: "right" }, formCopy: { fontSize: 11, lineHeight: 20, textAlign: "right", marginTop: 6, marginBottom: 18 }, notes: { minHeight: 110, borderWidth: 1, borderRadius: 15, padding: 12, textAlignVertical: "top", writingDirection: "rtl", marginBottom: 12 }, file: { minHeight: 44, borderBottomWidth: 1, flexDirection: "row", alignItems: "center", gap: 8 }, fileName: { flex: 1, fontSize: 9, textAlign: "right" }, message: { fontSize: 10, textAlign: "center", marginVertical: 10 }, request: { marginBottom: 9 }, requestHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, requestTitle: { flex: 1, fontSize: 13, fontWeight: "900", textAlign: "right" }, requestMeta: { fontSize: 9, marginTop: 8, textAlign: "right" }, status: { borderRadius: 10, paddingHorizontal: 9, paddingVertical: 6, marginRight: 8 } });
