import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import React, { useState } from "react";
import { ScaledText as Text } from "@/src/components/ScaledText";
import { Modal, Pressable, StyleSheet, View } from "react-native";
import { AppHeader } from "@/src/components/AppHeader";
import { AppButton, Card, Field, Screen } from "@/src/components/ui";
import { api, ApiError, jsonBody } from "@/src/lib/api";
import { useAuth } from "@/src/providers/AuthProvider";
import { useTheme } from "@/src/providers/ThemeProvider";

export default function Security() {
  const { colors } = useTheme(); const { logout } = useAuth(); const [modal, setModal] = useState(false); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const remove = async () => { setLoading(true); setError(""); try { await api("/api/mobile/account", { method: "DELETE", body: jsonBody({ password, confirmation }) }); await logout(); setModal(false); router.replace("/(auth)/welcome"); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "تعذر حذف الحساب"); } finally { setLoading(false); } };
  return <Screen><AppHeader title="الأمان والخصوصية" subtitle="تحكم كامل في حسابك" back /><Card style={styles.card}><Ionicons name="shield-checkmark-outline" size={31} color={colors.success} /><Text style={[styles.title, { color: colors.text }]}>جلسة آمنة على هذا الجهاز</Text><Text style={[styles.copy, { color: colors.textSoft }]}>رمز الدخول محفوظ في التخزين الآمن للنظام ولا يُرسل إلا إلى خادم مراس عبر HTTPS. يمكنك تسجيل الخروج لإلغاء الجلسة الحالية.</Text><AppButton title="تسجيل الخروج من الجهاز" variant="soft" onPress={async () => { await logout(); router.replace("/(auth)/welcome"); }} /></Card><Card style={[styles.card, { marginTop: 13, borderColor: `${colors.danger}55` }]}><Ionicons name="trash-outline" size={31} color={colors.danger} /><Text style={[styles.title, { color: colors.danger }]}>حذف الحساب</Text><Text style={[styles.copy, { color: colors.textSoft }]}>الحذف يزيل الجلسات والأجهزة والطلبات والملفات والملاحظات والتقدم والدعم والتقييمات. تُحوّل بيانات السجلات المالية الضرورية إلى معرّف مجهول وفق مدة الاحتفاظ النظامية.</Text><AppButton title="طلب حذف حسابي" variant="danger" onPress={() => setModal(true)} /></Card><Modal visible={modal} transparent animationType="fade" onRequestClose={() => setModal(false)}><View style={[styles.overlay, { backgroundColor: colors.overlay }]}><View style={[styles.dialog, { backgroundColor: colors.background }]}><Pressable onPress={() => setModal(false)}><Ionicons name="close" size={24} color={colors.text} /></Pressable><Text style={[styles.dialogTitle, { color: colors.danger }]}>تأكيد حذف الحساب نهائيًا</Text><Text style={[styles.copy, { color: colors.textSoft }]}>اكتب «حذف حسابي» وأدخل كلمة المرور للتأكيد.</Text><Field label="عبارة التأكيد" value={confirmation} onChangeText={setConfirmation} placeholder="حذف حسابي" /><Field label="كلمة المرور" value={password} onChangeText={setPassword} secureTextEntry />{error ? <Text style={[styles.error, { color: colors.danger }]}>{error}</Text> : null}<AppButton title="حذف الحساب نهائيًا" variant="danger" loading={loading} disabled={confirmation !== "حذف حسابي" || password.length < 8} onPress={remove} /></View></View></Modal></Screen>;
}
const styles = StyleSheet.create({ card: { alignItems: "flex-end", gap: 9 }, title: { fontSize: 17, fontWeight: "900", textAlign: "right" }, copy: { fontSize: 10, lineHeight: 19, textAlign: "right", writingDirection: "rtl", marginBottom: 8 }, overlay: { flex: 1, alignItems: "center", justifyContent: "center", padding: 18 }, dialog: { width: "100%", borderRadius: 25, padding: 20 }, dialogTitle: { fontSize: 19, fontWeight: "900", textAlign: "right", marginTop: 12 }, error: { fontSize: 10, textAlign: "center", marginBottom: 8 } });
