import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import ts from 'typescript';
function moduleAt(path, mocks={}) { const exports={}; vm.runInNewContext(ts.transpileModule(readFileSync(new URL('../'+path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:name=>mocks[name],Date,Set}); return exports; }
const social=moduleAt('src/lib/social-provider-policy.ts');
test('iOS Google login requires the configured privacy-preserving Apple equivalent',()=> { assert.equal(social.nativeSocialProviders('ios',{google:true,apple:false}).google,false);assert.equal(social.nativeSocialProviders('ios',{google:true,apple:true}).google,true);assert.equal(social.nativeSocialProviders('android',{google:true,apple:false}).google,true);assert.equal(social.nativeSocialProviders('web',{google:true,apple:true}).google,false); });
const account=moduleAt('src/lib/account-access.ts',{'@/src/lib/notification-routing':{safeInternalPath:v=>v||null}});
test('instructors verify email then enter their own workspace without student academic onboarding',()=> {const user={role:'instructor',emailVerified:false,profileCompleted:false,onboardingCompleted:false};assert.equal(account.accountRequirement(user),'/verify-email');user.emailVerified=true;assert.equal(account.accountRequirement(user),null);assert.equal(account.authDestination(user,undefined,'/admin'),'/instructor');assert.equal(account.authDestination({...user,role:'student'}),'/complete-profile');});
const instructor=moduleAt('src/lib/instructor.ts');
test('instructor application requires unexpired complete identity evidence and editable server status',()=> {const data={profile:{status:'draft',bio:'خبرة في الشرح والتدريس الجامعي أكثر من خمس سنوات',teachingSubjects:'رياضيات'},identityCollection:{enabled:true},documents:[{kind:'selfie'},{kind:'identity_front'}]};assert.equal(instructor.instructorReadyToSubmit(data),false);data.documents.push({kind:'identity_back'});assert.equal(instructor.instructorReadyToSubmit(data),true);data.documents[0].expiresAt='2000-01-01';assert.equal(instructor.instructorReadyToSubmit(data),false);data.documents=[{kind:'selfie'},{kind:'passport'}];assert.equal(instructor.instructorReadyToSubmit(data),true);data.profile.status='submitted';assert.equal(instructor.instructorReadyToSubmit(data),false);data.profile.status='changes_requested';data.identityCollection.enabled=false;assert.equal(instructor.instructorReadyToSubmit(data),false);});
