import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash,randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const exports={};vm.runInNewContext(ts.transpileModule(readFileSync(new URL('../src/lib/instructor-video-upload.ts',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports,TextEncoder,Set});
const hash=async bytes=>createHash('sha256').update(bytes).digest('hex');
function fixture(overrides={}){const bytes=new Uint8Array(exports.INSTRUCTOR_VIDEO_CHUNK_BYTES+20).fill(3),id=randomUUID(),calls=[],saved=new Map();let received=[0];const receipt=()=>({id,status:'open',received:[...received],sizeBytes:bytes.length,chunkBytes:exports.INSTRUCTOR_VIDEO_CHUNK_BYTES});const source={sizeBytes:bytes.length,contentType:'video/mp4',read:async(offset,length)=>bytes.slice(offset,offset+length)};const transport={userId:1,signal:new AbortController().signal,hash,uuid:randomUUID,saved:async(key,value)=>{if(value===null)saved.delete(key);else if(value!==undefined)saved.set(key,value);return saved.get(key)||null;},request:async(path,method,body)=>{calls.push({path,method,body});if(method==='PUT'){received.push(Number(new URL('https://x'+path).searchParams.get('part')));return receipt();}const data=JSON.parse(body);return {...receipt(),status:data.action==='complete'?'completed':'open'};},...overrides};return {source,transport,calls,saved};}
test('native instructor upload resumes only missing chunks and commits the exact revision',async()=>{const x=fixture();await exports.uploadInstructorVideo(x.source,x.transport,{assignmentId:4,lessonId:8,expectedRevision:11});const writes=x.calls.filter(v=>v.method==='PUT');assert.equal(writes.length,1);assert.match(writes[0].path,/part=1$/);assert.equal(JSON.parse(x.calls.at(-1).body).expectedRevision,11);assert.equal(x.saved.size,0);});
test('corrupt acknowledgement retains account-scoped resumable request and prevents completion',async()=>{const x=fixture();const original=x.transport.request;x.transport.request=async(...args)=>{const result=await original(...args);return args[1]==='PUT'?{...result,id:randomUUID()}:result;};await assert.rejects(()=>exports.uploadInstructorVideo(x.source,x.transport,{assignmentId:4,lessonId:8,expectedRevision:11}),/متسق/);assert.equal(x.calls.some(v=>v.method==='POST'&&JSON.parse(v.body).action==='complete'),false);assert.equal(x.saved.size,1);assert.match([...x.saved.keys()][0],/instructor-upload\.1\.4\./);});
test('changing video bytes after hashing never sends the altered chunk',async()=>{const x=fixture();let reads=0;const original=x.source.read;x.source.read=async(...args)=>{const value=await original(...args);if(++reads>2)value[0]=7;return value;};await assert.rejects(()=>exports.uploadInstructorVideo(x.source,x.transport,{assignmentId:4,lessonId:8,expectedRevision:11}),/تغيّر/);assert.equal(x.calls.some(v=>v.method==='PUT'),false);});
test('aborted upload performs no network mutation',async()=>{const abort=new AbortController();abort.abort();const x=fixture({signal:abort.signal});await assert.rejects(()=>exports.uploadInstructorVideo(x.source,x.transport,{assignmentId:4,lessonId:8,expectedRevision:11}));assert.equal(x.calls.length,0);});
