import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import vm from "node:vm";
import ts from "typescript";
function load(path,globals={}){const compiledModule={exports:{}};vm.runInNewContext(ts.transpileModule(readFileSync(new URL(path,import.meta.url),"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:compiledModule,exports:compiledModule.exports,DOMException,Blob,File,setTimeout,clearTimeout,...globals});return compiledModule.exports;}
function recorderFixture(){let stopped=0;const instances=[];
 class Recorder {state="inactive";static isTypeSupported(type){return type==="audio/mp4";}constructor(_stream,options){instances.push(this);this.mimeType=options.mimeType;}start(){this.state="recording";}stop(){this.state="inactive";this.ondataavailable?.({data:new Blob(["audio"])});this.onstop?.();}}
 const stream={getTracks:()=>[{stop(){stopped++;}}]};return {Recorder,stream,stopped:()=>stopped,instance:()=>instances[0]};}
test("voice recording chooses a supported audio container including Safari MP4",()=>{const voice=load("../lib/voice-recording.ts");assert.equal(voice.supportedVoiceType(type=>type==="audio/mp4").extension,"m4a");assert.equal(voice.supportedVoiceType(()=>false),null);});
test("microphone permission resolving after navigation releases tracks without creating a recording",async()=>{const f=recorderFixture();let allow;const permission=new Promise(resolve=>{allow=resolve;});const voice=load("../lib/voice-recording.ts",{navigator:{mediaDevices:{getUserMedia:()=>permission}},MediaRecorder:f.Recorder});const controller=new AbortController();const pending=voice.startVoiceRecording({signal:controller.signal,onFile(){assert.fail("file after navigation")},onStop(){},onError(){}});controller.abort();allow(f.stream);await assert.rejects(pending,{name:"AbortError"});assert.equal(f.stopped(),1);assert.equal(f.instance(),undefined);});
test("normal recording produces MIME-correct file and releases microphone",async()=>{const f=recorderFixture();const voice=load("../lib/voice-recording.ts",{navigator:{mediaDevices:{getUserMedia:async()=>f.stream}},MediaRecorder:f.Recorder});let file,ended=0;const recording=await voice.startVoiceRecording({signal:new AbortController().signal,onFile:value=>{file=value},onStop:()=>{ended++},onError:()=>assert.fail("unexpected error")});recording.stop();assert.equal(file.type,"audio/mp4");assert.match(file.name,/\.m4a$/);assert.equal(ended,1);assert.equal(f.stopped(),1);recording.dispose();assert.equal(f.stopped(),1);});
test("navigation disposes microphone without appending a file to another ticket",async()=>{const f=recorderFixture();const voice=load("../lib/voice-recording.ts",{navigator:{mediaDevices:{getUserMedia:async()=>f.stream}},MediaRecorder:f.Recorder});const controller=new AbortController();await voice.startVoiceRecording({signal:controller.signal,onFile:()=>assert.fail("file after cleanup"),onStop:()=>assert.fail("state update after cleanup"),onError:()=>assert.fail("unexpected error")});controller.abort();assert.equal(f.stopped(),1);assert.equal(f.instance().state,"inactive");});
test("an upload cancelled before starting does not create or send a network request",async()=>{let constructed=0;const uploads=load("../lib/upload-client.ts",{XMLHttpRequest:class{constructor(){constructed++;}}});const controller=new AbortController();controller.abort();await assert.rejects(uploads.uploadWithProgress({url:"/api/support",body:new Blob(["private"]),signal:controller.signal}),error=>error.status===499);assert.equal(constructed,0);});
