import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { isolatedSource } from './helpers/isolated-source.mjs';
class ApiError extends Error {constructor(message,status,extra={}){super(message);this.status=status;Object.assign(this,extra);}}
async function harness({status=200,body='{}',size=body.length,os='ios',throws=false,permission=true}={}){
 const calls={requests:[],deletes:[],reads:[],mkdir:[],headers:0,copies:[]};
 const FileSystem={cacheDirectory:'file:///cache/',documentDirectory:null,makeDirectoryAsync:async path=>calls.mkdir.push(path),
  downloadAsync:async(url,destination,options)=>{calls.requests.push({url,destination,options});if(throws)throw new Error('private network issue');return {status,uri:destination};},
  getInfoAsync:async()=>({exists:true,isDirectory:false,size}),readAsStringAsync:async path=>{calls.reads.push(path);return body;},deleteAsync:async path=>calls.deletes.push(path),copyAsync:async input=>calls.copies.push(input),
  StorageAccessFramework:{requestDirectoryPermissionsAsync:async()=>({granted:permission,directoryUri:'content://files'}),createFileAsync:async()=> 'content://files/saved.pdf'},
 };
 const apiRequestUrl=path=>{const url=new URL(path,'https://maras.example');if(url.origin!=='https://maras.example'||!url.pathname.startsWith('/api/'))throw new ApiError('غير موثوق',0);return url;};
 const mod=await isolatedSource('mobile/src/lib/downloads.ts',{FileSystem,randomUUID,Platform:{OS:os},apiRequestUrl,ApiError,getApiToken:()=> 'test-token',getApiDeviceHeaders:()=>{calls.headers++;return {'x-meras-device-id':'fixture-device','x-meras-admin-step-up':'fixture-step-up'};}});
 return {mod,calls,FileSystem};
}
test('mobile download displays server pending reason and retry metadata; removes error file',async()=>{const{mod,calls}=await harness({status:423,body:JSON.stringify({error:'الملف قيد الفحص',code:'FILE_SCAN_PENDING',retryAfterSeconds:30})});await assert.rejects(mod.downloadProtectedFile({path:'/api/support/files/1',fileName:'طلب.pdf',openAfterDownload:false}),error=>{assert.equal(error.message,'الملف قيد الفحص');assert.equal(error.status,423);assert.equal(error.code,'FILE_SCAN_PENDING');assert.equal(error.retryAfterSeconds,30);return true;});assert.equal(calls.deletes.length,1);assert.equal(calls.reads.length,1);});
test('mobile download missing or quarantined response is not reported as saved',async()=>{const{mod,calls}=await harness({status:404,body:JSON.stringify({error:'ملف محجور',code:'FILE_QUARANTINED'})});await assert.rejects(mod.downloadProtectedFile({path:'/api/course-requests/files/1',fileName:'test.pdf'}),error=>error.status===404&&error.code==='FILE_QUARANTINED');assert.equal(calls.copies.length,0);assert.equal(calls.deletes.length,1);});
test('mobile download never reads a large HTML/error response into JavaScript memory',async()=>{const{mod,calls}=await harness({status:503,size:1000000});await assert.rejects(mod.downloadProtectedFile({path:'/api/support/files/1',fileName:'x'}),/HTTP 503/);assert.equal(calls.reads.length,0);assert.equal(calls.deletes.length,1);});
test('mobile malformed error response preserves accurate HTTP error',async()=>{const{mod,calls}=await harness({status:403,body:'not json'});await assert.rejects(mod.downloadProtectedFile({path:'/api/support/files/1',fileName:'x'}),/HTTP 403/);assert.equal(calls.deletes.length,1);});
test('mobile successful download carries identity and authentication headers',async()=>{const{mod,calls}=await harness();const result=await mod.downloadProtectedFile({path:'/api/admin/course-requests/1/download',fileName:'notes.pdf',openAfterDownload:false});assert.equal(result.action,'stored');assert.equal(calls.requests[0].options.headers.authorization,'Bearer test-token');assert.equal(calls.requests[0].options.headers['x-meras-device-id'],'fixture-device');assert.equal(calls.requests[0].options.headers['x-meras-admin-step-up'],'fixture-step-up');assert.equal(calls.reads.length,0);assert.equal(calls.deletes.length,0);});
test('mobile concurrent same-name downloads have unique destinations',async()=>{const{mod,calls}=await harness();await Promise.all([1,2].map(()=>mod.downloadProtectedFile({path:'/api/support/files/1',fileName:'notes.pdf',openAfterDownload:false})));assert.notEqual(calls.requests[0].destination,calls.requests[1].destination);});
test('mobile filename cannot escape its private download directory',async()=>{const{mod,calls}=await harness();await mod.downloadProtectedFile({path:'/api/support/files/1',fileName:'../../evil\n.pdf',openAfterDownload:false});const name=calls.requests[0].destination.slice(calls.mkdir[0].length);assert.doesNotMatch(decodeURIComponent(name),/[\\/\n]/);});
test('mobile untrusted URL is rejected before credentials or filesystem operations',async()=>{const{mod,calls}=await harness();await assert.rejects(mod.downloadProtectedFile({path:'https://untrusted.test/secret',fileName:'notes.pdf'}),/غير موثوق/);assert.equal(calls.headers,0);assert.equal(calls.requests.length,0);assert.equal(calls.mkdir.length,0);});
test('mobile network failure cleans its incomplete download folder',async()=>{const{mod,calls}=await harness({throws:true});await assert.rejects(mod.downloadProtectedFile({path:'/api/support/files/1',fileName:'x'}),/انقطع تنزيل/);assert.equal(calls.deletes.length,1);});
test('Android directory permission cancellation does not download or falsely report success',async()=>{const{mod,calls}=await harness({os:'android',permission:false});assert.deepEqual(await mod.downloadProtectedFile({path:'/api/support/files/1',fileName:'x',saveToFiles:true}),{action:'cancelled',uri:null});assert.equal(calls.requests.length,0);});
test('Android successful SAF copy returns the actual destination',async()=>{const{mod,calls}=await harness({os:'android'});assert.deepEqual(await mod.downloadProtectedFile({path:'/api/support/files/1',fileName:'x.pdf',saveToFiles:true}),{action:'saved',uri:'content://files/saved.pdf'});assert.equal(calls.copies.length,1);});
test('mobile support uses protected helper, gates previews, and does not keep old unchecked downloader',async()=>{const source=await readFile(new URL('../mobile/src/components/SupportChat.tsx',import.meta.url),'utf8');assert.match(source,/downloadProtectedFile/);assert.doesNotMatch(source,/FileSystem\.downloadAsync/);assert.match(source,/scanStatus/);assert.doesNotMatch(source,/تم حفظ الملف[^\n]*catch/);});
