import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { isolatedSource } from './helpers/isolated-source.mjs';
import { standaloneSource } from './helpers/standalone-source.mjs';
const scanner=await standaloneSource('lib/malware-scanner.ts');
const storage=await standaloneSource('lib/storage.ts');
async function mod(overrides={}){return isolatedSource('lib/file-security.ts',{...scanner,activeStorageProvider:()=> 'local',getObject:storage.getObject,scannerConfig:()=>({mode:'clamd',host:'fixture',port:1}),scanClamd:async stream=>{const bytes=await scanner.readLimitedStream(stream,1000,AbortSignal.timeout(1000));return {status:'clean',provider:'protocol-fixture',error:null,reason:null,...(!bytes.length?{status:'pending'}:{})};},...overrides});}
test('scanner reads actual private stored bytes and honors explicit provider despite default changes',async()=>{const folder=await mkdtemp(join(tmpdir(),'meras-scan-test-'));const old=process.env.UPLOAD_DIR;process.env.UPLOAD_DIR=folder;try{await storage.putObject('scan/test.txt',new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('actual-file-bytes'));c.close();}}),'text/plain','local');const m=await mod({activeStorageProvider:()=> 's3'});const result=await m.scanStoredFile({objectKey:'scan/test.txt',originalName:'test.txt',contentType:'text/plain',storageProvider:'local'});assert.equal(result.status,'clean');assert.ok(result.scannedAt);assert.equal(result.provider,'protocol-fixture');}finally{if(old===undefined)delete process.env.UPLOAD_DIR;else process.env.UPLOAD_DIR=old;await rm(folder,{recursive:true,force:true});}});
test('missing actual stored object remains pending with repairable error',async()=>{const folder=await mkdtemp(join(tmpdir(),'meras-missing-test-'));const old=process.env.UPLOAD_DIR;process.env.UPLOAD_DIR=folder;try{const m=await mod();const result=await m.scanStoredFile({objectKey:'missing.txt',originalName:'x',contentType:'text/plain',storageProvider:'local'});assert.equal(result.status,'pending');assert.equal(result.error,'stored_object_missing');}finally{if(old===undefined)delete process.env.UPLOAD_DIR;else process.env.UPLOAD_DIR=old;await rm(folder,{recursive:true,force:true});}});
test('scanner unavailable in development still refuses a clean timestamp',async()=>{let reads=0;const m=await mod({scannerConfig:()=>({mode:'unconfigured'}),getObject:async()=>reads++});const v=await m.scanStoredFile({objectKey:'x',originalName:'x',contentType:'text/plain'});assert.equal(v.status,'pending');assert.equal(v.scannedAt,null);assert.equal(reads,0);});
test('scanner provider exceptions never persist private endpoint details',async()=>{const m=await mod({getObject:async()=>{throw new Error('https://secret.example/?token=secret');}});const result=await m.scanStoredFile({objectKey:'x',originalName:'x',contentType:'text/plain'});assert.equal(result.error,'scanner_connection_failed');assert.doesNotMatch(JSON.stringify(result),/secret/);});
test('scanner concurrency cap rejects extra work before fetching another private object',async()=>{let active=0;const releases=[];const m=await mod({getObject:async()=>({size:1,body:new ReadableStream({start(c){c.enqueue(new Uint8Array([1]));c.close();}})}),scanClamd:async()=>{active++;await new Promise(resolve=>releases.push(resolve));active--;return {status:'clean',provider:'fixture',error:null,reason:null};}});const input={objectKey:'x',originalName:'x',contentType:'text/plain'};const first=m.scanStoredFile(input),second=m.scanStoredFile(input);while(active<2)await new Promise(resolve=>setImmediate(resolve));const third=await m.scanStoredFile(input);assert.equal(third.status,'pending');assert.equal(third.error,'scanner_busy');for(const release of releases)release();await Promise.all([first,second]);assert.equal(globalThis.__merasActiveFileScans,0);});
test('scanner oversized metadata cancels stream without invoking transport',async()=>{let cancelled=false,calls=0;const m=await mod({getObject:async()=>({size:scanner.MAX_SCAN_BYTES+1,body:new ReadableStream({cancel(){cancelled=true;}})}),scanClamd:async()=>{calls++;}});const result=await m.scanStoredFile({objectKey:'x',originalName:'x',contentType:'text/plain'});assert.equal(result.error,'scanner_size_limit');assert.equal(cancelled,true);assert.equal(calls,0);});
