import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import net from 'node:net';
import { once } from 'node:events';
import { standaloneSource } from './helpers/standalone-source.mjs';
const scanner = await standaloneSource('lib/malware-scanner.ts');
const stream = (...chunks) => new ReadableStream({start(c){for(const chunk of chunks)c.enqueue(Buffer.from(chunk));c.close();}});
async function withEnv(values, fn) {const old={};for(const[k,v]of Object.entries(values)){old[k]=process.env[k];if(v===undefined)delete process.env[k];else process.env[k]=v;}try{return await fn();}finally{for(const[k,v]of Object.entries(old)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}}
async function httpFixture(t, handler){const server=http.createServer(handler);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>{server.closeAllConnections();server.close();});return `http://127.0.0.1:${server.address().port}/scan`;}
async function tcpFixture(t, handler){const sockets=new Set();const server=net.createServer(socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));socket.on('error',()=>{});handler(socket);});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>{for(const socket of sockets)socket.destroy();server.close();});return {mode:'clamd',host:'127.0.0.1',port:server.address().port};}
function parseInstream(socket, reply, onBody=()=>{}){let bytes=Buffer.alloc(0),command=false,parts=[];socket.on('data',data=>{bytes=Buffer.concat([bytes,data]);if(!command){const end=bytes.indexOf(0);if(end<0)return;assert.equal(bytes.subarray(0,end).toString(),'zINSTREAM');bytes=bytes.subarray(end+1);command=true;}while(bytes.length>=4){const length=bytes.readUInt32BE(0);if(bytes.length<4+length)return;const part=bytes.subarray(4,4+length);bytes=bytes.subarray(4+length);if(length===0){onBody(Buffer.concat(parts));socket.write(reply);return;}assert.ok(length<=65536);parts.push(part);}});}

test('scanner configuration never declares development uploads clean without an engine', async()=>{
 await withEnv({MALWARE_SCAN_URL:undefined,CLAMD_SOCKET:undefined,CLAMD_HOST:undefined,NODE_ENV:'development'},()=>assert.deepEqual(scanner.scannerConfig(),{mode:'unconfigured'}));
 for(const bad of ['file:///etc/passwd','https://user:pass@example.com/scan','https://example.com/#x','not a url'])await withEnv({MALWARE_SCAN_URL:bad},()=>assert.deepEqual(scanner.scannerConfig(),{mode:'invalid'}));
 await withEnv({MALWARE_SCAN_URL:undefined,CLAMD_SOCKET:undefined,CLAMD_HOST:'scanner',CLAMD_PORT:'65536'},()=>assert.equal(scanner.scannerConfig().mode,'invalid'));
 await withEnv({MALWARE_SCAN_URL:undefined,CLAMD_SOCKET:'/private/scanner.sock'},()=>assert.deepEqual(scanner.scannerConfig(),{mode:'clamd',socket:'/private/scanner.sock'}));
});
for(const [name,payload,status] of [
 ['explicit clean',{clean:true},'clean'],['status clean',{status:'CLEAN'},'clean'],['negative',{clean:false},'quarantined'],
 ['conflicting infected',{clean:true,status:'infected'},'quarantined'],['conflicting threat',{clean:true,threat:'fixture-threat'},'quarantined'],
 ['false beats status',{clean:false,status:'clean'},'quarantined'],['error beats clean',{clean:true,error:'not scanned'},'pending'],
 ['unknown status',{clean:true,status:'processing'},'pending'],['string boolean',{clean:'true'},'pending'],['empty',{},'pending'],['null',null,'pending'],['array',[],'pending'],
])test(`remote verdict: ${name}`,()=>assert.equal(scanner.remoteVerdict(payload).status,status));
test('remote engine labels remove control characters and are length-limited',()=>{const v=scanner.remoteVerdict({clean:true,engine:'x\r\n\0'+'a'.repeat(300)});assert.ok(v.provider.length<=80);assert.doesNotMatch(v.provider,/[\r\n\0]/);});
test('actual bounded stream joins bytes without decoding',async()=>assert.deepEqual(await scanner.readLimitedStream(stream([0,255],[123]),3,AbortSignal.timeout(1000)),Uint8Array.from([0,255,123])));
test('actual bounded stream cancels on overflow',async()=>{let cancelled=false;const s=new ReadableStream({start(c){c.enqueue(new Uint8Array(5));},cancel(){cancelled=true;}});await assert.rejects(scanner.readLimitedStream(s,4,AbortSignal.timeout(1000)),/scanner_size_limit/);assert.equal(cancelled,true);});
test('actual bounded stream cancels stalled reads after abort',async()=>{const controller=new AbortController();let cancelled=false;const s=new ReadableStream({cancel(){cancelled=true;}});const pending=scanner.readLimitedStream(s,4,controller.signal);controller.abort();await assert.rejects(pending);assert.equal(cancelled,true);});
test('remote HTTP sends actual file bytes, trusted token and encoded name',async t=>{
 let observed;const endpoint=await httpFixture(t,async(req,res)=>{const parts=[];for await(const p of req)parts.push(p);observed={body:Buffer.concat(parts),headers:req.headers};res.setHeader('content-type','application/json');res.end(JSON.stringify({clean:true,engine:'protocol-fixture'}));});
 await withEnv({MALWARE_SCAN_TOKEN:'test-token-not-a-secret'},async()=>{const v=await scanner.scanRemote(stream('%PDF-fixture'),{originalName:'طلب.pdf\n',contentType:'application/pdf'},{mode:'remote',endpoint},AbortSignal.timeout(2000));assert.equal(v.status,'clean');assert.equal(observed.body.toString(),'%PDF-fixture');assert.equal(observed.headers.authorization,'Bearer test-token-not-a-secret');assert.equal(observed.headers['content-type'],'application/pdf');assert.ok(observed.headers['x-file-name'].includes('%'));});
});
for(const code of [401,429,503])test(`remote HTTP ${code} stays pending`,async t=>{const endpoint=await httpFixture(t,(_req,res)=>{res.writeHead(code);res.end('private internal detail');});const v=await scanner.scanRemote(stream('data'),{originalName:'x',contentType:'text/plain'},{mode:'remote',endpoint},AbortSignal.timeout(2000));assert.equal(v.status,'pending');assert.equal(v.error,`scanner_http_${code}`);});
test('remote HTTP redirects cannot forward document or credentials',async t=>{let targetCalls=0;const target=await httpFixture(t,(_req,res)=>{targetCalls++;res.end('{"clean":true}');});const endpoint=await httpFixture(t,(_req,res)=>{res.writeHead(307,{location:target});res.end();});await assert.rejects(scanner.scanRemote(stream('confidential-fixture'),{originalName:'x',contentType:'text/plain'},{mode:'remote',endpoint},AbortSignal.timeout(2000)));assert.equal(targetCalls,0);});
test('remote empty content never reaches engine',async()=>{const v=await scanner.scanRemote(stream(),{originalName:'x',contentType:'text/plain'},{mode:'remote',endpoint:'http://127.0.0.1:1'},AbortSignal.timeout(1000));assert.equal(v.status,'pending');assert.equal(v.error,'stored_object_empty');});
test('remote invalid JSON stays pending',async t=>{const endpoint=await httpFixture(t,(_req,res)=>res.end('OK'));const v=await scanner.scanRemote(stream('data'),{originalName:'x',contentType:'text/plain'},{mode:'remote',endpoint},AbortSignal.timeout(2000));assert.equal(v.error,'scanner_invalid_response');});
test('remote oversized verdict is rejected',async t=>{const endpoint=await httpFixture(t,(_req,res)=>res.end(' '.repeat(17000)+'{"clean":true}'));await assert.rejects(scanner.scanRemote(stream('data'),{originalName:'x',contentType:'text/plain'},{mode:'remote',endpoint},AbortSignal.timeout(2000)),/scanner_size_limit/);});
for(const [reply,status]of [['stream: OK\0','clean'],['stream: Fixture-Threat FOUND\0','quarantined'],['INSTREAM size limit exceeded. ERROR\0','pending'],['OK\0','pending'],['stream: OK\0unexpected','pending']])test(`clamd exact verdict ${JSON.stringify(reply)}`,()=>assert.equal(scanner.clamdVerdict(reply).status,status));
test('actual clamd TCP framing transmits all bytes including multiple 64KiB chunks',async t=>{const expected=Buffer.alloc(180000,0x91);let actual;const config=await tcpFixture(t,socket=>parseInstream(socket,'stream: OK\0',bytes=>actual=bytes));const v=await scanner.scanClamd(stream(expected.subarray(0,70000),expected.subarray(70000)),config,AbortSignal.timeout(3000));assert.equal(v.status,'clean');assert.deepEqual(actual,expected);});
test('actual clamd TCP infected response quarantines the submitted object',async t=>{const config=await tcpFixture(t,socket=>parseInstream(socket,'stream: Fixture-Threat FOUND\0'));const v=await scanner.scanClamd(stream('fixture'),config,AbortSignal.timeout(2000));assert.equal(v.status,'quarantined');assert.equal(v.reason,'Fixture-Threat');});
test('clamd TCP premature success cannot release an incomplete stream',async t=>{const config=await tcpFixture(t,socket=>socket.once('data',()=>socket.write('stream: OK\0')));const s=new ReadableStream({start(c){c.enqueue(Buffer.from('partial'));}});const v=await scanner.scanClamd(s,config,AbortSignal.timeout(2000));assert.equal(v.status,'pending');assert.equal(v.error,'scanner_premature_response');});
test('clamd TCP truncated connection remains pending',async t=>{const config=await tcpFixture(t,socket=>socket.once('data',()=>socket.end('stream: O')));const v=await scanner.scanClamd(stream('file'),config,AbortSignal.timeout(2000));assert.equal(v.status,'pending');});
test('clamd TCP aborted connection cannot become clean',async t=>{const config=await tcpFixture(t,()=>{});await assert.rejects(scanner.scanClamd(stream('file'),config,AbortSignal.timeout(40)),/scanner_timeout/);});
test('clamd readiness probe performs actual PING/PONG exchange',async t=>{const config=await tcpFixture(t,socket=>socket.once('data',data=>{assert.equal(data.toString(),'zPING\0');socket.end('PONG\0');}));assert.equal(await scanner.probeClamd(config),true);});

test("explicit external scanner host overrides the Docker default local socket",async()=>{await withEnv({MALWARE_SCAN_URL:undefined,CLAMD_HOST:"private-scanner",CLAMD_PORT:"3310",CLAMD_SOCKET:"/tmp/meras-clamav/clamd.sock"},()=>assert.deepEqual(scanner.scannerConfig(),{mode:"clamd",host:"private-scanner",port:3310}));});

test("enabled local scanner resolves the same default socket as the startup script",async()=>{await withEnv({MALWARE_SCAN_URL:undefined,CLAMD_HOST:undefined,CLAMD_SOCKET:undefined,LOCAL_MALWARE_SCANNER_ENABLED:"true"},()=>assert.deepEqual(scanner.scannerConfig(),{mode:"clamd",socket:"/tmp/meras-clamav/clamd.sock"}));});
