import test from 'node:test';
import assert from 'node:assert/strict';
import {pureSource} from './helpers/pure-source.mjs';
const {createRealtimeController}=await pureSource('lib/realtime-client.ts');
function fixture(){const timers=new Map(),requests=[],events=[],streams=[];let id=0;const api=createRealtimeController({fetchSnapshot(signal){return new Promise((resolve,reject)=>requests.push({signal,resolve,reject}));},createStream(){const handlers={};const stream={closed:false,addEventListener(name,fn){handlers[name]=fn;},close(){this.closed=true;},handlers};streams.push(stream);return stream;},deliver:e=>events.push(e),timer(fn){timers.set(++id,fn);return id;},clearTimer:id=>timers.delete(id)});return{api,timers,requests,events,streams};}
const snapshot=version=>({ok:true,version,serverTime:'synthetic',channels:{catalog:version}});
const flush=()=>new Promise(resolve=>setImmediate(resolve));
test('pagehide aborts in-flight request, closes stream and cancels reconnect work',async()=>{const f=fixture();f.api.resume();assert.equal(f.requests.length,1);f.api.pause();assert.equal(f.requests[0].signal.aborted,true);assert.equal(f.streams[0].closed,true);assert.equal(f.timers.size,0);f.requests[0].resolve(snapshot('late'));await flush();assert.deepEqual(f.events,[]);assert.equal(f.timers.size,0);});
test('restoring a page cannot receive or schedule an old snapshot',async()=>{const f=fixture();f.api.resume();f.requests[0].resolve(snapshot('1'));await flush();f.api.pause();f.api.resume();assert.equal(f.requests.length,2);f.requests[1].resolve(snapshot('2'));await flush();assert.equal(f.events.length,1);assert.deepEqual(f.events[0].changed,['catalog']);f.api.dispose();assert.equal(f.timers.size,0);});
test('late rejection cannot clear a newer in-flight lifecycle',async()=>{const f=fixture();f.api.resume();f.api.pause();f.api.resume();f.requests[0].reject(new Error('cancelled'));await flush();assert.equal(f.timers.size,0);f.requests[1].resolve(snapshot('new'));await flush();assert.equal(f.timers.size,1);f.api.dispose();});
test('failed stream schedules one bounded reconnect, pausing suppresses all callbacks',()=>{const f=fixture();f.api.resume();const old=f.streams[0];old.onerror();assert.equal(old.closed,true);assert.equal(f.timers.size,2);f.api.pause();old.handlers.ready();old.handlers.change();old.onerror();assert.equal(f.timers.size,0);f.api.dispose();f.api.resume();assert.equal(f.streams.length,1);});
test('snapshot failures back off for a minute instead of consuming the hot-path limit',async()=>{const timers=new Map(),requests=[];let id=0;const sync=createRealtimeController({fetchSnapshot(signal){return new Promise((resolve,reject)=>requests.push({signal,resolve,reject}));},createStream:()=>null,deliver:()=>{},timer:(callback,delay)=>{timers.set(++id,{callback,delay});return id;},clearTimer:id=>timers.delete(id)});sync.resume();requests[0].reject(new Error('offline'));await flush();assert.deepEqual([...timers.values()].map(v=>v.delay),[60000]);sync.pause();assert.equal(timers.size,0);sync.resume();assert.equal(requests.length,2);requests[1].resolve(snapshot('recovered'));await flush();assert.deepEqual([...timers.values()].map(v=>v.delay),[5000]);sync.dispose();});
