import React,{useEffect,useRef,useState} from "react";
import {Modal,ScrollView,View} from "react-native";
import {Redirect,useLocalSearchParams,type Href} from "expo-router";
import {useQuery} from "@tanstack/react-query";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import {InstructorPreview} from "@/src/components/instructor-video-preview";
import {AppHeader} from "@/src/components/AppHeader";
import {AppButton,Card,EmptyState,Field,LoadingState,Screen,SectionTitle} from "@/src/components/ui";
import {ScaledText as Text} from "@/src/components/ScaledText";
import {api,getApiToken,jsonBody} from "@/src/lib/api";
import {downloadProtectedFile} from "@/src/lib/downloads";
import {MerasAlert} from "@/src/lib/interaction-events";
import {uploadNativeInstructorVideo} from "@/src/lib/instructor-video-native";
import type {InstructorVideoProgress} from "@/src/lib/instructor-video-upload";
import {INSTRUCTOR_ASSIGNMENT_LABELS,instructorAssignmentEditable,type InstructorAssignmentDetail,type InstructorLesson,type InstructorUnit} from "@/src/lib/instructor-assignments";
import {useAuth} from "@/src/providers/AuthProvider";
import {useTheme} from "@/src/providers/ThemeProvider";
type Edit={action:"saveUnit"|"saveLesson";id?:number;unitId?:number;title:string;description:string;position:number};
export default function AssignmentScreen(){
 const {id}=useLocalSearchParams<{id:string}>(),{user,loading}=useAuth();
 if(loading)return <Screen><LoadingState /></Screen>;
 if(!user)return <Redirect href={"/(auth)/login?return_to=%2Finstructor" as Href} />;
 if(user.role!=="instructor")return <Redirect href="/(tabs)/account" />;
 if(!user.emailVerified)return <Redirect href={"/verify-email?return_to=%2Finstructor" as Href} />;
 if(!id||!/^\d+$/.test(id)||!Number.isSafeInteger(Number(id))||Number(id)<1)return <Screen><EmptyState title="المادة غير متاحة" text="أعد فتح المادة من مساحة الشارح." /></Screen>;
 return <AssignmentWorkspace key={`${user.id}:${id}`} userId={user.id} assignmentId={Number(id)} />;
}
function AssignmentWorkspace({userId,assignmentId}:{userId:number;assignmentId:number}){
 const {colors}=useTheme(),endpoint=`/api/instructor/assignments/${assignmentId}`;
 const [busy,setBusy]=useState(""),[message,setMessage]=useState(""),[progress,setProgress]=useState<InstructorVideoProgress|null>(null),[edit,setEdit]=useState<Edit|null>(null),[preview,setPreview]=useState<number|null>(null);
 const mounted=useRef(true),writing=useRef(false),controller=useRef<AbortController|null>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 const query=useQuery({queryKey:["instructor-assignment",userId,assignmentId],queryFn:({signal})=>api<InstructorAssignmentDetail>(endpoint,{signal}),retry:false,staleTime:15000});
 const assertActive=(token:string)=>{if(!mounted.current||getApiToken()!==token)throw new Error("تغيّر الحساب أو أُغلقت المادة");};
 async function work(key:string,operation:(token:string,signal:AbortSignal)=>Promise<void>){if(writing.current)return;const token=getApiToken();writing.current=true;setBusy(key);setMessage("");const abort=new AbortController();controller.current=abort;try{assertActive(token);await operation(token,abort.signal);}catch(error){if(mounted.current&&getApiToken()===token)setMessage(error instanceof Error?error.message:"تعذر إكمال العملية");}finally{writing.current=false;controller.current=null;if(mounted.current){setBusy("");setProgress(null);}}}
 async function refresh(token:string){assertActive(token);const updated=await query.refetch();if(updated.isError)throw new Error("حُفظ التغيير لكن تعذر تحديث العرض. حدّث المادة قبل تكرار العملية.");}
 async function save(command:Record<string,unknown>){await work(String(command.action),async(token,signal)=>{if(!query.data)return;await api(endpoint,{method:"POST",signal,body:jsonBody({...command,expectedRevision:query.data.assignment.revision})});assertActive(token);setEdit(null);await refresh(token);});}
 function confirm(command:Record<string,unknown>,title:string,description:string){const token=getApiToken();MerasAlert.alert(title,description,[{text:"إلغاء",style:"cancel"},{text:title,style:command.action==="submit"?"default":"destructive",onPress:()=>{if(mounted.current&&getApiToken()===token)void save(command);}}]);}
 async function upload(lesson:InstructorLesson){await work(`video-${lesson.id}`,async(token,signal)=>{let uri="";try{const result=await DocumentPicker.getDocumentAsync({type:["video/mp4","video/webm","video/quicktime","video/x-matroska","video/x-msvideo"],copyToCacheDirectory:true,multiple:false});uri=result.assets?.[0]?.uri||"";assertActive(token);if(result.canceled||!result.assets[0]||!query.data)return;await uploadNativeInstructorVideo(result.assets[0],{userId,assignmentId,lessonId:lesson.id,expectedRevision:query.data.assignment.revision,signal,onProgress:value=>{if(mounted.current)setProgress(value);}});await refresh(token);setMessage("استلم الخادم الفيديو. تابع حالة المعالجة قبل إرسال المادة للمراجعة.");}finally{if(uri&&FileSystem.cacheDirectory&&uri.startsWith(FileSystem.cacheDirectory))await FileSystem.deleteAsync(uri,{idempotent:true}).catch(()=>undefined);}});}
 const text={color:colors.textSoft,fontSize:14,lineHeight:25,textAlign:"right" as const};
 if(query.isLoading)return <Screen><AppHeader title="المادة المسندة" back /><LoadingState /></Screen>;
 if(!query.data)return <Screen><AppHeader title="المادة المسندة" back /><EmptyState title="تعذر فتح المادة" text={query.error instanceof Error?query.error.message:"تحقق من الاتصال أو صلاحية الإسناد."} action={<AppButton title="إعادة المحاولة" onPress={()=>void query.refetch()} />} /></Screen>;
 const data=query.data,editable=instructorAssignmentEditable(data.assignment.status);
 const editUnit=(unit?:InstructorUnit)=>setEdit({action:"saveUnit",id:unit?.id,title:unit?.title||"",description:unit?.description||"",position:unit?.position??data.units.length});
 const editLesson=(unit:InstructorUnit,lesson?:InstructorLesson)=>setEdit({action:"saveLesson",id:lesson?.id,unitId:unit.id,title:lesson?.title||"",description:lesson?.description||"",position:lesson?.position??unit.lessons.length});
 return <Screen keyboard><AppHeader title={data.assignment.courseTitle} subtitle={INSTRUCTOR_ASSIGNMENT_LABELS[data.assignment.status]||data.assignment.status} back /><Card style={{gap:10}}><Text style={text}>{data.assignment.instructions||"استخدم ملفات المادة المرجعية، ونظم شرحك في وحدات ودروس. المحتوى يبقى مسودة حتى تعتمد الإدارة نشره."}</Text>{data.assignment.reviewNotes?<Text style={{...text,color:colors.warning}}>ملاحظة الإدارة: {data.assignment.reviewNotes}</Text>:null}<AppButton title="تحديث المادة وحالة الفيديوهات" variant="ghost" disabled={Boolean(busy)} loading={query.isFetching} onPress={()=>void query.refetch()} /></Card>
  <View style={{gap:12,marginVertical:20}}><SectionTitle title="ملفات المادة المرجعية" />{data.resources.length?data.resources.map(resource=><Card key={resource.id} style={{gap:8}}><Text style={{...text,color:colors.text,fontWeight:"800"}}>{resource.title}</Text><Text style={text}>{resource.originalName} · {(resource.sizeBytes/1024/1024).toFixed(1)} م.ب</Text><AppButton title="تحميل الملف" variant="soft" disabled={Boolean(busy)} loading={busy===`file-${resource.id}`} onPress={()=>void work(`file-${resource.id}`,async()=>{await downloadProtectedFile({path:`${endpoint}/resources/${resource.id}`,fileName:resource.originalName,mimeType:resource.contentType,saveToFiles:true});})} /></Card>):<Text style={text}>لا توجد ملفات مرفقة بهذه المادة.</Text>}</View>
  <SectionTitle title="الوحدات والدروس" subtitle="ترتيب مستقل للمراجعة؛ النشر متاح للإدارة فقط" />
  <View style={{gap:16}}>{data.units.map(unit=><Card key={unit.id} style={{gap:12}}><Text style={{...text,color:colors.text,fontSize:20,fontWeight:"800"}}>{unit.position+1}. {unit.title}</Text>{unit.description?<Text style={text}>{unit.description}</Text>:null}{editable?<View style={{gap:8}}><AppButton title="تعديل الوحدة" variant="ghost" disabled={Boolean(busy)} onPress={()=>editUnit(unit)} /><AppButton title="حذف الوحدة ودروسها" variant="danger" disabled={Boolean(busy)} onPress={()=>confirm({action:"deleteUnit",id:unit.id},"حذف الوحدة","ستحذف الوحدة ودروسها من مسودتك. هل تريد المتابعة؟")} /></View>:null}{unit.lessons.map(lesson=><View key={lesson.id} style={{gap:9,paddingTop:12,borderTopWidth:1,borderColor:colors.border}}><Text style={{...text,color:colors.text,fontWeight:"800"}}>{lesson.position+1}. {lesson.title}</Text>{lesson.description?<Text style={text}>{lesson.description}</Text>:null}<Text style={text}>{lesson.video?`حالة الفيديو: ${lesson.video.processingStatus==="ready"?"جاهز":lesson.video.processingStatus==="failed"?"تعذرت المعالجة":`جارٍ التجهيز (${lesson.video.processingProgress||0}٪)`}`:"لم يُرفق فيديو"}</Text>{lesson.video?.processingStatus==="ready"?<AppButton title="معاينة الفيديو" variant="soft" disabled={Boolean(busy)} onPress={()=>setPreview(lesson.id)} />:null}{editable?<><AppButton title="تعديل الدرس" variant="ghost" disabled={Boolean(busy)} onPress={()=>editLesson(unit,lesson)} /><AppButton title={lesson.video?"استبدال فيديو الدرس":"رفع فيديو الدرس"} variant="soft" disabled={Boolean(busy)} loading={busy===`video-${lesson.id}`} onPress={()=>void upload(lesson)} /><AppButton title="حذف الدرس" variant="danger" disabled={Boolean(busy)} onPress={()=>confirm({action:"deleteLesson",id:lesson.id},"حذف الدرس","سيحذف هذا الدرس من المسودة. هل تريد المتابعة؟")} /></>:null}</View>)}{editable?<AppButton title="إضافة درس لهذه الوحدة" variant="soft" disabled={Boolean(busy)} onPress={()=>editLesson(unit)} />:null}</Card>)}{editable?<AppButton title="إضافة وحدة" disabled={Boolean(busy)} onPress={()=>editUnit()} />:null}</View>
  {progress?<Card style={{gap:10,marginTop:16}}><Text style={text}>{progress.phase==="hashing"?"تجهيز بصمات الفيديو":progress.phase==="finalizing"?"اعتماد الفيديو في الخادم":"رفع الفيديو"} · {progress.percent}٪</Text><Text style={text}>أبقِ التطبيق مفتوحًا أثناء الرفع. إذا انقطع الاتصال أعد اختيار الفيديو نفسه لاستكمال الأجزاء المتبقية.</Text><AppButton title="إيقاف الرفع" variant="ghost" onPress={()=>controller.current?.abort()} /></Card>:null}
  {message?<Text accessibilityLiveRegion="polite" style={{...text,color:colors.primary,marginVertical:14}}>{message}</Text>:null}{editable?<Card style={{gap:10,marginTop:20}}><Text style={text}>بعد اكتمال الوحدات والدروس ومعالجة الفيديوهات، أرسل المحتوى. تُقفل المسودة أثناء المراجعة وتقرر الإدارة اعتماد النشر أو طلب تعديل.</Text><AppButton title="اكتمل الشرح — إرسال للمراجعة" disabled={Boolean(busy)||!data.units.length||data.units.some(unit=>!unit.lessons.length||unit.lessons.some(lesson=>lesson.video?.processingStatus!=="ready"))} loading={busy==="submit"} onPress={()=>confirm({action:"submit"},"إرسال للمراجعة","هل راجعت الدروس واكتمل شرح المادة؟ ستقفل المسودة لحين مراجعة الإدارة.")} /></Card>:null}
  <Modal visible={Boolean(edit)} transparent animationType="slide" onRequestClose={()=>!busy&&setEdit(null)}><View style={{flex:1,justifyContent:"center",padding:20,backgroundColor:colors.overlay}}><View style={{maxHeight:"90%",borderRadius:20,padding:20,backgroundColor:colors.background}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{gap:14}}><Text style={{...text,color:colors.text,fontSize:21,fontWeight:"800"}}>{edit?.action==="saveUnit"?"بيانات الوحدة":"بيانات الدرس"}</Text><Field label="العنوان" value={edit?.title||""} onChangeText={title=>setEdit(value=>value?{...value,title}:null)} maxLength={160} editable={!busy} /><Field label="الوصف" value={edit?.description||""} onChangeText={description=>setEdit(value=>value?{...value,description}:null)} multiline maxLength={4000} editable={!busy} /><Field label="الترتيب (يبدأ من 1)" value={String((edit?.position||0)+1)} onChangeText={position=>setEdit(value=>value?{...value,position:Math.min(999,Math.max(0,(Number(position)||1)-1))}:null)} keyboardType="number-pad" editable={!busy} /><AppButton title="حفظ" disabled={Boolean(busy)||!edit||edit.title.trim().length<2} loading={busy==="saveUnit"||busy==="saveLesson"} onPress={()=>{if(edit)void save(edit);}} />{message?<Text style={text}>{message}</Text>:null}<AppButton title="إلغاء" variant="ghost" disabled={Boolean(busy)} onPress={()=>setEdit(null)} /></ScrollView></View></View></Modal>
  {preview!==null?<Modal visible animationType="slide" onRequestClose={()=>setPreview(null)}><Screen><AppHeader title="معاينة شرحك" /><InstructorPreview path={`${endpoint}/videos/${preview}`} /><AppButton title="إغلاق المعاينة" variant="soft" onPress={()=>setPreview(null)} /></Screen></Modal>:null}
 </Screen>;
}
