/* eslint-disable react-hooks/immutability, react-hooks/refs -- Expo Video and Animated expose imperative native objects by design. */
import { Ionicons } from "@expo/vector-icons";
import Slider from "@react-native-community/slider";
import { useEvent } from "expo";
import * as ScreenCapture from "expo-screen-capture";
import { router, useLocalSearchParams } from "expo-router";
import { useVideoPlayer, VideoView } from "expo-video";
import React, { useEffect, useMemo, useRef, useState } from "react";
import { Animated, AppState, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppHeader } from "@/src/components/AppHeader";
import { AppButton, Card, LoadingState, Screen } from "@/src/components/ui";
import { absoluteUrl, api, ApiError, jsonBody } from "@/src/lib/api";
import { useAuth } from "@/src/providers/AuthProvider";
import { useTheme } from "@/src/providers/ThemeProvider";
import type { Catalog } from "@/src/types";

const rates = [0.75, 1, 1.25, 1.5, 1.75, 2];
export default function LessonPlayer() {
  const { courseSlug, lessonId } = useLocalSearchParams<{ courseSlug: string; lessonId: string }>(); const { user } = useAuth(); const { colors } = useTheme();
  const [course, setCourse] = useState<Catalog["courses"][number] | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [privateOverlay, setPrivateOverlay] = useState(false); const [note, setNote] = useState(""); const [noteMessage, setNoteMessage] = useState("");
  const [time, setTime] = useState(0); const [duration, setDuration] = useState(0); const [rateIndex, setRateIndex] = useState(1); const videoRef = useRef<VideoView>(null); const watermark = useRef(new Animated.Value(0)).current;
  const player = useVideoPlayer(null, (instance) => { instance.loop = false; instance.muted = false; instance.volume = 1; instance.playbackRate = 1; instance.audioMixingMode = "doNotMix"; });
  const { isPlaying } = useEvent(player, "playingChange", { isPlaying: player.playing });
  const lesson = useMemo(() => course?.units.flatMap((unit) => unit.lessons).find((item) => item.id === lessonId), [course, lessonId]);
  useEffect(() => { void ScreenCapture.preventScreenCaptureAsync("meras-lesson"); const sub = AppState.addEventListener("change", (state) => { setPrivateOverlay(state !== "active"); if (state !== "active") player.pause(); }); return () => { sub.remove(); void ScreenCapture.allowScreenCaptureAsync("meras-lesson"); }; }, [player]);
  useEffect(() => { const animation = Animated.loop(Animated.sequence([Animated.timing(watermark, { toValue: 1, duration: 9000, useNativeDriver: true }), Animated.timing(watermark, { toValue: 0, duration: 9000, useNativeDriver: true })])); animation.start(); return () => animation.stop(); }, [watermark]);
  useEffect(() => { const timer = setInterval(() => { setTime(player.currentTime || 0); setDuration(player.duration || 0); }, 500); return () => clearInterval(timer); }, [player]);
  useEffect(() => { void (async () => { setLoading(true); setError(""); try { const catalog = await api<Catalog>("/api/mobile/catalog"); const selected = catalog.courses.find((item) => item.slug === courseSlug); if (!selected) throw new Error("المادة غير موجودة"); setCourse(selected); const session = await api<{ streamUrl: string }>("/api/video/session", { method: "POST", body: jsonBody({ courseSlug, lessonId }) }); await player.replaceAsync({ uri: absoluteUrl(session.streamUrl), contentType: "progressive", useCaching: false, metadata: { title: selected.units.flatMap((unit) => unit.lessons).find((item) => item.id === lessonId)?.title || selected.title, artist: "مراس العلم" } }); const progress = await api<{ progress: { lessonId: string; watchedSeconds: number }[] }>(`/api/progress?course=${encodeURIComponent(courseSlug || "")}`).catch(() => ({ progress: [] })); const saved = progress.progress.find((item) => item.lessonId === lessonId); if (saved?.watchedSeconds) player.currentTime = saved.watchedSeconds; const noteResult = await api<{ note: { body: string } | null }>(`/api/mobile/notes?lesson=${encodeURIComponent(lessonId || "")}`).catch(() => ({ note: null })); setNote(noteResult.note?.body || ""); player.play(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : reason instanceof Error ? reason.message : "تعذر تشغيل الدرس"); } finally { setLoading(false); } })(); }, [courseSlug, lessonId, player]);
  useEffect(() => { if (!user || !courseSlug || !lessonId) return; const save = () => api("/api/progress", { method: "POST", body: jsonBody({ courseSlug, lessonId, watchedSeconds: Math.floor(player.currentTime || 0), completed: player.duration > 0 && player.currentTime / player.duration >= .9 }) }).catch(() => undefined); const timer = setInterval(save, 15_000); return () => { clearInterval(timer); void save(); }; }, [courseSlug, lessonId, player, user]);
  const seek = (seconds: number) => { player.currentTime = Math.max(0, Math.min(player.duration || 0, player.currentTime + seconds)); };
  const cycleRate = () => { const next = (rateIndex + 1) % rates.length; setRateIndex(next); player.playbackRate = rates[next]!; };
  const saveNote = async () => { setNoteMessage(""); try { await api("/api/mobile/notes", { method: "PUT", body: jsonBody({ lessonId, body: note }) }); setNoteMessage("تم حفظ الملاحظة"); } catch { setNoteMessage("تعذر حفظ الملاحظة"); } };
  if (loading) return <Screen scroll={false}><LoadingState label="جارٍ إنشاء رابط مشاهدة خاص..." /></Screen>;
  if (error || !course || !lesson) return <Screen><AppHeader title="مشغل مراس" back /><Card style={styles.errorCard}><Ionicons name="shield-outline" size={38} color={colors.danger} /><Text style={[styles.errorTitle, { color: colors.text }]}>تعذر فتح الدرس</Text><Text style={[styles.errorText, { color: colors.textSoft }]}>{error || "الدرس غير موجود"}</Text><AppButton title="العودة للمادة" onPress={() => router.back()} /></Card></Screen>;
  return <Screen padded={false}><View style={{ paddingHorizontal: 18 }}><AppHeader title={lesson.title} subtitle={course.title} back /></View><View style={styles.playerWrap}><VideoView ref={videoRef} player={player} style={styles.video} nativeControls={false} contentFit="contain" allowsPictureInPicture={false} allowsVideoFrameAnalysis={false} fullscreenOptions={{ enable: true }} /><Animated.View pointerEvents="none" style={[styles.watermark, { transform: [{ translateX: watermark.interpolate({ inputRange: [0, 1], outputRange: [-70, 70] }) }, { translateY: watermark.interpolate({ inputRange: [0, 1], outputRange: [-65, 60] }) }] }]}><Text>{user?.fullName || "طالب مراس"}</Text><Text>{user?.phone || user?.email || "معاينة"}</Text></Animated.View>{privateOverlay && <View style={styles.privacy}><Ionicons name="shield-checkmark" size={40} color="#FFFFFF" /><Text>المحتوى محمي داخل مراس</Text></View>}<View style={styles.controls}><Slider style={styles.slider} minimumValue={0} maximumValue={Math.max(duration, 1)} value={time} onSlidingComplete={(value) => { player.currentTime = value; }} minimumTrackTintColor="#4385FF" maximumTrackTintColor="rgba(255,255,255,.28)" thumbTintColor="#FFFFFF" /><View style={styles.timeRow}><Text>{formatTime(time)}</Text><Text>{formatTime(duration)}</Text></View><View style={styles.controlRow}><Pressable onPress={cycleRate} style={styles.controlSmall}><Text>{rates[rateIndex]}x</Text></Pressable><Pressable onPress={() => seek(10)} style={styles.controlSmall}><Ionicons name="play-forward" size={19} color="#FFF" /></Pressable><Pressable onPress={() => isPlaying ? player.pause() : player.play()} style={styles.controlMain}><Ionicons name={isPlaying ? "pause" : "play"} size={29} color="#071B45" /></Pressable><Pressable onPress={() => seek(-10)} style={styles.controlSmall}><Ionicons name="play-back" size={19} color="#FFF" /></Pressable><Pressable onPress={() => videoRef.current?.enterFullscreen()} style={styles.controlSmall}><Ionicons name="expand" size={19} color="#FFF" /></Pressable></View></View></View><View style={styles.content}><Text style={[styles.lessonTitle, { color: colors.text }]}>{lesson.title}</Text><Text style={[styles.protection, { color: colors.textSoft }]}><Ionicons name="shield-checkmark-outline" size={14} color={colors.success} /> بث خاص مؤقت · علامة مائية · حفظ تقدم تلقائي</Text><Card style={styles.notes}><Text style={[styles.notesTitle, { color: colors.text }]}>ملاحظاتي على الدرس</Text><TextInput multiline value={note} onChangeText={setNote} placeholder="اكتب نقاطك المهمة هنا..." placeholderTextColor={colors.textSoft} style={[styles.noteInput, { color: colors.text, backgroundColor: colors.surfaceAlt, borderColor: colors.border }]} textAlign="right" /><AppButton title="حفظ الملاحظة" variant="soft" icon="save-outline" onPress={saveNote} />{noteMessage ? <Text style={[styles.noteMessage, { color: noteMessage.startsWith("تم") ? colors.success : colors.danger }]}>{noteMessage}</Text> : null}</Card></View></Screen>;
}

function formatTime(value: number) { const total = Math.max(0, Math.floor(value || 0)); return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, "0")}`; }
const styles = StyleSheet.create({ playerWrap: { width: "100%", aspectRatio: 16 / 10, backgroundColor: "#02050B", position: "relative" }, video: { width: "100%", height: "100%" }, watermark: { position: "absolute", alignSelf: "center", top: "40%", opacity: .28, transform: [{ rotate: "-15deg" }], alignItems: "center" }, controls: { position: "absolute", left: 0, right: 0, bottom: 0, backgroundColor: "rgba(2,5,11,.74)", paddingHorizontal: 12, paddingBottom: 10, paddingTop: 5 }, slider: { width: "100%", height: 24 }, timeRow: { flexDirection: "row-reverse", justifyContent: "space-between", marginTop: -5 }, controlRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-around", marginTop: 5 }, controlSmall: { width: 40, height: 40, borderRadius: 13, backgroundColor: "rgba(255,255,255,.12)", alignItems: "center", justifyContent: "center" }, controlMain: { width: 50, height: 50, borderRadius: 17, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, privacy: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "#02050B", alignItems: "center", justifyContent: "center", gap: 10, zIndex: 10 }, content: { paddingHorizontal: 18, paddingTop: 18 }, lessonTitle: { fontSize: 21, lineHeight: 31, fontWeight: "900", textAlign: "right" }, protection: { fontSize: 9, textAlign: "right", marginTop: 7 }, notes: { marginTop: 20 }, notesTitle: { fontSize: 14, fontWeight: "900", textAlign: "right", marginBottom: 11 }, noteInput: { minHeight: 140, borderWidth: 1, borderRadius: 15, padding: 12, textAlignVertical: "top", writingDirection: "rtl", marginBottom: 10 }, noteMessage: { fontSize: 9, textAlign: "center", marginTop: 8 }, errorCard: { marginTop: 40, alignItems: "center", gap: 13 }, errorTitle: { fontSize: 19, fontWeight: "900" }, errorText: { fontSize: 11, lineHeight: 19, textAlign: "center" } });
