import React,{useEffect,useRef,useState} from "react";
import {Modal,ScrollView,View} from "react-native";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {AppButton,Card,EmptyState,Field,LoadingState,SectionTitle} from "@/src/components/ui";
import {SearchPicker} from "@/src/components/SearchPicker";
import {ScaledText as Text} from "@/src/components/ScaledText";
import {InstructorPreview} from "@/src/components/instructor-video-preview";
import {api,getApiToken,jsonBody} from "@/src/lib/api";
import {downloadProtectedFile} from "@/src/lib/downloads";
import {useAdminCapabilities} from "@/src/lib/admin-capabilities";
import {MerasAlert} from "@/src/lib/interaction-events";
import {INSTRUCTOR_DOCUMENT_LABELS,type InstructorProfileResponse} from "@/src/lib/instructor";
import {type InstructorAssignment, type InstructorAssignmentDetail,INSTRUCTOR_ASSIGNMENT_LABELS} from "@/src/lib/instructor-assignments";
import {useAuth} from "@/src/providers/AuthProvider";
import {useTheme} from "@/src/providers/ThemeProvider";
type ContractForm={title:string;termsAr:string;termsEn:string;trialTermsAr:string;trialTermsEn:string;compensationModel:"hourly"|"course";rateHalalas:number;trialDays:number;employment:{startDate:string;endDate:string;workLocation:string;weeklyHours:number;nationality:string;paymentTermsAr:string;paymentTermsEn:string;benefitsAr:string;benefitsEn:string}};
type Contract=ContractForm&{id:number;revision:number;version:number;status:string};
type Details=InstructorProfileResponse&{user:InstructorProfileResponse["user"]&{status:string};devices:{id:number;deviceLabel:string;platform:string;policyVersion:number;revokedAt:string|null;returnPolicy:string}[];sessions:{id:number;deviceLabel:string;platform:string;lastSeenAt:string}[]};
const profileLabels:Record<string,string>={draft:"مسودة",submitted:"قيد المراجعة",changes_requested:"مطلوب استكمال",approved:"معتمد",rejected:"مرفوض",suspended:"موقوف"};
const contractLabels:Record<string,string>={draft:"مسودة",offered:"بانتظار التوقيع",signed:"موقع",withdrawn:"مسحوب",terminated:"منتهي"};
export function AdminInstructors(){const capabilities=useAdminCapabilities(),{user}=useAuth();if(!capabilities.owner)return <EmptyState title="خاص بالمدير الأعلى" text="بيانات الشارحين والمستندات والعقود متاحة للمدير الأعلى فقط." />;return <InstructorAdminWorkspace key={user!.id} ownerId={user!.id} />;}
function InstructorAdminWorkspace({ownerId}:{ownerId:number}){
 const {colors}=useTheme();const [search,setSearch]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1),[selected,setSelected]=useState<number|null>(null);
 const list=useQuery({queryKey:["admin-instructors",ownerId,page,query],queryFn:({signal})=>api<{instructors:{id:number;fullName:string;email:string;status:string;specialty:string}[];total:number}>(`/api/admin/instructors?${new URLSearchParams({page:String(page),q:query})}`,{signal}),retry:false});
 if(selected)return <InstructorAdminDetail key={selected} ownerId={ownerId} userId={selected} close={()=>setSelected(null)} />;
 return <View style={{gap:14}}><SectionTitle title="فريق مراس — الشارحون" subtitle="مراجعة الطلبات والمستندات والعقود والتكليفات" /><Field label="البحث بالاسم أو البريد" value={search} onChangeText={setSearch} /><AppButton title="بحث" onPress={()=>{setPage(1);setQuery(search);}} />{list.isLoading?<LoadingState />:list.isError?<Text style={{color:colors.danger}}>{list.error.message}</Text>:list.data?.instructors.map(item=><Card key={item.id} style={{gap:8}}><Text style={{color:colors.text,fontSize:20,fontWeight:"800",textAlign:"right"}}>{item.fullName}</Text><Text selectable style={{color:colors.textSoft,textAlign:"right"}}>{item.email} · {profileLabels[item.status]||item.status}</Text><Text style={{color:colors.textSoft,textAlign:"right"}}>{item.specialty}</Text><AppButton title="مراجعة ملف الشارح" variant="soft" onPress={()=>setSelected(item.id)} /></Card>)}{list.data&&!list.data.instructors.length?<Text style={{color:colors.textSoft}}>لا توجد طلبات مطابقة.</Text>:null}<AppButton title="السابق" variant="ghost" disabled={page<=1} onPress={()=>setPage(value=>value-1)} /><AppButton title="التالي" variant="ghost" disabled={!list.data||page*30>=list.data.total} onPress={()=>setPage(value=>value+1)} /><AppButton title="تحديث القائمة" variant="ghost" onPress={()=>void list.refetch()} /></View>;
}
function InstructorAdminDetail({ownerId,userId,close}:{ownerId:number;userId:number;close:()=>void}){
 const {colors}=useTheme(),client=useQueryClient();const [reason,setReason]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[editor,setEditor]=useState<(ContractForm&{id?:number;revision?:number})|null>(null),[course,setCourse]=useState(""),[instructions,setInstructions]=useState(""),[assignmentId,setAssignmentId]=useState<number|null>(null),[preview,setPreview]=useState<number|null>(null);
 const pending=useRef(false),mounted=useRef(true),controller=useRef<AbortController|null>(null);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 const detail=useQuery({queryKey:["admin-instructor-detail",ownerId,userId],queryFn:({signal})=>api<Details>(`/api/admin/instructors?userId=${userId}`,{signal}),retry:false});
 const contracts=useQuery({queryKey:["admin-instructor-contracts",ownerId,userId],queryFn:({signal})=>api<{contracts:Contract[];template:Pick<ContractForm,"title"|"termsAr"|"termsEn"|"trialTermsAr"|"trialTermsEn">}>(`/api/admin/instructors/contracts?userId=${userId}`,{signal}),enabled:Boolean(detail.data),retry:false});
 const assignments=useQuery({queryKey:["admin-instructor-assignments",ownerId,userId],queryFn:({signal})=>api<{assignments:InstructorAssignment[]}>(`/api/admin/instructors/assignments?userId=${userId}`,{signal}),enabled:Boolean(detail.data),retry:false});
 const catalog=useQuery({queryKey:["catalog"],queryFn:({signal})=>api<{courses:{slug:string;title:string;university:string}[]}>("/api/mobile/catalog",{signal}),enabled:Boolean(detail.data),retry:false});
 const content=useQuery({queryKey:["admin-instructor-content",ownerId,userId,assignmentId],queryFn:({signal})=>api<InstructorAssignmentDetail>(`/api/instructor/assignments/${assignmentId}`,{signal}),enabled:Boolean(assignmentId),retry:false});
 async function run(work:(signal:AbortSignal,token:string)=>Promise<void>){if(pending.current)return;const token=getApiToken();pending.current=true;setBusy(true);setMessage("");const abort=new AbortController();controller.current=abort;try{await work(abort.signal,token);}catch(error){if(mounted.current&&token===getApiToken())setMessage(error instanceof Error?error.message:"تعذر إكمال الإجراء");}finally{pending.current=false;controller.current=null;if(mounted.current)setBusy(false);}}
 async function post(path:string,body:object){await run(async(signal,token)=>{await api(path,{method:"POST",body:jsonBody(body),signal});if(!mounted.current||token!==getApiToken())return;setMessage("تم حفظ الإجراء");setEditor(null);setPreview(null);await Promise.all([detail.refetch(),contracts.refetch(),assignments.refetch(),assignmentId?content.refetch():Promise.resolve(),client.invalidateQueries({queryKey:["admin-instructors",ownerId]})]);});}
 function confirm(title:string,path:string,body:object,description="سيُحفظ هذا الإجراء في سجل التدقيق."){const token=getApiToken();MerasAlert.alert(title,description,[{text:"إلغاء",style:"cancel"},{text:title,onPress:()=>{if(mounted.current&&token===getApiToken())void post(path,body);}}]);}
 function download(path:string,name:string,mime:string){void run(async(signal,token)=>{await api(`/api/admin/instructors?userId=${userId}`,{signal});if(!mounted.current||token!==getApiToken())return;await downloadProtectedFile({path,fileName:name,mimeType:mime,saveToFiles:true});});}
 const text={color:colors.textSoft,fontSize:14,lineHeight:25,textAlign:"right" as const};
 if(detail.isLoading)return <LoadingState />;
 if(!detail.data)return <View style={{gap:12}}><EmptyState title="تعذر فتح الملف" text={detail.error?.message||"قد يلزم التحقق الإداري الإضافي."} /><AppButton title="إعادة المحاولة والتحقق" onPress={()=>void detail.refetch()} /><AppButton title="العودة للقائمة" variant="ghost" onPress={close} /></View>;
 const data=detail.data,available=data.user.status!=="deleted";
 const review=(action:string,label:string)=>confirm(label,"/api/admin/instructors",{action,userId,expectedRevision:data.profile.revision,reason});
 const startContract=()=>{if(!contracts.data)return;setEditor({...contracts.data.template,compensationModel:data.profile.compensationModel,rateHalalas:5000,trialDays:30,employment:{startDate:"",endDate:"",workLocation:"",weeklyHours:0,nationality:"",paymentTermsAr:"",paymentTermsEn:"",benefitsAr:"",benefitsEn:""}});};
 const contractAction=(contract:Contract,action:string,title:string)=>confirm(title,"/api/admin/instructors/contracts",{action,userId,id:contract.id,expectedRevision:contract.revision,reason},action==="offer"?"سيصل العقد إلى الشارح بهذه النسخة. راجع البنود والمبالغ والتجربة والبيانات النظامية قبل تقديمه.":undefined);
 return <View style={{gap:16}}><AppButton title="العودة لقائمة الشارحين" variant="ghost" disabled={busy} onPress={close} /><SectionTitle title={data.user.fullName} subtitle={profileLabels[data.profile.status]||data.profile.status} /><Card style={{gap:8}}><Text selectable style={text}>{data.user.email} · {data.user.phone}</Text><Text style={text}>{data.profile.country} · {data.profile.gender==="female"?"أنثى":"ذكر"} · {data.profile.qualification} · {data.profile.specialty}</Text><Text selectable style={text}>{data.profile.address}</Text><Text style={text}>{data.profile.bio}</Text><Text style={text}>مواد الشرح: {data.profile.teachingSubjects}</Text><Text style={text}>نظام العمل: {data.profile.compensationModel==="hourly"?"بالساعات":"بالمادة"}</Text>{data.profile.bank?<Text selectable style={text}>البنك: {data.profile.bank.bankName} — {data.profile.bank.accountHolder}{"\n"}{data.profile.bank.iban}</Text>:null}<Text style={text}>ملاحظات المراجعة: {data.profile.reviewNotes||"—"}</Text></Card>
  <SectionTitle title="المستندات" />{data.documents.map(document=><Card key={document.id} style={{gap:8}}><Text style={text}>{INSTRUCTOR_DOCUMENT_LABELS[document.kind]} · {document.originalName}</Text><AppButton title="تحميل المستند للمراجعة" variant="soft" disabled={busy} onPress={()=>download(`/api/instructor/documents/${document.id}`,document.originalName,document.contentType)} /></Card>)}
  <Field label="سبب القرار أو ملاحظة المراجعة" value={reason} onChangeText={setReason} multiline maxLength={1000} editable={!busy} /><Text style={text}>تستخدم هذه الملاحظة لقرارات الملف والعقد والمادة، وتصل للشارح حيث ينطبق ذلك.</Text>{available?<View style={{gap:8}}>{data.profile.status==="submitted"?<><AppButton title="اعتماد الشارح" disabled={busy||reason.trim().length<5} onPress={()=>review("approve","اعتماد الشارح")} /><AppButton title="رفض الطلب" variant="danger" disabled={busy||reason.trim().length<5} onPress={()=>review("reject","رفض الطلب")} /></>:null}{["submitted","rejected"].includes(data.profile.status)?<AppButton title="إعادة لاستكمال البيانات" variant="soft" disabled={busy||reason.trim().length<5} onPress={()=>review("request_changes","طلب استكمال الملف")} />:null}<AppButton title={data.profile.status==="suspended"?"إعادة فتح الملف للاستكمال":"إيقاف حساب الشارح"} variant="danger" disabled={busy||reason.trim().length<5} onPress={()=>review(data.profile.status==="suspended"?"resume":"suspend",data.profile.status==="suspended"?"إعادة فتح الملف":"إيقاف الحساب")} /></View>:<Text style={text}>الحساب محذوف؛ تبقى العقود والأعمال اللازمة وفق سياسة الاحتفاظ.</Text>}
  <SectionTitle title="الأجهزة والجلسات" />{data.devices.map(device=><Card key={device.id} style={{gap:8}}><Text style={text}>{device.deviceLabel} · {device.platform} · {device.revokedAt?"مسحوب الاعتماد":"معتمد"}</Text>{available?<>{[{action:"end_sessions",label:"إنهاء جلسات الجهاز"},{action:"revoke_block",label:"سحب الاعتماد ومنع العودة"},{action:"allow_return",label:"السماح للجهاز المسحوب بالعودة"}].filter(item=>item.action!=="allow_return"||device.revokedAt).map(item=><AppButton key={item.action} title={item.label} variant="ghost" disabled={busy||reason.trim().length<5} onPress={()=>confirm(item.label,"/api/admin/instructors",{action:"device",userId,expectedRevision:data.profile.revision,deviceId:device.id,expectedDeviceRevision:device.policyVersion,deviceAction:item.action,reason})} />)}</>:null}</Card>)}<Text style={text}>الجلسات الحالية: {data.sessions.length}</Text>
  <SectionTitle title="العقود" />{contracts.isError?<Text style={text}>{contracts.error.message}</Text>:null}{contracts.data?.contracts.map(contract=><Card key={contract.id} style={{gap:10}}><Text style={{...text,color:colors.text,fontWeight:"800"}}>{contract.title} · نسخة {contract.version} · {contractLabels[contract.status]||contract.status}</Text><Text style={text}>{(contract.rateHalalas/100).toFixed(2)} ريال / {contract.compensationModel==="hourly"?"ساعة":"مادة"} · تجربة {contract.trialDays} يومًا</Text><AppButton title="قراءة البنود والبيانات" variant="soft" disabled={busy} onPress={()=>setEditor(contract)} /><AppButton title="تنزيل العقد PDF" variant="ghost" disabled={busy} onPress={()=>download(`/api/admin/instructors/contracts/${contract.id}/download`,`meras-contract-${contract.id}.pdf`,"application/pdf")} />{contract.status==="draft"&&available?<AppButton title="تقديم العقد للشارح" disabled={busy} onPress={()=>contractAction(contract,"offer","تقديم العقد")} />:null}{contract.status==="offered"?<AppButton title="سحب العرض" variant="danger" disabled={busy||reason.trim().length<5} onPress={()=>contractAction(contract,"withdraw","سحب العرض")} />:null}{contract.status==="signed"?<AppButton title="إنهاء العقد بإجراء موثق" variant="danger" disabled={busy||reason.trim().length<5} onPress={()=>contractAction(contract,"terminate","إنهاء العقد")} />:null}</Card>)}<AppButton title="إنشاء مسودة عقد جديدة" disabled={busy||!contracts.data||data.profile.status!=="approved"||!available} onPress={startContract} />
  <SectionTitle title="إسناد المواد ومراجعتها" />{available&&data.profile.status==="approved"?<Card style={{gap:12}}><SearchPicker label="المادة" placeholder="اختر مادة منشورة بالمنصة" value={course} items={(catalog.data?.courses||[]).map(item=>({key:item.slug,label:item.title,detail:item.university}))} onSelect={item=>setCourse(item.key)} disabled={busy} /><Field label="تعليمات الشرح" value={instructions} onChangeText={setInstructions} multiline maxLength={6000} editable={!busy} /><AppButton title="إسناد المادة للعقد الساري" disabled={busy||!course||!contracts.data?.contracts.some(contract=>contract.status==="signed")} onPress={()=>confirm("إسناد المادة","/api/admin/instructors/assignments",{action:"create",userId,contractId:contracts.data?.contracts.find(contract=>contract.status==="signed")?.id,courseSlug:course,instructions})} /></Card>:null}{assignments.data?.assignments.map(item=><Card key={item.id} style={{gap:9}}><Text style={{...text,color:colors.text,fontWeight:"800"}}>{item.courseTitle}</Text><Text style={text}>{INSTRUCTOR_ASSIGNMENT_LABELS[item.status]||item.status}</Text><AppButton title="مراجعة الوحدات والفيديوهات" variant="soft" disabled={busy} onPress={()=>{setPreview(null);setAssignmentId(item.id);}} />{item.status==="submitted"?<><AppButton title="اعتماد المحتوى ونشره" disabled={busy||reason.trim().length<5} onPress={()=>confirm("نشر الشرح",`/api/admin/instructors/assignments/${item.id}`,{action:"publish",expectedRevision:item.revision,reason},"سيصبح شرح هذه المهمة متاحًا للطلاب ضمن المادة. تأكد من مراجعة جميع الفيديوهات وحقوق المحتوى.")} /><AppButton title="إعادة للشارح مع ملاحظات" variant="soft" disabled={busy||reason.trim().length<5} onPress={()=>confirm("إعادة للمراجعة",`/api/admin/instructors/assignments/${item.id}`,{action:"return_changes",expectedRevision:item.revision,reason})} /></>:null}{!["published","cancelled"].includes(item.status)?<AppButton title="إلغاء التكليف" variant="danger" disabled={busy||reason.trim().length<5} onPress={()=>confirm("إلغاء التكليف",`/api/admin/instructors/assignments/${item.id}`,{action:"cancel",expectedRevision:item.revision,reason})} />:null}</Card>)}
  {assignmentId?<Card style={{gap:10}}><SectionTitle title="محتوى المهمة المختارة" />{content.isLoading?<LoadingState />:content.isError?<Text style={text}>{content.error.message}</Text>:content.data?.units.map(unit=><View key={unit.id} style={{gap:8}}><Text style={{...text,color:colors.text,fontWeight:"800"}}>{unit.title}</Text><Text style={text}>{unit.description}</Text>{unit.lessons.map(lesson=><View key={lesson.id} style={{gap:6}}><Text style={text}>{lesson.title} · {lesson.video?.processingStatus||"بلا فيديو"}</Text><Text style={text}>{lesson.description}</Text>{lesson.video?<AppButton title="معاينة شرح الدرس" variant="ghost" disabled={busy} onPress={()=>setPreview(lesson.id)} />:null}</View>)}</View>)}{preview?<InstructorPreview key={`${assignmentId}:${preview}`} path={`/api/instructor/assignments/${assignmentId}/videos/${preview}`} />:null}<AppButton title="إغلاق مراجعة المحتوى" variant="ghost" onPress={()=>{setPreview(null);setAssignmentId(null);}} /></Card>:null}
  {message?<Text accessibilityLiveRegion="polite" style={{...text,color:colors.primary}}>{message}</Text>:null}<AppButton title="تحديث الملف والعقود والمواد" variant="ghost" disabled={busy} onPress={()=>{void detail.refetch();void contracts.refetch();void assignments.refetch();}} />
  <ContractEditor value={editor} setValue={setEditor} busy={busy} message={message} editable={Boolean(editor&&available&&(!editor.id||contracts.data?.contracts.find(item=>item.id===editor.id)?.status==="draft"))} save={()=>{if(editor)void post("/api/admin/instructors/contracts",{...editor,action:"save",userId,expectedRevision:editor.revision});}} />
 </View>;
}
function ContractEditor({value,setValue,busy,message,editable,save}:{value:(ContractForm&{id?:number;revision?:number})|null;setValue:React.Dispatch<React.SetStateAction<(ContractForm&{id?:number;revision?:number})|null>>;busy:boolean;message:string;editable:boolean;save:()=>void}){
 const {colors}=useTheme();const textFields=[{key:"title",label:"عنوان العقد"},{key:"termsAr",label:"البنود العربية"},{key:"termsEn",label:"English terms"},{key:"trialTermsAr",label:"شروط التجربة بالعربية"},{key:"trialTermsEn",label:"English probation terms"}] as const;
 const employmentFields=[{key:"startDate",label:"المباشرة YYYY-MM-DD"},{key:"endDate",label:"نهاية العقد YYYY-MM-DD (اختياري)"},{key:"workLocation",label:"مكان العمل"},{key:"nationality",label:"الجنسية"},{key:"paymentTermsAr",label:"آلية ومواعيد الأجر بالعربية"},{key:"paymentTermsEn",label:"English payment terms"},{key:"benefitsAr",label:"المزايا والحقوق بالعربية"},{key:"benefitsEn",label:"English benefits"}] as const;
 return <Modal visible={Boolean(value)} animationType="slide" onRequestClose={()=>!busy&&setValue(null)}><View style={{flex:1,padding:20,paddingTop:45,backgroundColor:colors.background}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{gap:14,paddingBottom:30}}><SectionTitle title={editable?"تحرير مسودة العقد":"قراءة العقد"} subtitle="الأرقام النظامية والشعار من إعدادات المنصة؛ تحفظ في النسخة المقدمة" />{textFields.map(field=><Field key={field.key} label={field.label} value={value?.[field.key]||""} multiline maxLength={field.key.startsWith("terms")?30000:3000} inputDirection={field.key.endsWith("En")?"ltr":"natural"} editable={editable&&!busy} onChangeText={text=>setValue(old=>old?{...old,[field.key]:text}:null)} />)}<SearchPicker label="نظام الأجر" placeholder="اختر" value={value?.compensationModel} items={[{key:"hourly",label:"بالساعة"},{key:"course",label:"بالمادة"}]} disabled={!editable||busy} onSelect={item=>setValue(old=>old?{...old,compensationModel:item.key as "hourly"|"course"}:null)} /><Field label="الأجر بالريال" value={String((value?.rateHalalas||0)/100)} keyboardType="decimal-pad" editable={editable&&!busy} onChangeText={text=>setValue(old=>old?{...old,rateHalalas:Math.round(Number(text)*100)||0}:null)} /><Field label="مدة التجربة بالأيام (0–180)" value={String(value?.trialDays||0)} keyboardType="number-pad" editable={editable&&!busy} onChangeText={text=>setValue(old=>old?{...old,trialDays:Number(text)||0}:null)} />{employmentFields.map(field=><Field key={field.key} label={field.label} value={value?.employment[field.key]||""} multiline maxLength={3000} inputDirection={field.key.endsWith("En")||field.key.endsWith("Date")?"ltr":"natural"} editable={editable&&!busy} onChangeText={text=>setValue(old=>old?{...old,employment:{...old.employment,[field.key]:text}}:null)} />)}<Field label="ساعات العمل الأسبوعية" value={String(value?.employment.weeklyHours||0)} keyboardType="number-pad" editable={editable&&!busy} onChangeText={text=>setValue(old=>old?{...old,employment:{...old.employment,weeklyHours:Number(text)||0}}:null)} />{message?<Text style={{color:colors.primary,textAlign:"right"}}>{message}</Text>:null}{editable?<AppButton title="حفظ المسودة" loading={busy} onPress={save} />:null}<AppButton title="إغلاق" variant="ghost" disabled={busy} onPress={()=>setValue(null)} /></ScrollView></View></Modal>;
}
