import React,{useState} from "react";
import {View} from "react-native";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {AppButton,Card,Field,LoadingState,EmptyState} from "@/src/components/ui";
import {SearchPicker} from "@/src/components/SearchPicker";
import {ScaledText as Text} from "@/src/components/ScaledText";
import {api,jsonBody,isAdminStepUpError,ADMIN_STEP_UP_MESSAGE} from "@/src/lib/api";
import {useTheme} from "@/src/providers/ThemeProvider";
type Audience={course:{slug:string;title:string;managed:boolean;enrollmentMode:"auto"|"open"|"closed";availableForPurchase:boolean;updatedAt:string|null};summary:{subscriptions:number;active:number;waiting:number;notified:number;converted:number};items:Array<{id:number;userEmail:string;fullName:string|null;phone:string|null;status:string}>;pagination:{page:number;total:number;totalPages:number}};
const labels:Record<string,string>={active:"نشط",suspended:"موقوف",scheduled:"مجدول",expired:"منتهٍ",revoked:"ملغي",notified:"أُنشئ له تنبيه",converted:"اشترك",cancelled:"ألغى"};
export function AdminCourseAudience({slug,onOpenStudent,onStepUpRequired}:{slug:string;onOpenStudent:(email:string)=>void;onStepUpRequired?:(message:string)=>void}) {
 const {colors}=useTheme();const client=useQueryClient();const [kind,setKind]=useState("subscriptions");const [status,setStatus]=useState("all");const [query,setQuery]=useState("");const [search,setSearch]=useState("");const [page,setPage]=useState(1);const [mode,setMode]=useState<string|null>(null);const [modeVersion,setModeVersion]=useState<string|null>(null);const [reason,setReason]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const result=useQuery({queryKey:["admin-course-audience",slug,kind,status,search,page],queryFn:()=>api<Audience>(`/api/admin/courses/${encodeURIComponent(slug)}/audience?kind=${kind}&status=${status}&q=${encodeURIComponent(search)}&page=${page}`)});
 const data=result.data;const statusValues=kind==="waitlist"?["active","notified","converted","cancelled"]:["active","suspended","scheduled","expired","revoked"];
 async function mutate(action:string){if(!data||busy)return;if(reason.trim().length<3){setMessage("اكتب سبب الإجراء من ثلاثة أحرف على الأقل");return;}setBusy(true);setMessage("");try{const response=await api<{message:string}>(`/api/admin/courses/${encodeURIComponent(slug)}/audience`,{method:"POST",body:jsonBody({action,reason,enrollmentMode:mode||data.course.enrollmentMode,expectedUpdatedAt:modeVersion||data.course.updatedAt}),timeoutMs:120000});setMessage(response.message);setMode(null);setModeVersion(null);await client.invalidateQueries({queryKey:["admin-course-audience",slug]});await client.invalidateQueries({queryKey:["admin-console"]});await client.invalidateQueries({queryKey:["catalog"]});}catch(e){if(isAdminStepUpError(e)){onStepUpRequired?.(ADMIN_STEP_UP_MESSAGE);setMessage(ADMIN_STEP_UP_MESSAGE);}else setMessage(e instanceof Error?e.message:"تعذر تنفيذ الإجراء");}finally{setBusy(false);}}
 if(result.isLoading)return <LoadingState label="تحميل مشتركي المادة والمنتظرين…"/>;
 if(!data)return <EmptyState icon="cloud-offline-outline" title="تعذر تحميل المادة" text={result.error instanceof Error?result.error.message:"حاول مرة أخرى"} action={<AppButton title="إعادة المحاولة" onPress={()=>void result.refetch()}/>}/>;
 return <Card style={{gap:14,marginVertical:12}}><Text style={{color:colors.text,fontSize:18,fontWeight:"800",textAlign:"right"}}>{data.course.title}</Text><Text style={{color:colors.text,textAlign:"right",lineHeight:24}}>السجلات: {data.summary.subscriptions} · وصول نشط: {data.summary.active} · ينتظر الإتاحة: {data.summary.waiting} · أُنشئ له تنبيه: {data.summary.notified} · اشترك بعد الانتظار: {data.summary.converted}</Text>
 <SearchPicker label="حالة فتح الاشتراك" value={mode||data.course.enrollmentMode} disabled={busy} placeholder="اختر الحالة" items={[{key:"auto",label:"تلقائي مع جاهزية درس"},{key:"open",label:"مفتوح دون اشتراط اكتمال الفيديوهات"},{key:"closed",label:"مغلق مع استقبال طلبات التنبيه"}]} onSelect={row=>{setMode(row.key);setModeVersion(data.course.updatedAt);}}/><Field label="سبب تعديل الإتاحة أو إرسال التنبيهات" value={reason} onChangeText={setReason}/><View style={{gap:8}}><AppButton title="حفظ حالة الاشتراك" disabled={busy||!data.course.managed} loading={busy} onPress={()=>void mutate("setEnrollment")}/><AppButton title="معالجة دفعة تنبيهات الإتاحة" variant="soft" disabled={busy} onPress={()=>void mutate("dispatchLaunch")}/></View>{!data.course.managed?<Text style={{color:colors.textSoft,textAlign:"right"}}>هذه مادة قالب؛ احفظها من تعديل المادة في إدارة الويب أولًا.</Text>:null}
 <SearchPicker label="القائمة" value={kind} placeholder="اختر القائمة" items={[{key:"subscriptions",label:"المشتركون"},{key:"waitlist",label:"من فعّلوا تنبيه الإتاحة"}]} onSelect={row=>{setKind(row.key);setStatus("all");setPage(1);}}/>
 <SearchPicker label="تصفية الحالة" value={status} placeholder="الكل" items={[{key:"all",label:"كل الحالات"},...statusValues.map(key=>({key,label:labels[key]||key}))]} onSelect={row=>{setStatus(row.key);setPage(1);}}/><Field label="الاسم أو البريد أو الجوال" value={query} onChangeText={setQuery}/><AppButton title="بحث" variant="ghost" onPress={()=>{setSearch(query);setPage(1);}}/>
 {data.items.length?data.items.map(row=><View key={row.id} style={{gap:6,borderTopWidth:1,borderColor:colors.border,paddingTop:10}}><Text style={{color:colors.text,textAlign:"right",fontWeight:"700"}}>{row.fullName||row.userEmail}</Text><Text style={{color:colors.textSoft,textAlign:"right"}}>{row.userEmail} · {row.phone||""} · {kind==="waitlist"&&row.status==="active"?"بانتظار الإتاحة":labels[row.status]||row.status}</Text><AppButton title="فتح ملف الطالب والتحكم به" variant="ghost" onPress={()=>onOpenStudent(row.userEmail)}/></View>):<Text style={{color:colors.textSoft,textAlign:"right"}}>لا توجد نتائج لهذه التصفية.</Text>}
 <View style={{gap:8}}><Text style={{color:colors.textSoft,textAlign:"right"}}>صفحة {data.pagination.page} / {data.pagination.totalPages} · {data.pagination.total} سجل</Text><AppButton title="السابق" disabled={data.pagination.page<=1||result.isFetching} variant="ghost" onPress={()=>setPage(data.pagination.page-1)}/><AppButton title="التالي" disabled={data.pagination.page>=data.pagination.totalPages||result.isFetching} variant="ghost" onPress={()=>setPage(data.pagination.page+1)}/></View>
 {message?<Text accessibilityLiveRegion="polite" style={{color:colors.text,textAlign:"right",lineHeight:24}}>{message}</Text>:null}<Text style={{color:colors.textSoft,textAlign:"right",lineHeight:22}}>أعداد التنبيهات تشير إلى التسجيل والطابور. وصول Push يحتاج إذن الإشعارات ومزودًا مهيأ؛ قبول المزود ليس تأكيد قراءة.</Text></Card>;
}
