import { useQuery } from "@tanstack/react-query";
import React, { useState } from "react";
import { View } from "react-native";
import { ScaledText as Text } from "@/src/components/ScaledText";
import { SearchPicker } from "@/src/components/SearchPicker";
import { AppButton, Card, EmptyState, Field, LoadingState } from "@/src/components/ui";
import { api, ApiError } from "@/src/lib/api";
import { useTheme } from "@/src/providers/ThemeProvider";
type Row = { id: number; userEmail: string; status: string; source: string; startsAt?: string; expiresAt?: string | null; createdAt?: string; notifiedAt?: string | null; student: { fullName: string; phone: string | null } | null };
type Roster = { rows: Row[]; totals: Record<string, number>; pagination: { page: number; pageSize: number; total: number } };
const labels: Record<string, string> = { all: "كل الحالات", active: "نشط", suspended: "موقوف", revoked: "ملغي", expired: "منتهي", scheduled: "مجدول", notified: "أُبلغ", converted: "حصل على الوصول", cancelled: "ألغى" };
export function AdminCourseRoster({ courses, onOpenStudent, initialSlug = "" }: { initialSlug?: string; courses: { slug: string; title: string; university: string }[]; onOpenStudent: (email: string) => void }) {
  const { colors } = useTheme(); const [slug, setSlug] = useState(initialSlug); const [kind, setKind] = useState("subscriptions"); const [status, setStatus] = useState("all"); const [draft, setDraft] = useState(""); const [q, setQ] = useState(""); const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ["admin-course-roster", slug, kind, status, q, page], queryFn: ({ signal }) => api<Roster>(`/api/admin/courses/${encodeURIComponent(slug)}?${new URLSearchParams({ kind, status, q, page: String(page) })}`, { signal }), enabled: Boolean(slug), retry: 1 });
  const count = query.data?.pagination; const states = kind === "waitlist" ? ["all", "active", "notified", "converted", "cancelled"] : ["all", "active", "suspended", "revoked", "expired", "scheduled"];
  return <View style={{ gap: 12 }}><Card><SearchPicker placeholder="اختر من القائمة" label="المادة" value={slug} items={courses.map(course => ({ key: course.slug, label: course.title, detail: course.university }))} onSelect={item => { setSlug(item.key); setPage(1); }} /><SearchPicker placeholder="اختر من القائمة" label="القائمة" value={kind} items={[{ key: "subscriptions", label: "المشتركون والوصول" }, { key: "waitlist", label: "تنبيهات التوفر والانتظار" }]} onSelect={item => { setKind(item.key); setStatus("all"); setPage(1); }} /><SearchPicker placeholder="اختر من القائمة" label="الحالة" value={status} items={states.map(key => ({ key, label: labels[key] || key }))} onSelect={item => { setStatus(item.key); setPage(1); }} /><Field label="الاسم أو البريد أو الجوال" value={draft} onChangeText={setDraft} /><AppButton title="بحث في جميع السجلات" onPress={() => { setQ(draft.trim()); setPage(1); }} /></Card>
    {!slug && <EmptyState title="اختر المادة" text="تظهر هنا أسماء المشتركين ومن فعّلوا تنبيه توفرها." icon="school-outline" />}
    {slug && query.isLoading && <LoadingState label="جارٍ تحميل السجلات" />}
    {query.isError && <EmptyState title="تعذر تحميل السجلات" text={query.error instanceof ApiError ? query.error.message : "تحقق من الاتصال"} icon="cloud-offline-outline" action={<AppButton title="إعادة المحاولة" onPress={() => void query.refetch()} />} />}
    {query.data && <><Card><Text selectable style={{ color: colors.text }}>المشتركون النشطون: {query.data.totals.active} · المنتظرون: {query.data.totals.waiting} · أُبلغوا: {query.data.totals.notified}</Text></Card>{query.data.rows.map(row => <Card key={row.id}><Text selectable style={{ color: colors.text, fontWeight: "800", textAlign: "right" }}>{row.student?.fullName || row.userEmail}</Text><Text selectable style={{ color: colors.textSoft }}>{row.userEmail} · {row.student?.phone}</Text><Text style={{ color: colors.primary }}>{labels[row.status] || row.status} · {row.source}</Text><Text style={{ color: colors.textSoft }}>{kind === "waitlist" ? `طلب التنبيه: ${row.createdAt ? new Date(row.createdAt).toLocaleDateString("ar-SA") : "—"} · أُبلغ: ${row.notifiedAt ? new Date(row.notifiedAt).toLocaleDateString("ar-SA") : "لم يرسل بعد"}` : `حتى ${row.expiresAt ? new Date(row.expiresAt).toLocaleDateString("ar-SA") : "دون انتهاء"}`}</Text><AppButton title="فتح ملف الطالب والتحكم" variant="soft" onPress={() => onOpenStudent(row.userEmail)} /></Card>)}{!query.data.rows.length && <EmptyState title="لا توجد سجلات مطابقة" text="يمكن تعديل البحث أو الحالة." icon="search-outline" />}{count && <View style={{ gap: 8 }}><Text style={{ color: colors.text }}>صفحة {page} من {Math.max(1, Math.ceil(count.total / count.pageSize))} · {count.total} سجل</Text><View style={{ flexDirection: "row", gap: 8 }}><AppButton full={false} title="السابق" disabled={page <= 1 || query.isFetching} onPress={() => setPage(page - 1)} /><AppButton full={false} title="التالي" disabled={page * count.pageSize >= count.total || query.isFetching} onPress={() => setPage(page + 1)} /></View></View>}</>}
  </View>;
}
