import React,{useState} from "react";
import {View} from "react-native";
import {Card,AppButton,Field} from "@/src/components/ui";
import {SearchPicker} from "@/src/components/SearchPicker";
import {ScaledText as Text} from "@/src/components/ScaledText";
import {api,jsonBody,isAdminStepUpError,ADMIN_STEP_UP_MESSAGE} from "@/src/lib/api";
import {useTheme} from "@/src/providers/ThemeProvider";
export function AdminAiDiagnostics({keys,onChanged,onStepUpRequired}:{keys:Array<{id:number;label:string;updatedAt:string;lastSuccessAt:string|null}>;onChanged:()=>void|Promise<unknown>;onStepUpRequired?:(message:string)=>void}) {
 const {colors}=useTheme();const [service,setService]=useState("chat");const [id,setId]=useState("");const [replacement,setReplacement]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function run(body:Record<string,unknown>){setBusy(true);setMessage("");try{const result=await api<{message:string;diagnostic?:{model:string;keyId:number|null;inputTokens:number;outputTokens:number}}>("/api/admin/ai",{method:"POST",body:jsonBody(body),timeoutMs:130000});const d=result.diagnostic;setMessage(result.message+(d?` النموذج ${d.model} · مفتاح ${d.keyId||"بيئة الخادم"} · ${d.inputTokens} إدخال / ${d.outputTokens} إخراج`:""));if(!d)setReplacement("");await onChanged();}catch(e){if(isAdminStepUpError(e)){onStepUpRequired?.(ADMIN_STEP_UP_MESSAGE);setMessage(ADMIN_STEP_UP_MESSAGE);}else setMessage(e instanceof Error?e.message:"تعذر الفحص");}finally{setBusy(false);}}
 return <Card style={{gap:12,marginVertical:12}}><Text style={{color:colors.text,textAlign:"right",fontWeight:"800",fontSize:16}}>فحص التشغيل الفعلي</Text><Text style={{color:colors.textSoft,textAlign:"right",lineHeight:22}}>الحفظ لا يثبت صلاحية المفتاح. يولّد الفحص نصًا تجريبيًا من إعدادات الخدمة المحفوظة وقد يستهلك حصة المزود؛ رفع الملفات يحتاج اختبارًا مستقلًا.</Text><SearchPicker label="الخدمة" value={service} placeholder="اختر الخدمة" disabled={busy} items={[{key:"chat",label:"المحادثة"},{key:"summary",label:"التلخيص"},{key:"translation",label:"الترجمة"},{key:"quiz",label:"الاختبارات وبنية JSON"}]} onSelect={row=>setService(row.key)}/><AppButton title="اختبار الخدمة فعليًا" loading={busy} onPress={()=>void run({action:"testRuntime",service})}/><SearchPicker label="استبدال مفتاح محفوظ — اختياري" value={id} placeholder="اختر المفتاح" disabled={busy} items={keys.map(row=>({key:String(row.id),label:row.label,detail:row.lastSuccessAt?"اختُبر سابقًا":"لم يُختبر التوليد"}))} onSelect={row=>setId(row.key)}/>{id?<View style={{gap:10}}><Field label="المفتاح الجديد" value={replacement} onChangeText={setReplacement} secureTextEntry autoCapitalize="none" autoCorrect={false} inputDirection="ltr"/><AppButton title="تأكيد الاستبدال المشفر" variant="soft" disabled={busy||replacement.trim().length<20} onPress={()=>{const key=keys.find(row=>row.id===Number(id));if(key)void run({action:"replaceKey",id:key.id,apiKey:replacement,expectedUpdatedAt:key.updatedAt});}}/></View>:null}{message?<Text accessibilityLiveRegion="polite" style={{color:colors.text,textAlign:"right",lineHeight:24}}>{message}</Text>:null}</Card>;
}
