import { Ionicons } from "@expo/vector-icons";
import React from "react";
import { Pressable, StyleSheet, View } from "react-native";
import { ScaledText as Text } from "@/src/components/ScaledText";
import { Card, SectionTitle } from "@/src/components/ui";
import { useTheme, type FontScale } from "@/src/providers/ThemeProvider";
import { paletteLabels, type PaletteId } from "@/src/theme/colors";

const palettes: { id: PaletteId; colors: [string, string] }[] = [
  { id: "official", colors: ["#155EEF", "#7445F5"] },
  { id: "violet", colors: ["#6D45E8", "#D86AF4"] },
  { id: "rose", colors: ["#D83F78", "#F08AAA"] },
  { id: "teal", colors: ["#078F96", "#35C6B2"] },
];
const fontScales: { value: FontScale; label: string; icon: "remove" | "text" | "add" | "add-circle-outline" }[] = [{ value: .9, label: "صغير", icon: "remove" }, { value: 1, label: "قياسي", icon: "text" }, { value: 1.1, label: "كبير", icon: "add" }, { value: 1.2, label: "أكبر", icon: "add-circle-outline" }];

export function AppearanceSettings() {
  const { colors, dark, mode, palette, fontScale, setMode, setPalette, setFontScale } = useTheme();
  return <View style={styles.wrap}><SectionTitle title="مظهر هذا الجهاز" subtitle="تُحفظ الألوان وحجم النص على هذا الجهاز فقط، وتُطبّق مباشرة في كل أجزاء التطبيق عليه." /><Card style={styles.card}><Text style={[styles.label, { color: colors.text }]}>الوضع</Text><View style={styles.row}>{([{ key: "system", title: "تلقائي", icon: "phone-portrait-outline" }, { key: "light", title: "فاتح", icon: "sunny-outline" }, { key: "dark", title: "ليلي", icon: "moon-outline" }] as const).map((item) => <Pressable key={item.key} accessibilityRole="button" onPress={() => setMode(item.key)} style={[styles.option, { backgroundColor: mode === item.key ? colors.primary : colors.surfaceAlt, borderColor: mode === item.key ? colors.primary : colors.border }]}><Ionicons name={item.icon} size={19} color={mode === item.key ? "#FFF" : colors.text} /><Text style={[styles.optionText, { color: mode === item.key ? "#FFF" : colors.text }]}>{item.title}</Text></Pressable>)}</View><Text style={[styles.label, { color: colors.text }]}>الثيم اللوني</Text><View style={styles.paletteGrid}>{palettes.map((item) => <Pressable key={item.id} accessibilityRole="button" onPress={() => setPalette(item.id)} style={[styles.palette, { backgroundColor: colors.surfaceAlt, borderColor: palette === item.id ? colors.primary : colors.border }]}><View style={styles.swatches}><View style={[styles.swatch, { backgroundColor: item.colors[0] }]} /><View style={[styles.swatch, { backgroundColor: item.colors[1] }]} /></View><Text style={[styles.paletteText, { color: colors.text }]}>{paletteLabels[item.id]}</Text>{palette === item.id && <Ionicons name="checkmark-circle" size={15} color={colors.primary} />}</Pressable>)}</View><Text style={[styles.label, { color: colors.text }]}>حجم الخط</Text><View style={styles.row}>{fontScales.map((item) => <Pressable key={item.value} accessibilityRole="button" onPress={() => setFontScale(item.value)} style={[styles.option, { backgroundColor: fontScale === item.value ? colors.primary : colors.surfaceAlt, borderColor: fontScale === item.value ? colors.primary : colors.border }]}><Ionicons name={item.icon} size={18} color={fontScale === item.value ? "#FFF" : colors.text} /><Text style={[styles.optionText, { color: fontScale === item.value ? "#FFF" : colors.text }]}>{item.label}</Text></Pressable>)}</View><View style={[styles.status, { backgroundColor: colors.surfaceAlt }]}><Ionicons name={dark ? "moon-outline" : "sunny-outline"} size={16} color={colors.primary} /><Text style={[styles.statusText, { color: colors.textSoft }]}>مظهر هذا الجهاز: {paletteLabels[palette]} · {dark ? "ليلي" : "فاتح"} · حجم {fontScale === 1 ? "قياسي" : `${Math.round(fontScale * 100)}%`}</Text></View></Card></View>;
}

const styles = StyleSheet.create({ wrap: { marginTop: 5, marginBottom: 18 }, card: { gap: 13 }, label: { fontSize: 12, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, row: { flexDirection: "row-reverse", gap: 7, flexWrap: "wrap" }, option: { minHeight: 45, flexGrow: 1, flexBasis: "30%", paddingHorizontal: 10, borderWidth: 1, borderRadius: 13, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 6 }, optionText: { fontSize: 10, fontWeight: "800" }, paletteGrid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, palette: { flexBasis: "47%", flexGrow: 1, minHeight: 60, borderWidth: 1, borderRadius: 14, padding: 9, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, swatches: { flexDirection: "row-reverse" }, swatch: { width: 21, height: 34, borderRadius: 8, marginLeft: -5 }, paletteText: { flex: 1, textAlign: "right", fontSize: 10, fontWeight: "800" }, status: { minHeight: 36, borderRadius: 11, paddingHorizontal: 10, flexDirection: "row-reverse", alignItems: "center", gap: 6 }, statusText: { flex: 1, fontSize: 9, textAlign: "right", writingDirection: "rtl" } });
