import React, { useState } from "react";
import { View } from "react-native";
import { useQuery } from "@tanstack/react-query";
import { ScaledText as Text } from "@/src/components/ScaledText";
import { AppButton, Card, Field } from "@/src/components/ui";
import { SearchPicker } from "@/src/components/SearchPicker";
import { api, jsonBody } from "@/src/lib/api";
import { MerasAlert } from "@/src/lib/interaction-events";
import { FAQ_CATEGORIES, validateInformation, type InformationContent } from "@/src/lib/information-contract";
import { useTheme } from "@/src/providers/ThemeProvider";
export function PublicContentEditor() {
  const { colors } = useTheme();
  const query = useQuery({ queryKey: ["admin-public-information"], queryFn: ({signal}) => api<{content: InformationContent; version:string|null}>("/api/admin/content",{signal}) });
  const [draft,setDraft] = useState<InformationContent|null>(null); const [version,setVersion] = useState<string|null>(null);
  const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [active,setActive] = useState<string|null>(null); const [search,setSearch]=useState("");
  const text = { color:colors.text,fontSize:16,lineHeight:28,textAlign:"right" as const };
  function publish() {
    if (!draft || busy) return;
    try { validateInformation(draft); } catch(e) {setError(e instanceof Error?e.message:"تحقق من النصوص");return;}
    MerasAlert.alert("نشر محتوى الصفحات؟","سيظهر للزوار في الويب والتطبيق. تحقّق من دقة النصوص؛ تحفظ نسخة في سجل التدقيق.",[{text:"إلغاء",style:"cancel"},{text:"نشر",onPress:()=>{void(async()=>{setBusy(true);setError("");try{const result=await api<{version:string}>("/api/admin/content",{method:"POST",body:jsonBody({content:draft,version})});setVersion(result.version);setDraft(null);setActive(null);await query.refetch();}catch(e){setError(e instanceof Error?e.message:"تعذر النشر");}finally{setBusy(false);}})();}}]);
  }
  const updateAbout=(key:"title"|"intro"|"mission"|"vision",value:string)=>{if(draft)setDraft({...draft,about:{...draft.about,[key]:value}});};
  return <View style={{gap:16}}><Card style={{gap:12}}><Text style={{...text,fontSize:23,fontWeight:"800"}}>الصفحات والمحتوى العام</Text><Text style={{...text,color:colors.textSoft}}>عن مراس، لماذا مراس، والأسئلة الشائعة من مصدر مشترك. لا تضف اعتمادًا أو ضمانًا بلا دليل.</Text>{!draft&&query.data&&<AppButton title="تحرير النسخة المنشورة" onPress={()=>{setDraft(JSON.parse(JSON.stringify(query.data.content)));setVersion(query.data.version);}}/>}{!query.data&&<AppButton title="إعادة التحميل" variant="soft" loading={query.isFetching} onPress={()=>void query.refetch()}/>}</Card>
    {(error||query.error)&&<Text accessibilityRole="alert" selectable style={{...text,color:colors.danger}}>{error||(query.error as Error).message}</Text>}
    {draft&&<><Card style={{gap:14}}><Text style={{...text,fontSize:20,fontWeight:"800"}}>عن مراس</Text>{([['title','العنوان',100],['intro','المقدمة',600],['mission','الرسالة',1600],['vision','الرؤية',1600]] as const).map(([key,label,max])=><Field key={key} label={label} value={draft.about[key]} multiline editable={!busy} maxLength={max} onChangeText={value=>updateAbout(key,value)}/>)}<Text style={{...text,fontWeight:"800"}}>بطاقات لماذا مراس</Text>{draft.about.why.map((item,index)=><View key={index} style={{gap:10,borderTopWidth:1,borderColor:colors.border,paddingTop:12}}><Field label={`عنوان البطاقة ${index+1}`} value={item.title} maxLength={100} editable={!busy} onChangeText={value=>setDraft({...draft,about:{...draft.about,why:draft.about.why.map((row,i)=>i===index?{...row,title:value}:row)}})}/><Field label="الشرح" value={item.body} maxLength={1200} multiline editable={!busy} onChangeText={value=>setDraft({...draft,about:{...draft.about,why:draft.about.why.map((row,i)=>i===index?{...row,body:value}:row)}})}/></View>)}</Card>
    <Card style={{gap:12}}><Text style={{...text,fontSize:21,fontWeight:"800"}}>الأسئلة الشائعة · {draft.faq.length}</Text><Field label="ابحث لتعديل سؤال" value={search} onChangeText={setSearch}/><AppButton title="إضافة سؤال" variant="soft" disabled={busy||draft.faq.length>=80} onPress={()=>{const id=`faq-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;setDraft({...draft,faq:[...draft.faq,{id,category:"start",question:"سؤال جديد — عدّل النص",answer:"اكتب الإجابة الدقيقة التي يحتاج الطالب معرفتها هنا."}]});setActive(id);setSearch("");}}/></Card>
    {draft.faq.map((item,index)=>({item,index})).filter(({item})=>`${item.question} ${item.answer}`.includes(search)).map(({item,index})=><Card key={item.id} style={{gap:12}}><AppButton title={`${index+1}. ${item.question}`} variant="soft" onPress={()=>setActive(active===item.id?null:item.id)}/>{active===item.id&&<><SearchPicker placeholder="اختر التصنيف" label="التصنيف" value={item.category} items={Object.entries(FAQ_CATEGORIES).map(([key,label])=>({key,label}))} onSelect={value=>setDraft({...draft,faq:draft.faq.map(row=>row.id===item.id?{...row,category:value.key as typeof item.category}:row)})}/><Field label="السؤال" value={item.question} maxLength={250} editable={!busy} multiline onChangeText={value=>setDraft({...draft,faq:draft.faq.map(row=>row.id===item.id?{...row,question:value}:row)})}/><Field label="الإجابة" value={item.answer} maxLength={2400} editable={!busy} multiline onChangeText={value=>setDraft({...draft,faq:draft.faq.map(row=>row.id===item.id?{...row,answer:value}:row)})}/><AppButton title="نقل للأعلى" variant="soft" disabled={busy||index===0} onPress={()=>{const faq=[...draft.faq];if(index>0&&faq[index]&&faq[index-1]) [faq[index-1],faq[index]]=[faq[index]!,faq[index-1]!];setDraft({...draft,faq});}}/><AppButton title="نقل للأسفل" variant="soft" disabled={busy||index===draft.faq.length-1} onPress={()=>{const faq=[...draft.faq];if(faq[index]&&faq[index+1]) [faq[index+1],faq[index]]=[faq[index]!,faq[index+1]!];setDraft({...draft,faq});}}/><AppButton title="حذف السؤال" variant="danger" disabled={busy||draft.faq.length<=1} onPress={()=>MerasAlert.alert("حذف السؤال من المسودة؟",item.question,[{text:"إلغاء",style:"cancel"},{text:"حذف",style:"destructive",onPress:()=>setDraft({...draft,faq:draft.faq.filter(row=>row.id!==item.id)})}])}/></>}</Card>)}
    <Card style={{gap:12}}><AppButton title="نشر التغييرات" loading={busy} onPress={publish}/><AppButton title="إلغاء المسودة" variant="soft" disabled={busy} onPress={()=>MerasAlert.alert("تجاهل التعديلات؟","ستُهمل كل التعديلات غير المنشورة.",[{text:"متابعة التحرير",style:"cancel"},{text:"تجاهل",style:"destructive",onPress:()=>{setDraft(null);setActive(null);}}])}/></Card></>}
  </View>;
}
