LocalSocket /run/clamav/clamd.ctl
LocalSocketMode 660
FixStaleSocket yes
User clamav
DatabaseDirectory /var/lib/clamav
LogFile /var/log/clamav/clamd.log
LogTime yes
LogRotate yes
LogFileMaxSize 5M
MaxThreads 2
MaxQueue 8
StreamMaxLength 100M
MaxFileSize 100M
MaxScanSize 200M
MaxRecursion 16
MaxFiles 10000
AlertExceedsMax yes
AlertEncrypted yes
HeuristicAlerts yes
ReadTimeout 40
CommandReadTimeout 10
SendBufTimeout 500
SelfCheck 1800
