DatabaseDirectory /var/lib/clamav
DatabaseOwner clamav
DatabaseMirror database.clamav.net
Checks 24
NotifyClamd /etc/clamav/clamd.conf
UpdateLogFile /var/log/clamav/freshclam.log
LogTime yes
LogRotate yes
LogFileMaxSize 5M
ConnectTimeout 20
ReceiveTimeout 60
