"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {AdminCenterNav} from "@/components/admin-center-nav";
import styles from "./admin-store-purchases.module.css";
type Product={product_key:string;title:string;kind:string;status:string;duration_days:number|null;ios_product_id:string|null;android_product_id:string|null;updated_at:string};
type Data={productPagination:{page:number;pageSize:number;total:number};configured:boolean;products:Product[];courses:{slug:string;title:string}[];bundles:{slug:string;title:string}[];events:{event_type:string;status:string;count:number}[];transactions:{id:string;user_id:number;title:string;email:string;store:string;status:string;purchased_at:string;transaction_id:string}[];pagination:{page:number;pageSize:number;total:number}};
export function AdminStorePurchases(){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[page,setPage]=useState(1),[productPage,setProductPage]=useState(1),[search,setSearch]=useState(""),[kind,setKind]=useState("course");
 const load=useCallback(async()=>{const r=await fetch("/api/admin/purchases?page="+page+"&productPage="+productPage+"&search="+encodeURIComponent(search),{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.error);setData(p);},[page,productPage,search]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{if(active)void load().catch(e=>setError(e.message));},250);return()=>{active=false;clearTimeout(timer);};},[load]);
 async function act(payload:Record<string,unknown>){setBusy(true);setError("");try{const r=await fetch("/api/admin/purchases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok)throw new Error(p.error);await load();}catch(e){setError(e instanceof Error?e.message:"تعذر تنفيذ الإجراء");}finally{setBusy(false);}}
 return <main className={styles.page} dir="rtl"><h1>مشتريات التطبيقات</h1><AdminCenterNav/><p>ربط منتجات App Store وGoogle Play بالمواد والباقات وأدوات مراس. يحتفظ كل شراء بحقوقه وسجله المستقل.</p>{!data?.configured?<p className={styles.notice}>الربط الخارجي يحتاج إعداد RevenueCat والمتاجر. المنتجات تبقى مسودات حتى تفعيلها؛ اختبار الشراء الفعلي يتم بحسابات الاختبار.</p>:null}{error?<p role="alert">{error} <Link href="/admin/security">التحقق الإداري</Link></p>:null}
 <section><h2>إضافة منتج</h2><form className={styles.form} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:"create",productKey:f.get("productKey"),kind,targetSlug:f.get("targetSlug"),iosProductId:f.get("iosProductId"),androidProductId:f.get("androidProductId"),durationDays:kind==="ai"?30:f.get("durationDays")===""?null:Number(f.get("durationDays"))});}}>
 <label>معرف داخلي<input name="productKey" required placeholder="course-accounting-v1"/></label><label>نوع المنتج<select value={kind} onChange={e=>setKind(e.target.value)}><option value="course">مادة</option><option value="bundle">باقة</option><option value="ai">أدوات مراس</option></select></label>
 {kind!=="ai"?<label>المحتوى<select key={kind} name="targetSlug" required><option value="">اختر المحتوى</option>{(kind==="course"?data?.courses:data?.bundles)?.map(c=><option key={c.slug} value={c.slug}>{c.title}</option>)}</select></label>:null}
 <label>معرف App Store<input name="iosProductId" dir="ltr"/></label><label>معرف Google Play<input name="androidProductId" dir="ltr"/></label><label>مدة الوصول بالأيام<input name="durationDays" type="number" min={1} max={3650} disabled={kind==="ai"} placeholder={kind==="ai"?"٣٠ يومًا":"فارغ = دائم"}/></label><button disabled={busy}>حفظ مسودة</button></form><p>معرفات المنتجات ومحتوياتها ومددها ثابتة لحماية المشتريات. لتغييرها أنشئ إصدارًا بمعرف متجر جديد. التجديد يدوي، وسعر الشراء النهائي يأتي من المتجر.</p></section>
 <section><h2>الكتالوج ({data?.productPagination.total||0})</h2>{data?.products.map(p=><article className={styles.card} key={p.product_key}><strong>{p.title}</strong><code>{p.product_key}</code><span>{p.duration_days===null?"دائم":p.duration_days+" يومًا"}</span><span>{p.status==="active"?"نشط":p.status==="archived"?"مؤرشف":"مسودة"}</span><button disabled={busy} onClick={()=>void act({action:"status",productKey:p.product_key,status:p.status==="active"?"archived":"active",expectedUpdatedAt:p.updated_at})}>{p.status==="active"?"أرشفة":"تفعيل"}</button></article>)}<div className={styles.pager}><button disabled={productPage===1} onClick={()=>setProductPage(productPage-1)}>السابق</button><span>صفحة {productPage}</span><button disabled={!data||productPage*30>=data.productPagination.total} onClick={()=>setProductPage(productPage+1)}>التالي</button></div></section>
 <section><h2>المعاملات ({data?.pagination.total||0})</h2><input aria-label="البحث بالبريد أو المعاملة" placeholder="البريد أو المادة أو رقم معاملة المتجر" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);setProductPage(1);}}/>{data?.transactions.map(t=><article className={styles.card} key={t.id}><strong>{t.title}</strong><Link href={"/admin/students/"+encodeURIComponent(t.email)}>{t.email}</Link><span>{t.store==="app_store"?"App Store":"Google Play"}</span><span>{t.status==="owned"?"موثق":"مسترد"}</span><time>{new Date(t.purchased_at).toLocaleString("ar-SA")}</time><code>{t.transaction_id}</code><button disabled={busy} onClick={()=>void act({action:"sync",userId:t.user_id})}>مزامنة مشتريات الطالب</button></article>)}<div className={styles.pager}><button disabled={page===1||busy} onClick={()=>setPage(page-1)}>السابق</button><span>صفحة {page}</span><button disabled={!data||page*30>=data.pagination.total||busy} onClick={()=>setPage(page+1)}>التالي</button></div></section>
 <section><h2>أحداث المزود</h2>{data?.events.map(e=><p key={e.event_type+e.status}>{e.event_type} · {e.status==="processed"?"عولج":"بانتظار إعادة المحاولة"} · {e.count}</p>)}<p>الاسترداد المالي يتم في المتجر، ثم تُعكس المعاملة المعنية عند وصول الحدث أو المزامنة. إيصال المتجر هو مرجع المبلغ المدفوع.</p></section></main>;
}