"use client";
import { useAdminAccess } from "@/components/admin-access";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import { ArrowRight, RefreshCw, Search, ShieldCheck, UsersRound } from "lucide-react";
import { confirmAction } from "@/lib/interaction-events";
import { DEVICE_ACTIONS, DEVICE_ACTION_LABELS, DEVICE_ACTION_DESCRIPTIONS, devicePolicyLabel, type DeviceAction } from "@/lib/device-access-policy";
import { instructorAdminJson as json, InstructorAdminError, instructorDate, applicationStatuses, InstructorAdminRequestError } from "./admin-instructors-shared";
import { AdminInstructorDocument } from "./admin-instructor-document";
import { AdminInstructorContracts } from "./admin-instructor-contracts";
import { AdminInstructorAssignments } from "./admin-instructor-assignments";
import styles from "./admin-instructors.module.css";
type Row = { id:number;fullName:string;email:string;status:string;accountStatus:string;specialty:string;country:string;submittedAt:string|null };
type Device = { id:number;deviceLabel:string;platform:string;lastSeenAt:string|null;revokedAt:string|null;returnPolicy:string;blockedUntil:string|null;policyVersion:number };
type Detail = { user:{id:number;fullName:string;email:string;phone:string;status:string;emailVerified:boolean}; profile:{status:string;revision:number;country:string;gender:string;qualification:string;specialty:string;address:string;bio:string;teachingSubjects:string;compensationModel:string;reviewNotes:string;submittedAt:string|null;bank:{accountHolder:string;bankName:string;iban:string}|null};documents:{id:number;kind:string;originalName:string;scanStatus:string;contentType:string;sizeBytes:number;expiresAt:string|null}[];devices:Device[];sessions:{id:number;deviceLabel:string;platform:string;lastSeenAt:string|null;expiresAt:string}[];identityCollection:{enabled:boolean;basis:string;retentionDays:number} };
const documentNames:Record<string,string> = {identity_front:"الهوية — الأمام",identity_back:"الهوية — الخلف",passport:"جواز السفر",selfie:"الصورة الملتقطة",cv:"السيرة الذاتية",certificate:"شهادة"};
const qualifications:Record<string,string> = {student:"طالب",diploma:"دبلوم",bachelor:"بكالوريوس",master:"ماجستير",doctorate:"دكتوراه",professional:"تأهيل مهني",other:"أخرى"};
export function AdminInstructors() {
 const { can } = useAdminAccess(), canManage = can(["instructors.manage"]);
 const [rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[query,setQuery]=useState(""),[status,setStatus]=useState("");
 const [detail,setDetail]=useState<Detail|null>(null),[tab,setTab]=useState("application"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [reason,setReason]=useState(""),[device,setDevice]=useState<Device|null>(null),[deviceAction,setDeviceAction]=useState<DeviceAction>("end_sessions"),[duration,setDuration]=useState(24);
 const [loadedAt,setLoadedAt]=useState(0);
 const alive=useRef(true),read=useRef<AbortController|null>(null),locked=useRef(false);
 const list=useCallback(async (nextPage=1,q="",filter="")=>{read.current?.abort();const controller=new AbortController();read.current=controller;setLoading(true);try{const data=await json<{instructors:Row[];total:number;page:number}>(`/api/admin/instructors?page=${nextPage}&q=${encodeURIComponent(q)}&status=${encodeURIComponent(filter)}`,{signal:controller.signal});if(alive.current&&!controller.signal.aborted){setRows(data.instructors);setTotal(data.total);setPage(data.page);setError("");}}catch(e){if(alive.current&&!controller.signal.aborted)setError(e instanceof Error?e.message:"تعذر تحميل الشارحين");}finally{if(alive.current&&!controller.signal.aborted)setLoading(false);}},[]);
 useEffect(()=>{alive.current=true;const timer=setTimeout(()=>void list(),0);return()=>{clearTimeout(timer);alive.current=false;read.current?.abort();};},[list]);
 // This helper runs after an explicit read/event, never during render; snapshot policy time with the response.
 // eslint-disable-next-line react-hooks/purity
 async function loadDetail(id:number) { read.current?.abort();const controller=new AbortController();read.current=controller;setLoading(true);try{const data=await json<Detail>(`/api/admin/instructors?userId=${id}`,{signal:controller.signal});if(alive.current&&!controller.signal.aborted){setDetail(data);setLoadedAt(Date.now());setError("");}}catch(e){if(alive.current&&!controller.signal.aborted)setError(e instanceof Error?e.message:"تعذر فتح الملف");}finally{if(alive.current&&!controller.signal.aborted)setLoading(false);} }
 async function action(name:string,extra:Record<string,unknown>={}) { if(!canManage||!detail||detail.user.status==="deleted"||locked.current)return;if(reason.trim().length<5){setError("اكتب سببًا واضحًا للإجراء من خمسة أحرف على الأقل.");return;}if(!await confirmAction({title:"تأكيد إجراء ملف الشارح",message:`سيُنفذ الإجراء على ${detail.user.fullName} ويُحفظ سببه في سجل الإدارة.`,confirmLabel:"تأكيد الإجراء",destructive:["reject","suspend","device"].includes(name)}))return;locked.current=true;setBusy(true);setError("");setNotice("");try{await json("/api/admin/instructors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:name,userId:detail.user.id,expectedRevision:detail.profile.revision,reason,...extra})});setReason("");setDevice(null);setNotice("حُفظ الإجراء وأُرسل تحديث لصاحب الحساب.");await loadDetail(detail.user.id);}catch(e){if(e instanceof InstructorAdminRequestError&&e.status===409){await loadDetail(detail.user.id);setDevice(null);}setError(e instanceof Error?e.message:"تعذر تنفيذ الإجراء");}finally{locked.current=false;setBusy(false);} }
 function search(e:FormEvent){e.preventDefault();void list(1,query,status);}
 return <main className={styles.page} dir="rtl"><header className={styles.hero}><span className={styles.icon}><UsersRound size={28}/></span><div><p>{canManage?"عرض وتعديل فريق الشارحين":"عرض فريق الشارحين فقط"}</p><h1>فريق مراس — الشارحون</h1><p>طلبات التوظيف، المستندات، العقود وتكليفات الشرح في مكان واحد.</p></div><Link className="button button-ghost" href="/join-instructors">صفحة الانضمام</Link></header>
 <InstructorAdminError message={error}/>{notice&&<p role="status" className={styles.success}>{notice}</p>}
 {!detail?<section className={styles.panel}><form className={styles.filters} onSubmit={search}><label>البحث بالاسم أو البريد<input value={query} maxLength={120} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن شارح…"/></label><label>حالة الطلب<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">جميع الحالات</option>{Object.entries(applicationStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="button button-primary" disabled={loading}><Search size={17}/>بحث</button></form><p>{total.toLocaleString("ar-SA")} ملف</p>{loading&&<p role="status">جارٍ تحميل الملفات…</p>}<div className={styles.tableScroll}><table><thead><tr><th>الشارح</th><th>التخصص</th><th>حالة الطلب</th><th>آخر تقديم</th><th>المراجعة</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.fullName}</strong><small dir="ltr">{row.email}</small></td><td>{row.specialty}<small>{row.country}</small></td><td><span className={styles.badge}>{applicationStatuses[row.status]||row.status}</span></td><td>{instructorDate(row.submittedAt)}</td><td><button type="button" className="button button-ghost" disabled={loading} onClick={()=>{setTab("application");setReason("");setNotice("");void loadDetail(row.id);}}>فتح الملف</button></td></tr>)}</tbody></table></div>{!loading&&!rows.length&&<p className={styles.empty}>لا توجد ملفات مطابقة.</p>}<div className={styles.actions}><button className="button button-ghost" disabled={loading||page<=1} onClick={()=>void list(page-1,query,status)}>السابق</button><span>صفحة {page}</span><button className="button button-ghost" disabled={loading||page*30>=total} onClick={()=>void list(page+1,query,status)}>التالي</button></div></section>:<>
 <section className={styles.panel}><div className={styles.heading}><div><h2>{detail.user.fullName}</h2><p dir="ltr">{detail.user.email}</p><span className={styles.badge}>{applicationStatuses[detail.profile.status]}</span></div><div className={styles.actions}><button className="button button-ghost" disabled={busy||loading} onClick={()=>{setDetail(null);setDevice(null);setNotice("");void list(page,query,status);}}><ArrowRight size={17}/>القائمة</button><button className="button button-ghost" disabled={busy||loading} onClick={()=>void loadDetail(detail.user.id)}><RefreshCw size={17}/>تحديث الملف</button></div></div><nav className={styles.tabs} aria-label="أقسام ملف الشارح">{[["application","الطلب والمستندات"],["contracts","عقود العمل"],["assignments","تكليفات المواد"],["security","الأجهزة والأمان"]].map(([key,label])=><button key={key} className={tab===key?styles.active:""} aria-current={tab===key?"page":undefined} disabled={busy} onClick={()=>setTab(key)}>{label}</button>)}</nav></section>
 {tab==="application"&&<section className={styles.panel}><h2>تفاصيل التقديم</h2><dl className={styles.facts}>{[["الاسم الكامل",detail.user.fullName],["البريد",detail.user.email],["التحقق من البريد",detail.user.emailVerified?"تم التحقق":"لم يُتحقق"],["الهاتف",detail.user.phone],["الدولة",detail.profile.country],["الجنس",detail.profile.gender==="male"?"ذكر":"أنثى"],["المؤهل",qualifications[detail.profile.qualification]||detail.profile.qualification],["التخصص",detail.profile.specialty],["نظام العمل",detail.profile.compensationModel==="hourly"?"ساعات شرح معتمدة":"مادة مكتملة"],["العنوان",detail.profile.address]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"—"}</dd></div>)}</dl><h3>الخبرة والقدرة على التدريس</h3><p className={styles.multiline}>{detail.profile.bio||"لم تُضف تفاصيل بعد."}</p><h3>المواد التي يستطيع شرحها</h3><p className={styles.multiline}>{detail.profile.teachingSubjects||"—"}</p>
 <h3>المستندات الخاصة</h3><p className={styles.hint}>فتح المستند يتطلب تحققًا إداريًا حديثًا، ويسجل الخادم عملية الوصول. تنتهي إتاحته بانتهاء مدة الاحتفاظ.</p><div className={styles.cards}>{detail.documents.map(doc=><article key={doc.id} className={styles.card}><strong>{documentNames[doc.kind]||doc.kind}</strong><span>{doc.originalName}</span><small>{(doc.sizeBytes/1024/1024).toFixed(2)} ميجابايت · {doc.scanStatus==="clean"?"اجتاز الفحص":doc.scanStatus==="pending"?"قيد الفحص":"محجور"}</small>{doc.expiresAt&&<small>الحفظ حتى {instructorDate(doc.expiresAt)}</small>}{doc.scanStatus==="clean"?<AdminInstructorDocument document={doc}/>:<p>غير متاح للفتح قبل اجتياز الفحص.</p>}</article>)}</div>{!detail.documents.length&&<p className={styles.empty}>لم تُرفع مستندات.</p>}
 <h3>الحساب البنكي</h3>{detail.profile.bank?<dl className={styles.facts}><div><dt>اسم صاحب الحساب</dt><dd>{detail.profile.bank.accountHolder}</dd></div><div><dt>البنك</dt><dd>{detail.profile.bank.bankName}</dd></div><div><dt>IBAN</dt><dd dir="ltr">{detail.profile.bank.iban}</dd></div></dl>:<p>لم تُسجل بيانات بنكية.</p>}
 <h3>قرار المراجعة</h3>{detail.user.status==="deleted"&&<p className={styles.hint}>هذا الحساب محذوف. تبقى العقود والسجلات التاريخية متاحة دون إعادة تفعيل الحساب.</p>}{detail.profile.reviewNotes&&<p className={styles.multiline}>آخر ملاحظة: {detail.profile.reviewNotes}</p>}{canManage&&<><label className={styles.field}>سبب القرار / ملاحظات الاستكمال<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1500} rows={3} disabled={busy}/></label><div className={styles.actions}>{detail.profile.status==="submitted"&&<><button className="button button-primary" disabled={busy||loading||detail.user.status==="deleted"} onClick={()=>void action("approve")}>اعتماد الطلب</button><button className="button button-ghost" disabled={busy||loading||detail.user.status==="deleted"} onClick={()=>void action("reject")}>رفض الطلب</button></>}{["submitted","rejected"].includes(detail.profile.status)&&<button className="button button-ghost" disabled={busy||loading||detail.user.status==="deleted"} onClick={()=>void action("request_changes")}>طلب استكمال</button>}{detail.profile.status==="suspended"?<button className="button button-primary" disabled={busy||loading||detail.user.status==="deleted"} onClick={()=>void action("resume")}>إعادة تفعيل الحساب وطلب المراجعة</button>:<button className="button button-ghost" disabled={busy||loading||detail.user.status==="deleted"} onClick={()=>void action("suspend")}>إيقاف الحساب والجلسات</button>}</div></>}</section>}
 {tab==="contracts"&&<AdminInstructorContracts key={detail.user.id} userId={detail.user.id} approved={detail.profile.status==="approved"&&detail.user.status!=="deleted"}/>}
 {tab==="assignments"&&<AdminInstructorAssignments key={detail.user.id} userId={detail.user.id} approved={detail.profile.status==="approved"&&detail.user.status!=="deleted"}/>}
 {tab==="security"&&<section className={styles.panel}><div className={styles.heading}><h2><ShieldCheck size={22}/>الأجهزة والجلسات</h2><span className={styles.badge}>الحد: جهازان</span></div><div className={styles.cards}>{detail.devices.map(item=><article className={styles.card} key={item.id}><strong>{item.deviceLabel}</strong><span>{item.platform} · {devicePolicyLabel(item,loadedAt)}</span><small>آخر ظهور: {instructorDate(item.lastSeenAt)}</small>{canManage&&<button className="button button-ghost" disabled={busy||detail.user.status==="deleted"} onClick={()=>{setDevice(item);setReason("");}}>إدارة الجهاز</button>}</article>)}</div>{!detail.devices.length&&<p>لا توجد أجهزة مسجلة.</p>}{canManage&&device&&<form className={styles.editor} onSubmit={e=>{e.preventDefault();void action("device",{deviceId:device.id,expectedDeviceRevision:device.policyVersion,deviceAction,durationHours:duration});}}><h3>إدارة: {device.deviceLabel}</h3><div className={styles.fields}><label>الإجراء<select value={deviceAction} disabled={busy} onChange={e=>setDeviceAction(e.target.value as DeviceAction)}>{DEVICE_ACTIONS.map(value=><option key={value} value={value}>{DEVICE_ACTION_LABELS[value]}</option>)}</select></label>{deviceAction==="block_until"&&<label>مدة الحظر بالساعات<input type="number" min={1} max={2160} required value={duration} disabled={busy} onChange={e=>setDuration(Number(e.target.value))}/></label>}<label className={styles.full}>السبب<textarea required minLength={5} maxLength={600} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label></div><p>{DEVICE_ACTION_DESCRIPTIONS[deviceAction]}</p><div className={styles.actions}><button className="button button-primary" disabled={busy||loading||detail.user.status==="deleted"}>تطبيق الإجراء</button><button className="button button-ghost" type="button" disabled={busy} onClick={()=>setDevice(null)}>إلغاء</button></div></form>}<h3>الجلسات النشطة المسجلة</h3>{detail.sessions.map(session=><p key={session.id}>{session.deviceLabel||session.platform} · آخر نشاط {instructorDate(session.lastSeenAt)} · تنتهي {instructorDate(session.expiresAt)}</p>)}</section>}
 </>}
 </main>;
}
