"use client";
import {useRef,useState} from "react";
import {AdminMfaNotice,isAdminStepUpResponse,ADMIN_STEP_UP_MESSAGE} from "@/components/admin-mfa-notice";
import styles from "./student-controls.module.css";
type Key={id:number;label:string;updatedAt:string;decryptable?:boolean;lastSuccessAt:string|null;status:string};
export function AdminAiDiagnostics({keys,onChanged}:{keys:Key[];onChanged:()=>void|Promise<void>}) {
 const [service,setService]=useState("chat");const [keyId,setKeyId]=useState("");const [replacement,setReplacement]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [stepUp,setStepUp]=useState(false);const input=useRef<HTMLInputElement>(null);
 async function run(body:Record<string,unknown>){setBusy(true);setMessage("");setStepUp(false);try{const res=await fetch("/api/admin/ai",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(130000)});const data=await res.json();if(isAdminStepUpResponse(res)){setStepUp(true);throw new Error(ADMIN_STEP_UP_MESSAGE);}if(!res.ok)throw new Error(`${data.error||"تعذر الفحص"}${data.code?` (${data.code})`:""}`);if(data.diagnostic){const d=data.diagnostic;setMessage(`${data.message} النموذج: ${d.model}، المفتاح: ${d.keyId?`#${d.keyId}`:"بيئة الخادم"}، رموز الإدخال: ${d.inputTokens}، رموز الإخراج: ${d.outputTokens}${d.structuredOutputVerified?". بُنية الاختبار JSON صحيحة.":"."}`);}else{setMessage(data.message||"تم الاستبدال");setReplacement("");if(input.current)input.current.value="";}await onChanged();}catch(e){setMessage(e instanceof Error?e.message:"تعذر تنفيذ الطلب");}finally{setBusy(false);}}
 return <section className={styles.root} aria-labelledby="ai-runtime-title"><div className={styles.form} style={{paddingTop:16}}><h2 id="ai-runtime-title">فحص التشغيل الفعلي واستبدال المفاتيح</h2><p className={styles.warning}>حفظ المفتاح لا يعني نجاحه. هذا الفحص يولّد نصًا تجريبيًا عبر نفس إعدادات الخدمة والمفاتيح التي يستخدمها الطلاب، وقد يستهلك حصة لدى المزود. لا يختبر رفع الملفات أو الدفع.</p><div className={styles.grid}><label htmlFor="ai-runtime-service">الخدمة المحفوظة<select id="ai-runtime-service" value={service} onChange={e=>setService(e.target.value)} disabled={busy}><option value="chat">المحادثة</option><option value="summary">التلخيص</option><option value="translation">الترجمة</option><option value="quiz">الاختبارات وبُنية JSON</option></select></label><button type="button" disabled={busy} onClick={()=>void run({action:"testRuntime",service})}>{busy?"جارٍ تنفيذ الطلب…":"اختبار الخدمة فعليًا"}</button></div>
 <details><summary>استبدال قيمة مفتاح محفوظ</summary><p>يحافظ الاستبدال على اسم المفتاح وأولويته وحالة تعطيله، ويمسح نتيجة الفحص القديمة. مفتاح التشفير الثابت مطلوب على الخادم.</p><label htmlFor="ai-replace-id">المفتاح<select id="ai-replace-id" value={keyId} onChange={e=>setKeyId(e.target.value)} disabled={busy}><option value="">اختر المفتاح</option>{keys.map(k=><option key={k.id} value={k.id}>{k.label} · {k.decryptable===false?"تعذر فك التشفير":k.lastSuccessAt?"اختُبر سابقًا":"لم يُختبر التوليد"}</option>)}</select></label><label htmlFor="ai-replace-value">القيمة الجديدة<input ref={input} id="ai-replace-value" type="password" autoComplete="new-password" value={replacement} onChange={e=>setReplacement(e.target.value)} disabled={busy} dir="ltr" spellCheck={false}/></label><button type="button" disabled={busy||!keyId||replacement.trim().length<20} onClick={()=>{const key=keys.find(k=>k.id===Number(keyId));if(key)void run({action:"replaceKey",id:key.id,apiKey:replacement,expectedUpdatedAt:key.updatedAt});}}>تأكيد استبدال المفتاح مشفرًا</button></details>
 {stepUp&&<AdminMfaNotice/>}{message&&<p role="status" aria-live="polite" className={styles.message}>{message}</p>}</div></section>;
}
