"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import styles from "./admin-operations-center.module.css";

type FunnelRow = { event:string;label:string;actors:number;conversionFromPrevious:number|null };
type AnalyticsData = { range:{days:number};totals:Record<string,number>;funnel:FunnelRow[];topCourses:Array<{courseSlug:string|null;events:number;actors:number}>;daily:Array<{day:string;events:number;actors:number}>;cohorts:Array<{cohort:string;enrolled:number;activated:number;retained7:number;retained30:number;activationRate:number;retention7Rate:number;retention30Rate:number}> };
type SupportData = { summary:{total:number;open:number;responseBreached:number;resolutionBreached:number;averageFirstResponseMinutes:number|null;resolved:number};queues:Array<{category:string;count:number;overdue:number}>;tickets:Array<{id:number;ticketNumber:string;title:string;priority:string;status:string;assignedTo:string|null;responseBreached:boolean;resolutionBreached:boolean;firstResponseDueAt:string;resolutionDueAt:string}> };
type ComplianceItem = { key:string;area:string;title:string;description:string;evidenceHint:string;status:string;owner:string;evidence:string;reviewDate:string;notes:string };
type ComplianceData = { disclaimer:string;progress:number;items:ComplianceItem[] };
type OperationsData = { waitlist:Record<string,number>;bundles:Record<string,number>;queues:{filesPendingScan:number;abandonedCheckout:number;expiringAccess:number;pushPending:number;refundPending:number;settlementUnmatched:number};generatedAt:string };
type Tab = "analytics"|"support"|"automation"|"compliance";

const categoryLabel:Record<string,string>={technical:"تقني",payment:"الدفع",course:"المحتوى",account:"الحساب",other:"أخرى"};
const statusLabel:Record<string,string>={not_started:"لم يبدأ",in_progress:"قيد العمل",ready:"جاهز للمراجعة",verified:"موثّق"};

export function AdminOperationsCenter({adminName}:{adminName:string}) {
  const [tab,setTab]=useState<Tab>("analytics");
  const [days,setDays]=useState(30);
  const [analytics,setAnalytics]=useState<AnalyticsData|null>(null);
  const [support,setSupport]=useState<SupportData|null>(null);
  const [compliance,setCompliance]=useState<ComplianceData|null>(null);
  const [operations,setOperations]=useState<OperationsData|null>(null);
  const [loading,setLoading]=useState(true);
  const [message,setMessage]=useState("");
  const [editing,setEditing]=useState<ComplianceItem|null>(null);

  const load=useCallback(async()=>{
    setLoading(true);setMessage("");
    const endpoint=tab==="analytics"?`/api/admin/analytics?days=${days}`:tab==="support"?"/api/admin/support/metrics":tab==="automation"?"/api/admin/operations/summary":"/api/admin/compliance";
    try{const response=await fetch(endpoint,{credentials:"same-origin",cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"تعذر تحميل البيانات");if(tab==="analytics")setAnalytics(payload);else if(tab==="support")setSupport(payload);else if(tab==="automation")setOperations(payload);else setCompliance(payload);}catch(error){setMessage(error instanceof Error?error.message:"تعذر التحميل");}finally{setLoading(false);}
  },[tab,days]);
  useEffect(()=>{
    let active=true;
    const endpoint=tab==="analytics"?`/api/admin/analytics?days=${days}`:tab==="support"?"/api/admin/support/metrics":tab==="automation"?"/api/admin/operations/summary":"/api/admin/compliance";
    void fetch(endpoint,{credentials:"same-origin",cache:"no-store"})
      .then(async(response)=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error||"تعذر تحميل البيانات");return payload;})
      .then((payload)=>{if(!active)return;if(tab==="analytics")setAnalytics(payload);else if(tab==="support")setSupport(payload);else if(tab==="automation")setOperations(payload);else setCompliance(payload);})
      .catch((error:unknown)=>{if(active)setMessage(error instanceof Error?error.message:"تعذر التحميل");})
      .finally(()=>{if(active)setLoading(false);});
    return()=>{active=false;};
  },[tab,days]);

  const saveCompliance=async()=>{if(!editing)return;setMessage("");const response=await fetch("/api/admin/compliance",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(editing)});const payload=await response.json();if(!response.ok){setMessage(payload.error||"تعذر الحفظ");return;}setEditing(null);setMessage("تم حفظ بند الامتثال");await load();};
  const runOperation=async(endpoint:string,label:string)=>{setMessage("");const response=await fetch(endpoint,{method:"POST",credentials:"same-origin"});const payload=await response.json();if(!response.ok){setMessage(payload.error||"تعذر تشغيل المهمة");return;}setMessage(`${label} · ${JSON.stringify(payload.summary||payload.lifecycle||payload.result||{})}`);await load();};

  return <main className={styles.page}><div className={styles.shell}>
    <header className={styles.header}><div><h1>مركز التشغيل والتحليلات</h1><p>{adminName} · قرارات مبنية على بيانات حية وحوكمة قابلة للتتبع</p></div><nav className={styles.links}><Link href="/admin">لوحة الإدارة</Link><Link href="/admin/finance">المركز المالي</Link></nav></header>
    <div className={styles.tabs}><button className={tab==="analytics"?styles.active:""} onClick={()=>{setLoading(true);setMessage("");setTab("analytics");}}>التحويل والاحتفاظ</button><button className={tab==="support"?styles.active:""} onClick={()=>{setLoading(true);setMessage("");setTab("support");}}>تشغيل الدعم وSLA</button><button className={tab==="automation"?styles.active:""} onClick={()=>{setLoading(true);setMessage("");setTab("automation");}}>الأتمتة والطوابير</button><button className={tab==="compliance"?styles.active:""} onClick={()=>{setLoading(true);setMessage("");setTab("compliance");}}>ملف الامتثال</button></div>
    {message?<div className={styles.notice}>{message}</div>:null}
    {loading?<div className={styles.loading}>جارٍ تحميل المؤشرات…</div>:tab==="analytics"&&analytics?<AnalyticsView data={analytics} days={days} setDays={setDays}/>:tab==="support"&&support?<SupportView data={support}/>:tab==="automation"&&operations?<OperationsView data={operations} run={runOperation}/>:tab==="compliance"&&compliance?<ComplianceView data={compliance} editing={editing} setEditing={setEditing} save={saveCompliance}/>:null}
  </div></main>;
}

function AnalyticsView({data,days,setDays}:{data:AnalyticsData;days:number;setDays:(value:number)=>void}){const paid=data.totals.payment_paid||0;const checkout=data.totals.checkout_start||0;return <><div className={styles.toolbar}><div><h2>قمع التحويل</h2><p>من زيارة المادة حتى الدفع وبدء التعلم</p></div><label>الفترة<select value={days} onChange={(event)=>setDays(Number(event.target.value))}><option value={7}>7 أيام</option><option value={30}>30 يومًا</option><option value={90}>90 يومًا</option><option value={365}>سنة</option></select></label></div><section className={styles.grid}><Metric title="زيارات المواد" value={data.totals.course_view||0}/><Metric title="بدء الدفع" value={checkout}/><Metric title="دفعات ناجحة" value={paid}/><Metric title="تحويل الدفع" value={`${checkout?Math.round(paid/checkout*1000)/10:0}%`}/></section><div className={styles.two}><section className={styles.panel}><h2>مراحل التحويل</h2><div className={styles.funnel}>{data.funnel.map((row)=><article key={row.event}><span>{row.label}</span><b>{row.actors.toLocaleString("ar-SA")}</b><em>{row.conversionFromPrevious===null?"البداية":`${row.conversionFromPrevious}%`}</em></article>)}</div></section><section className={styles.panel}><h2>المواد الأعلى نشاطًا</h2><div className={styles.table}><table><thead><tr><th>المادة</th><th>المستخدمون</th><th>الأحداث</th></tr></thead><tbody>{data.topCourses.map((row)=><tr key={row.courseSlug||"unknown"}><td>{row.courseSlug||"غير محدد"}</td><td>{row.actors}</td><td>{row.events}</td></tr>)}</tbody></table></div></section></div><section className={styles.panel}><h2>الاحتفاظ حسب شهر الاشتراك</h2><p>بدء التعلم والاستمرار بعد 7 و30 يومًا من تاريخ تفعيل المادة.</p><div className={styles.table}><table><thead><tr><th>الشهر</th><th>الاشتراكات</th><th>بدأوا التعلم</th><th>بعد 7 أيام</th><th>بعد 30 يومًا</th></tr></thead><tbody>{data.cohorts.map((row)=><tr key={row.cohort}><td dir="ltr">{row.cohort}</td><td>{row.enrolled}</td><td>{row.activated} · {row.activationRate}%</td><td>{row.retained7} · {row.retention7Rate}%</td><td>{row.retained30} · {row.retention30Rate}%</td></tr>)}</tbody></table></div></section><section className={styles.panel}><h2>النشاط اليومي</h2><div className={styles.table}><table><thead><tr><th>اليوم</th><th>المستخدمون</th><th>الأحداث</th></tr></thead><tbody>{data.daily.map((row)=><tr key={row.day}><td>{row.day}</td><td>{row.actors}</td><td>{row.events}</td></tr>)}</tbody></table></div></section></>}

function SupportView({data}:{data:SupportData}){return <><section className={styles.grid}><Metric title="تذاكر مفتوحة" value={data.summary.open}/><Metric title="تجاوز الرد" value={data.summary.responseBreached} tone="danger"/><Metric title="تجاوز الحل" value={data.summary.resolutionBreached} tone="warning"/><Metric title="متوسط أول رد" value={data.summary.averageFirstResponseMinutes===null?"—":`${data.summary.averageFirstResponseMinutes} د`}/></section><div className={styles.two}><section className={styles.panel}><h2>الطوابير</h2><div className={styles.funnel}>{data.queues.map((row)=><article key={row.category}><span>{categoryLabel[row.category]||row.category}</span><b>{row.count}</b><em className={row.overdue?styles.danger:styles.ok}>{row.overdue?`${row.overdue} متأخرة`:"ضمن SLA"}</em></article>)}</div></section><section className={styles.panel}><h2>الأولوية التشغيلية</h2><div className={styles.table}><table><thead><tr><th>التذكرة</th><th>العنوان</th><th>الحالة</th><th>SLA</th></tr></thead><tbody>{data.tickets.filter((row)=>row.responseBreached||row.resolutionBreached).slice(0,30).map((row)=><tr key={row.id}><td dir="ltr">{row.ticketNumber}</td><td>{row.title}</td><td>{row.status}</td><td className={styles.danger}>متأخرة</td></tr>)}</tbody></table></div></section></div></>}

function OperationsView({data,run}:{data:OperationsData;run:(endpoint:string,label:string)=>Promise<void>}){return <><section className={styles.grid}><Metric title="سلال/دفعات متروكة" value={data.queues.abandonedCheckout}/><Metric title="وصول ينتهي قريبًا" value={data.queues.expiringAccess}/><Metric title="مرفقات تنتظر الفحص" value={data.queues.filesPendingScan} tone="warning"/><Metric title="Push ينتظر الإرسال" value={data.queues.pushPending}/><Metric title="استردادات قيد المراجعة" value={data.queues.refundPending}/><Metric title="تسويات غير مطابقة" value={data.queues.settlementUnmatched} tone="warning"/><Metric title="قائمة انتظار نشطة" value={data.waitlist.active||0}/><Metric title="باقات منشورة" value={data.bundles.published||0}/></section><section className={styles.panel}><h2>تشغيل المهام الآمنة</h2><p>يمكن تشغيلها يدويًا هنا، وتعمل أيضًا عبر المجدول باستخدام مفتاح مستقل.</p><div className={styles.actions}><button onClick={()=>void run("/api/admin/lifecycle/dispatch","اكتملت تنبيهات دورة الحياة")}>تنبيهات السلة والتجديد والإطلاق</button><button onClick={()=>void run("/api/admin/files/scan","اكتمل فحص دفعة المرفقات")}>فحص المرفقات المعلقة</button><button onClick={()=>void run("/api/admin/notifications/dispatch","اكتمل إرسال الإشعارات المستحقة")}>إرسال Push المستحق</button></div></section></>}

function ComplianceView({data,editing,setEditing,save}:{data:ComplianceData;editing:ComplianceItem|null;setEditing:(item:ComplianceItem|null)=>void;save:()=>void}){return <><section className={styles.grid}><Metric title="نسبة الجاهزية" value={`${data.progress}%`}/><Metric title="بنود موثقة" value={data.items.filter((item)=>item.status==="verified").length}/><Metric title="قيد العمل" value={data.items.filter((item)=>item.status==="in_progress").length}/><Metric title="لم تبدأ" value={data.items.filter((item)=>item.status==="not_started").length}/></section><div className={styles.notice}>{data.disclaimer}</div><section className={styles.items}>{data.items.map((item)=><article className={styles.item} key={item.key}><header><div><small>{item.area}</small><h3>{item.title}</h3></div><span className={styles.status}>{statusLabel[item.status]||item.status}</span></header><p>{item.description}</p><small>الدليل المقترح: {item.evidenceHint}</small><button onClick={()=>setEditing(editing?.key===item.key?null:{...item})}>{editing?.key===item.key?"إغلاق":"تحديث البند"}</button>{editing?.key===item.key?<div className={styles.editor}><label>الحالة<select value={editing.status} onChange={(event)=>setEditing({...editing,status:event.target.value})}><option value="not_started">لم يبدأ</option><option value="in_progress">قيد العمل</option><option value="ready">جاهز للمراجعة</option><option value="verified">موثّق</option></select></label><label>المسؤول<input value={editing.owner} onChange={(event)=>setEditing({...editing,owner:event.target.value})}/></label><label>رابط أو وصف الدليل<textarea value={editing.evidence} onChange={(event)=>setEditing({...editing,evidence:event.target.value})}/></label><label>تاريخ المراجعة<input type="date" value={editing.reviewDate} onChange={(event)=>setEditing({...editing,reviewDate:event.target.value})}/></label><label>ملاحظات<textarea value={editing.notes} onChange={(event)=>setEditing({...editing,notes:event.target.value})}/></label><button className={styles.save} onClick={save}>حفظ وتوثيق</button></div>:null}</article>)}</section></>}

function Metric({title,value,tone}:{title:string;value:string|number;tone?:"danger"|"warning"}){return <article className={styles.metric}><small>{title}</small><strong className={tone?styles[tone]:undefined}>{typeof value==="number"?value.toLocaleString("ar-SA"):value}</strong><em>بيانات حية</em></article>}
