"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Sparkles } from "lucide-react";
import { studyJson } from "@/lib/ai-job-client";
import type { AiArtifactPayload, AiConversationSummary, AiQuizPayload, AiEntitlementStatus, AiUsageStatus } from "@/lib/ai-contracts";
import { StudyFileTools, StudyToolCards, type StudyAction } from "./study-file-tools";
import { StudyArtifactDownload } from "./study-artifact-download";
import { StudyRichText } from "./study-rich-text";
import { AiQuizRunner } from "./ai-quiz-runner";
import styles from "./study-tools.module.css";
type WorkspaceProps = { userId: number; studentName: string; initialConversationId: number | null; initialQuizId: number | null; initialService?: StudyAction | null };
export function MerasAiWorkspace(props: WorkspaceProps) {
  const [mode,setMode] = useState<StudyAction|null>(props.initialService || null), [history,setHistory] = useState<AiConversationSummary[]>([]), [selected,setSelected] = useState(props.initialConversationId), [quizId,setQuizId] = useState(props.initialQuizId);
  const [detail,setDetail] = useState<{ artifacts: AiArtifactPayload[]; quizzes: AiQuizPayload[] }|null>(null), [quiz,setQuiz] = useState<AiQuizPayload|null>(null), [error,setError] = useState("");
  const [status,setStatus] = useState<{entitlement:AiEntitlementStatus;services:Record<string,AiUsageStatus>}|null>(null);
  useEffect(()=>{const abort=new AbortController();void studyJson<{entitlement:AiEntitlementStatus;services:Record<string,AiUsageStatus>}>("/api/ai/status",{signal:abort.signal}).then(value=>{if(!abort.signal.aborted)setStatus(value);}).catch(reason=>{if(!abort.signal.aborted)setError(reason instanceof Error?reason.message:"تعذر تحميل الحصة");});return()=>abort.abort();},[props.userId,mode]);
  useEffect(()=>{const abort=new AbortController();void studyJson<{conversations:AiConversationSummary[]}>("/api/ai/conversations",{signal:abort.signal}).then(data=>{if(!abort.signal.aborted)setHistory(data.conversations.filter(row=>!row.kind.startsWith("lesson_tutor:")));}).catch(()=>{});return()=>abort.abort();},[mode,props.userId]);
  useEffect(()=>{const abort=new AbortController();if(selected)void studyJson<{artifacts:AiArtifactPayload[];quizzes:AiQuizPayload[]}>(`/api/ai/conversations/${selected}`,{signal:abort.signal}).then(data=>{if(!abort.signal.aborted)setDetail(data);}).catch(reason=>{if(!abort.signal.aborted)setError(reason instanceof Error?reason.message:"تعذر استعادة النتائج");});return()=>abort.abort();},[selected]);
  useEffect(()=>{const abort=new AbortController();if(quizId)void studyJson<{quiz:AiQuizPayload}>(`/api/ai/quizzes/${quizId}`,{signal:abort.signal}).then(data=>{if(!abort.signal.aborted)setQuiz(data.quiz);}).catch(reason=>{if(!abort.signal.aborted)setError(reason instanceof Error?reason.message:"تعذر استعادة الاختبار");});return()=>abort.abort();},[quizId]);
  function home(){setMode(null);setSelected(null);setDetail(null);setQuizId(null);setQuiz(null);setError("");}
  return <section className={styles.page} dir="rtl"><header className={styles.hero}><div><span className={styles.eyebrow}><Sparkles size={18}/> مساحة الدراسة الذكية</span><h1>فهمٌ أعمق.<br/><span>وكل أدواتك أقرب.</span></h1><p>أهلًا {props.studentName.split(" ")[0]}، حوّل محاضراتك إلى ملخصات منظمة، وترجمات أكاديمية، واختبارات تثبّت فهمك.</p></div><div className={styles.heroActions}><span className={styles.heroMark} aria-hidden="true"><Sparkles size={52}/></span>{(mode||selected||quizId)&&<button className={styles.secondary} onClick={home}>كل الأدوات</button>}<Link className={styles.secondary} href="/dashboard">لوحة الطالب</Link></div></header>
    {status&&<section className={styles.quotaPanel} aria-label="حصة أدوات مراس"><p>{status.entitlement.active ? "مزايا أدواتك مفعّلة" : "أدواتك الأساسية متاحة حسب الحصة"}</p><div className={styles.actions}>{(["summary","translation","quiz"] as const).map(action=><span key={action}>{({summary:"التلخيص",translation:"الترجمة",quiz:"الاختبارات"})[action]}: {status.services[action]?.enabled ? `${status.services[action].remaining} متبقية` : "متوقفة مؤقتًا"}</span>)}</div>{!status.entitlement.active&&<Link className={styles.secondary} href="/study-tools/subscribe">مزايا الاشتراك</Link>}</section>}
    {error&&<p role="alert" className={styles.error}>{error}</p>}
    {quiz?<AiQuizRunner key={quiz.id} quiz={quiz} onClose={home}/>:mode?<StudyFileTools key={`${props.userId}:${mode}`} action={mode} storageScope={`${props.userId}:workspace`} onBack={home}/>:detail?<section className={styles.panel}>{detail.artifacts?.map(item=><article key={item.id}><h2>{item.title}</h2><StudyRichText content={item.content}/><StudyArtifactDownload id={item.id}/></article>)}{detail.quizzes?.map(item=><button key={item.id} className={styles.primary} onClick={()=>setQuizId(item.id)}>{item.title}</button>)}</section>:<><StudyToolCards onSelect={action=>{if(action!=="chat")setMode(action);}}/><section className={`${styles.panel} ${styles.historyPanel}`}><div className={styles.panelHeader}><div><span className={styles.eyebrow}>مكتبتك الدراسية</span><h2>نتائجك السابقة</h2></div><span className={styles.hint}>عد إلى ما أنجزته، دون توليد جديد</span></div>{history.length?history.map(row=><button key={row.id} className={styles.historyItem} onClick={()=>{setDetail(null);setQuiz(null);setSelected(row.id);setError("");}}>{row.title}</button>):<p>تظهر هنا نتائج الملفات بعد تجهيزها.</p>}</section></>}
  </section>;
}
