"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, BookOpen, CheckCircle2, FileUp, GraduationCap, PlayCircle, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { BrandLogo } from "./brand-logo";
import { ThemeToggle } from "./theme-provider";

const steps = [
  { icon: UserRound, kicker: "ملفك الدراسي", title: "مرحبًا بك في مساحة تعلم صُممت لك", text: "كلما اكتمل ملفك الدراسي، أصبحت توصيات مراس أدق وأسهل في الوصول. لا تحتاج إلى إعادة ضبط تفضيلاتك كل مرة.", points: ["اقتراحات بحسب الجامعة والتخصص", "حساب واحد على الويب والتطبيق", "بياناتك محفوظة ومحمية"] },
  { icon: GraduationCap, kicker: "اكتشاف أسرع", title: "ابدأ من موادك، ثم توسّع كما تريد", text: "ستظهر لك المواد الأقرب إلى مسارك أولًا، مع إمكانية تغيير الجامعة والتخصص والبحث في كامل الكتالوج متى رغبت.", points: ["فلترة تلقائية ذكية", "بحث في جميع الجامعات", "مفضلة وسلة وتقدم موحّد"] },
  { icon: PlayCircle, kicker: "تعلّم بلا انقطاع", title: "مشغل يحفظ رحلتك من آخر ثانية", text: "شاهد الدرس المجاني، ثم واصل دروسك المدفوعة من أي جهاز. يتولى الخادم حماية الجلسة وحفظ تقدمك تلقائيًا.", points: ["استكمال المشاهدة تلقائيًا", "سرعات وجودات متعددة", "وصول آمن بعد الدفع"] },
  { icon: FileUp, kicker: "مادة غير موجودة؟", title: "اطلبها وتابعها مع مشرفك", text: "أرسل اسم المادة ورمزها وارفع التوصيف أو السلايدات. تظهر الحالة في حسابك ويصلك إشعار عند كل خطوة.", points: ["حتى 100 ملف بإجمالي 100MB", "محادثة دعم مرتبطة بالحساب", "تنبيه مباشر عند التوفير"] },
  { icon: ShieldCheck, kicker: "أنت جاهز", title: "رحلتك الجامعية تبدأ الآن", text: "أصبح لديك طريق واضح للاستكشاف، والمشاهدة، والشراء، وطلب المواد، والتواصل مع فريق مراس من مكان واحد.", points: ["دفع مؤكد من الخادم", "إشعارات تفاعلية", "صلاحيات منفصلة لكل دور"] },
];

export function OnboardingTour({ firstName }: { firstName: string }) {
  const [step, setStep] = useState(0);
  const [loading, setLoading] = useState(false);
  const current = steps[step]; const Icon = current.icon; const progress = ((step + 1) / steps.length) * 100;
  const finish = async () => { setLoading(true); const response = await fetch("/api/profile/onboarding", { method: "POST" }); if (response.ok) { const target = sessionStorage.getItem("meras_return_to") || "/dashboard"; sessionStorage.removeItem("meras_return_to"); window.location.assign(target); } else setLoading(false); };
  return <main className="onboarding-page"><header><BrandLogo compact /><div className="onboarding-header-actions"><span><ShieldCheck size={14} /> تجربة آمنة ومخصصة</span><ThemeToggle compact /></div></header><section className="onboarding-shell"><aside><div className="onboarding-welcome"><span className="onboarding-avatar"><Sparkles size={18} /></span><div><span>مرحبًا</span><strong>{firstName}</strong></div></div><h1>دليل البداية</h1><p>رحلة قصيرة لتجعل مراس أقرب إلى طريقتك في التعلم.</p><div className="onboarding-progress"><div><span>تقدم الإعداد</span><b>{step + 1} / {steps.length}</b></div><i><em style={{ width: `${progress}%` }} /></i></div><nav>{steps.map((item, index) => <button type="button" key={item.title} className={index === step ? "active" : index < step ? "done" : ""} onClick={() => setStep(index)}><i>{index < step ? <CheckCircle2 size={16} /> : index + 1}</i><span><strong>{item.kicker}</strong><small>{item.title}</small></span></button>)}</nav><div className="onboarding-aside-note"><ShieldCheck size={16} /><span>لا نطلب منك كلمة مرور أو بيانات بطاقة في هذه الرحلة.</span></div></aside><article><div className="onboarding-visual" key={current.title}><span /><span /><i><Icon size={45} /></i><b>{String(step + 1).padStart(2, "0")}</b><small>مراس العلم</small></div><div className="onboarding-copy"><span className="onboarding-kicker">{current.kicker}</span><h2>{current.title}</h2><p>{current.text}</p><ul>{current.points.map((point) => <li key={point}><CheckCircle2 size={17} />{point}</li>)}</ul>{step === 1 && <Link href="/courses" className="onboarding-inline-link"><BookOpen size={17} /> استكشف الكتالوج الآن</Link>}{step === 3 && <Link href="/request-course" className="onboarding-inline-link"><FileUp size={17} /> فتح نموذج طلب المادة</Link>}<footer><button type="button" className="button button-ghost" disabled={step === 0} onClick={() => setStep(step - 1)}>السابق</button>{step < steps.length - 1 ? <button type="button" className="button button-primary" onClick={() => setStep(step + 1)}>التالي <ArrowLeft size={16} /></button> : <button type="button" className="button button-primary" disabled={loading} onClick={finish}>{loading ? "جارٍ تجهيز لوحتك..." : "ابدأ في لوحتي"} <BookOpen size={16} /></button>}</footer></div></article></section></main>;
}
