"use client";
import { useCallback, useEffect, useState } from "react";
import { BookOpen, Plus, Save, Search } from "lucide-react";
import { adminFetch } from "@/lib/admin-client";
import { confirmAction } from "@/lib/interaction-events";
import { FAQ_CATEGORIES, validateInformation, type InformationContent } from "@/lib/information-contract";
import styles from "./staff-manager.module.css";
export function PublicContentEditor() {
  const [draft, setDraft] = useState<InformationContent | null>(null); const [version, setVersion] = useState<string | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [dirty, setDirty] = useState(false); const [query, setQuery] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { try { const response = await adminFetch("/api/admin/content", { signal }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر تحميل المحتوى"); if (signal?.aborted) return; setDraft(result.content); setVersion(result.version); setDirty(false); setError(""); } catch (e) { if (!signal?.aborted) setError(e instanceof Error ? e.message : "تعذر التحميل"); } }, []);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => void load(controller.signal), 0); return () => { clearTimeout(timer); controller.abort(); }; }, [load]);
  useEffect(() => { if (!dirty) return; const prevent = (e: BeforeUnloadEvent) => { e.preventDefault(); }; window.addEventListener("beforeunload", prevent); return () => window.removeEventListener("beforeunload", prevent); }, [dirty]);
  function change(next: InformationContent) { setDraft(next); setDirty(true); }
  async function publish() {
    if (!draft || busy) return;
    try { validateInformation(draft); } catch (e) { setError(e instanceof Error ? e.message : "تحقق من النصوص"); return; }
    if (!await confirmAction({ title: "نشر محتوى الصفحات؟", message: "سيظهر المحتوى للزوار في الويب والتطبيق. تأكد من دقته، ولا تكتب اعتمادًا أو ضمانًا دون دليل. تحفظ نسخة من التغيير في سجل التدقيق.", confirmLabel: "نشر", destructive: false })) return;
    setBusy(true); setError("");
    try { const response = await adminFetch("/api/admin/content", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ content: draft, version }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر النشر"); setVersion(result.version); setDirty(false); }
    catch (e) { setError(e instanceof Error ? e.message : "تعذر النشر"); }
    finally { setBusy(false); }
  }
  if (!draft) return <section className={styles.root}><p role="status">{error || "جارٍ تحميل المحتوى…"}</p><button className="button button-outline" onClick={() => void load()}>إعادة التحميل</button></section>;
  return <section className={styles.root}><header className={styles.hero}><div><span className={styles.eyebrow}><BookOpen size={17}/> محتوى عام قابل للنشر</span><h1>صفحات تعرف مراس بوضوح</h1><p>نصوص «عن مراس» و«لماذا مراس» والأسئلة الشائعة من مصدر واحد للويب والتطبيق. لا يقبل المحرر أكواد HTML أو نصوصًا تنفيذية.</p></div><button className="button button-primary" disabled={!dirty || busy} onClick={() => void publish()}><Save size={17}/>{busy ? "جارٍ النشر…" : "نشر التغييرات"}</button></header>
    {error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.toolbar}><span>{dirty ? "تعديلات غير منشورة" : "كل التعديلات محفوظة"} · {version ? `آخر نشر ${new Date(version).toLocaleString("ar-SA")}` : "المحتوى الافتراضي"}</span><button type="button" disabled={busy} onClick={async () => { if (!dirty || await confirmAction("تجاهل التعديلات غير المنشورة وتحميل آخر نسخة؟")) await load(); }}>إعادة تحميل المنشور</button></div>
    <fieldset className={styles.editor} disabled={busy}><legend>عن مراس</legend><div className={styles.fields}>{([['title','عنوان الصفحة',100],['intro','المقدمة',600],['mission','الرسالة',1600],['vision','الرؤية',1600]] as const).map(([key,label,max]) => <label key={key}>{label}<textarea rows={key === "title" ? 2 : 4} maxLength={max} value={draft.about[key]} onChange={e => change({ ...draft, about: { ...draft.about, [key]: e.target.value } })}/><small>{[...draft.about[key]].length}/{max}</small></label>)}</div>
      <h2>بطاقات لماذا مراس</h2><div className={styles.grants}>{draft.about.why.map((item,index) => <div key={index}><label>عنوان البطاقة<input maxLength={100} value={item.title} onChange={e => change({ ...draft, about: { ...draft.about, why: draft.about.why.map((row,i) => i === index ? { ...row, title: e.target.value } : row) } })}/></label><label>الشرح<textarea rows={5} maxLength={1200} value={item.body} onChange={e => change({ ...draft, about: { ...draft.about, why: draft.about.why.map((row,i) => i === index ? { ...row, body: e.target.value } : row) } })}/></label></div>)}</div>
    </fieldset><section className={styles.editor}><header><h2>مركز الأسئلة الشائعة · {draft.faq.length}</h2><button className="button button-outline" disabled={busy || draft.faq.length >= 80} onClick={() => { change({ ...draft, faq: [...draft.faq, { id: `faq-${crypto.randomUUID()}`, category: "start", question: "سؤال جديد — عدّل النص", answer: "اكتب الإجابة الدقيقة التي يحتاج الطالب معرفتها هنا." }] }); setQuery(""); }}><Plus size={17}/> سؤال جديد</button></header><label className={styles.toolbar}><Search size={18}/><input aria-label="البحث في محتوى الأسئلة" value={query} onChange={e => setQuery(e.target.value)} placeholder="ابحث لتعديل سؤال…"/></label>
      {draft.faq.map((item,index) => ({item,index})).filter(({item}) => `${item.question} ${item.answer}`.includes(query)).map(({item,index}) => <details key={item.id} className={styles.member}><summary>{index + 1}. {item.question}</summary><div className={styles.editor}><label>التصنيف<select value={item.category} disabled={busy} onChange={e => change({ ...draft, faq: draft.faq.map(row => row.id === item.id ? { ...row, category: e.target.value as typeof item.category } : row) })}>{Object.entries(FAQ_CATEGORIES).map(([key,label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>السؤال<input maxLength={250} disabled={busy} value={item.question} onChange={e => change({ ...draft, faq: draft.faq.map(row => row.id === item.id ? { ...row, question: e.target.value } : row) })}/></label><label>الإجابة<textarea rows={6} maxLength={2400} disabled={busy} value={item.answer} onChange={e => change({ ...draft, faq: draft.faq.map(row => row.id === item.id ? { ...row, answer: e.target.value } : row) })}/></label><div className={styles.actions}><button disabled={busy || index === 0} onClick={() => { const faq = [...draft.faq]; [faq[index - 1], faq[index]] = [faq[index], faq[index - 1]]; change({ ...draft, faq }); }}>نقل للأعلى</button><button disabled={busy || index === draft.faq.length - 1} onClick={() => { const faq = [...draft.faq]; [faq[index + 1], faq[index]] = [faq[index], faq[index + 1]]; change({ ...draft, faq }); }}>نقل للأسفل</button><button disabled={busy || draft.faq.length <= 1} onClick={async () => { if (await confirmAction({ title: "حذف السؤال من المسودة؟", message: item.question, destructive: true })) change({ ...draft, faq: draft.faq.filter(row => row.id !== item.id) }); }}>حذف السؤال</button></div></div></details>)}
    </section><button className="button button-primary" disabled={!dirty || busy} onClick={() => void publish()}>نشر المحتوى العام</button></section>;
}
