"use client";
import { forwardRef, useId, useState } from "react";
import { Check, Eye, EyeOff, LockKeyhole } from "lucide-react";
import { normalizeVerificationCode, passwordRequirements } from "@/lib/security-form";

/** One real input preserves autofill, paste, screen-reader and keyboard behavior. */
export const VerificationCodeInput = forwardRef<HTMLInputElement, { value: string; onChange: (value: string) => void; name?: string; id?: string; disabled?: boolean; invalid?: boolean; label?: string }>(function VerificationCodeInput({ value, onChange, name = "code", id, disabled, invalid, label = "رمز التحقق" }, ref) {
  const uid = useId(); const inputId = id || uid;
  return <div className="security-code-field"><label htmlFor={inputId}>{label}</label><div className="security-code-wrap" data-invalid={invalid || undefined} data-disabled={disabled || undefined} dir="ltr"><div className="security-code-cells" aria-hidden="true">{Array.from({ length: 6 }, (_, index) => <span key={index} data-filled={Boolean(value[index])} data-current={index === Math.min(value.length, 5)}>{value[index] || ""}</span>)}</div><input ref={ref} id={inputId} name={name} aria-describedby={`${inputId}-help`} aria-invalid={invalid || undefined} aria-label={label} disabled={disabled} className="security-code-input" required inputMode="numeric" type="text" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} value={value} onChange={event => onChange(normalizeVerificationCode(event.target.value))} onPaste={event => { const pasted = normalizeVerificationCode(event.clipboardData.getData("text")); if (pasted) { event.preventDefault(); onChange(pasted); } }} /></div><small id={`${inputId}-help`}>أدخل الأرقام الستة، أو الصق الرمز كاملًا.</small></div>;
});

export function PasswordField({ value, onChange, name, label, disabled = false, requirements = false }: { value: string; onChange: (value: string) => void; name: string; label: string; disabled?: boolean; requirements?: boolean }) {
  const uid = useId(); const [show, setShow] = useState(false); const [caps, setCaps] = useState(false);
  const checks = passwordRequirements(value);
  return <div className="security-password-field"><label htmlFor={uid}>{label}</label><div className="security-password-wrap"><LockKeyhole size={19} aria-hidden="true" /><input id={uid} name={name} type={show ? "text" : "password"} value={value} disabled={disabled} onChange={event => onChange(event.target.value)} onKeyUp={event => setCaps(event.getModifierState("CapsLock"))} onBlur={() => setCaps(false)} autoComplete="new-password" required minLength={10} maxLength={128} dir="ltr" aria-describedby={requirements ? `${uid}-requirements` : undefined} /><button type="button" aria-label={show ? `إخفاء ${label}` : `إظهار ${label}`} aria-pressed={show} onClick={() => setShow(!show)}>{show ? <EyeOff size={19} /> : <Eye size={19} />}</button></div>{caps && <small role="status">مفتاح الأحرف الكبيرة مفعّل.</small>}{requirements && <div className="security-password-rules" id={`${uid}-requirements`}>{([["length", "10 أحرف على الأقل"], ["number", "رقم"], ["symbol", "رمز خاص"]] as const).map(([key, text]) => <span key={key} data-valid={checks[key]}><Check size={13} aria-hidden="true" />{text}</span>)}</div>}</div>;
}
