"use client";

import Link from "next/link";
import { ArrowLeft, BookOpen, CheckCircle2, Clock3, FileUp, GraduationCap, Play, ShieldCheck, Sparkles } from "lucide-react";
import type { DashboardCourse, DashboardRecommendation, DashboardRequest, DashboardUser } from "./student-dashboard";
import styles from "./student-overview.module.css";

export function studyProgress(value: number) { return Number.isFinite(value) ? Math.max(0, Math.min(100, Math.round(value))) : 0; }

export function StudentOverview({ user, owned, requests, recommended, setActive }: { user: DashboardUser; owned: DashboardCourse[]; requests: DashboardRequest[]; recommended: DashboardRecommendation[]; setActive: (id: string) => void }) {
  const active = owned.filter((course) => course.accessState === "active");
  const first = active.find((course) => studyProgress(course.progress) < 100) || active[0];
  const completed = active.filter((course) => studyProgress(course.progress) === 100).length;
  const progress = first ? studyProgress(first.progress) : 0;
  return <div className={styles.overview}>
    <header className={styles.welcome}><div><span>مساحتك، بكل ما تتعلّمه.</span><h1>أهلًا {user.fullName.trim().split(/\s+/)[0]}،<br /><em>لنكمل خطوة أبعد.</em></h1><p>خطتك أوضح، ووقتك للتعلّم. اختر خطوتك التالية.</p></div><Link href="/courses" className={styles.explore}><GraduationCap size={19} /> استكشف المواد <ArrowLeft size={17} /></Link></header>
    <div className={styles.workspace}>
      <section className={styles.focus} aria-labelledby="study-focus-title"><div className={styles.focusTop}><span><i /> {first ? "جاهز لخطوتك التالية" : "البداية هنا"}</span><BookOpen size={22} /></div><div className={styles.focusCopy}><small>{first ? "أكمل رحلتك مع" : "مساحة جديدة. فرصة جديدة."}</small><h2 id="study-focus-title">{first?.title || "كل إنجاز، يبدأ بفهم."}</h2><p>{first?.current || "اكتشف مواد جامعتك، واطّلع على الدروس التجريبية المتاحة قبل الاشتراك."}</p></div>{first ? <><div className={styles.progressLabel}><span>تقدّمك في المادة</span><strong><bdi>{progress}%</bdi></strong></div><div className={styles.track} role="progressbar" aria-label="تقدم المادة" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><span style={{ width: progress + "%" }} /></div></> : null}<footer><Link href={first ? "/learn/" + first.slug : "/courses"}><Play size={16} fill="currentColor" />{first ? (progress === 100 ? "راجع ما تعلّمته" : "متابعة التعلّم") : "اكتشف أول مادة"}<ArrowLeft size={17} /></Link>{first ? <span><Clock3 size={14} />{first.remaining}</span> : <span>تعلّم على إيقاعك</span>}</footer></section>
      <section className={styles.toolkit} aria-labelledby="study-toolkit-title"><span className={styles.toolkitIcon}><Sparkles size={24} /></span><small>مراس الذكية</small><h2 id="study-toolkit-title">من ملف طويل،<br />إلى فكرة واضحة.</h2><p>ملخّص للمراجعة، ترجمة للمصطلحات، أو اختبار يثبّت فهمك.</p><div className={styles.toolLinks}><Link href="/study-tools?service=summary">تلخيص <ArrowLeft size={15} /></Link><Link href="/study-tools?service=translation">ترجمة <ArrowLeft size={15} /></Link><Link href="/study-tools?service=quiz">اختبر فهمك <ArrowLeft size={15} /></Link></div></section>
    </div>
    <div className={styles.metrics} aria-label="رحلتك بالأرقام">{[{ icon: BookOpen, value: active.length, label: "مادة متاحة", action: "courses" }, { icon: CheckCircle2, value: completed, label: "مادة أتممتها", action: "courses" }, { icon: FileUp, value: requests.length, label: "طلب مادة", action: "requests" }].map(({ icon: Icon, value, label, action }) => <button type="button" key={label} onClick={() => setActive(action)}><i><Icon size={21} /></i><span><strong>{value.toLocaleString("ar-SA")}</strong><small>{label}</small></span><ArrowLeft size={15} /></button>)}</div>
    <section className={styles.library} aria-labelledby="study-library-title"><header className={styles.sectionHead}><div><span>مسارك المستمر</span><h2 id="study-library-title">مكتبتك التعليمية</h2></div><button type="button" onClick={() => setActive("courses")}>كل موادي <ArrowLeft size={16} /></button></header>{active.length ? <div className={styles.courseList}>{active.slice(0, 3).map((course) => <Link href={"/learn/" + course.slug} key={course.slug}><span className={styles.courseIcon} aria-hidden="true">{course.icon}</span><div><small>{course.university}</small><h3>{course.title}</h3><p>{course.current}</p></div><div className={styles.courseProgress}><bdi>{studyProgress(course.progress)}%</bdi><div><span style={{ width: studyProgress(course.progress) + "%" }} /></div></div><span className={styles.courseArrow}><ArrowLeft size={18} /></span></Link>)}</div> : <div className={styles.empty}><BookOpen size={30} /><div><h3>مكتبتك تنتظر أول مادة</h3><p>ستجد هنا دروسك وتقدمك وملاحظاتك بعد تفعيل الاشتراك.</p></div><Link href="/courses">تصفح المواد <ArrowLeft size={16} /></Link></div>}</section>
    <div className={styles.nextSteps}><Link href="/request-course"><FileUp size={23} /><div><small>ابنِ مسارك معنا</small><h3>لم تجد مادتك؟</h3><p>أرسل اسم المادة وملفاتها، وتابع التجهيز من حسابك.</p></div><ArrowLeft size={19} /></Link><button type="button" onClick={() => setActive("account")}><ShieldCheck size={23} /><div><small>حسابك بين يديك</small><h3>{user.emailVerified ? "تعلم بثقة واطمئنان" : "أكمل توثيق بريدك"}</h3><p>{user.emailVerified ? "إعدادات الحساب وأمان أجهزتك، في مكان واحد." : "وثّق بريدك لتتمكن من الاشتراك واستعادة الوصول بسهولة."}</p></div><ArrowLeft size={19} /></button></div>
    {recommended.length ? <section className={styles.recommendations} aria-labelledby="study-recommendations-title"><header className={styles.sectionHead}><div><span>أفق جديد لتعلّمك</span><h2 id="study-recommendations-title">قد تكون خطوتك التالية</h2></div><Link href="/courses">كل المواد <ArrowLeft size={16} /></Link></header><div className={styles.recommendationGrid}>{recommended.slice(0, 3).map((course) => <Link href={"/courses/" + course.slug} key={course.slug}><header><span aria-hidden="true">{course.icon}</span><small>{course.match}</small></header><h3>{course.title}</h3><p>{course.university} · {course.specialty}</p><footer><strong>{course.price.toLocaleString("ar-SA")} <small>ر.س</small></strong><ArrowLeft size={17} /></footer></Link>)}</div></section> : null}
  </div>;
}
