/** Real device/session/controller integration. Never accepts production data or provider credentials. */
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { and, eq, isNull } from "drizzle-orm";
const local = JSON.parse(readFileSync(".data/qa-database.json", "utf8")) as { url: string };
const url = new URL(local.url);
if (url.hostname !== "127.0.0.1" || url.pathname !== "/maras_qa" || process.env.DATABASE_URL !== local.url) throw new Error("Dedicated loopback maras_qa required");
if (["GEMINI_API_KEY", "GEMINI_API_KEYS", "RESEND_API_KEY", "TAP_SECRET_KEY", "S3_BUCKET", "BUCKET"].some(key => process.env[key])) throw new Error("Live provider credentials prohibited");
const origin = "https://maras-qa.example";
process.env.APP_URL = origin;
const [{ getDb, closeDb }, s, auth, deviceService, controller, mfa] = await Promise.all([
  import("../db"), import("../db/schema"), import("../lib/auth"), import("../lib/auth-devices"), import("../app/api/admin/students/[email]/devices/route"), import("../lib/admin-mfa"),
]);
const db = getDb(), nonce = randomUUID().slice(0, 8), now = () => new Date().toISOString();
const fixture = JSON.parse(readFileSync(".data/qa-fixtures.json", "utf8")) as { users: { id: number; role: string; email: string; token: string }[] };
const ownerFixture = fixture.users.find(user => user.role === "admin")!;
const [ownerRow] = await db.select().from(s.users).where(eq(s.users.id, ownerFixture.id));
assert.equal(ownerRow.isPlatformOwner, true);
const owner = auth.sessionUserFromRow(ownerRow);
const checks: string[] = [];
const pass = (message: string) => { checks.push(message); console.log(`PASS DEVICE ${message}`); };
function request(path: string, token = "", body?: unknown, headers: Record<string, string> = {}, method?: string) {
  return new Request(origin + path, { method: method || (body === undefined ? "GET" : "POST"), headers: { origin, "user-agent": "Synthetic device QA", "x-meras-device-id": `qa-device-${nonce}-operator`, ...(token ? { cookie: `${auth.SESSION_COOKIE}=${token}` } : {}), ...(body === undefined ? {} : { "content-type": "application/json" }), ...headers }, body: body === undefined ? undefined : JSON.stringify(body) });
}
async function newUser(label: string, role = "student") {
  const [row] = await db.insert(s.users).values({ email: `qa-device-${nonce}-${label}@example.test`, fullName: `اختبار أجهزة ${label}`, role, status: "active", profileCompletedAt: now(), onboardingCompletedAt: now() }).returning();
  return auth.sessionUserFromRow(row);
}
const savedFetch = globalThis.fetch;
globalThis.fetch = async () => { throw new Error("Network disabled in isolated device tests"); };
let ownerFactor: number | null = null;
try {
  const student = await newUser("student"), stranger = await newUser("other"), staff = await newUser("staff", "supervisor");
  const context = { params: Promise.resolve({ email: student.email }) };
  const endpoint = `/api/admin/students/${encodeURIComponent(student.email)}/devices`;
  const identity = (label: string) => `qa-device-${nonce}-${label}-installation`;
  const login = (label: string) => request("/api/auth/login", "", undefined, { "x-meras-device-id": identity(label) });
  const sessionA = await auth.createSession(student.id, login("a"));
  const sessionB = await auth.createSession(student.id, login("b"));
  const rows = () => db.select().from(s.authDevices).where(eq(s.authDevices.userId, student.id));
  const activeCount = async () => (await rows()).filter(row => !row.revokedAt).length;
  const device = async (label: string) => (await rows()).find(row => row.deviceId === identity(label))!;
  const mutation = async (label: string, action: import("../lib/device-access-policy").DeviceAction, extra: Record<string, unknown> = {}) => {
    const row = await device(label);
    return controller.POST(request(endpoint, ownerFixture.token, { action, deviceId: row.id, expectedRevision: row.policyVersion, reason: "مراجعة طلب الطالب الاصطناعي", ...extra }, stepHeaders), context);
  };
  const staffSession = await auth.createSession(staff.id, request("/api/auth/login"));
  await db.insert(s.staffPermissions).values({ userId: staff.id, permission: "students.manage", grantedBy: owner.id });
  assert.equal((await controller.GET(request(endpoint, staffSession.token), context)).status, 403);
  await db.insert(s.staffPermissions).values({ userId: staff.id, permission: "students.devices.view", grantedBy: owner.id });
  assert.equal((await controller.GET(request(endpoint, staffSession.token), context)).status, 200);
  assert.equal((await controller.POST(request(endpoint, staffSession.token, { action: "end_sessions" }), context)).status, 403);
  pass("editing student profiles does not grant device access; explicit read permission cannot write");
  const rowA = await device("a");
  assert.equal((await controller.POST(request(endpoint, ownerFixture.token, { action: "end_sessions", deviceId: rowA.id, expectedRevision: rowA.policyVersion, reason: "طلب صحيح" }), context)).status, 428);
  assert.ok(await auth.getSessionUser(request("/api/profile", sessionA.token)));
  assert.equal(activeCount instanceof Function, true);
  pass("a valid device change is rejected before mutation without administrative MFA");
  assert.equal((await db.select().from(s.adminMfaFactors).where(and(eq(s.adminMfaFactors.userId, owner.id), isNull(s.adminMfaFactors.disabledAt)))).length, 0, "do not overwrite a pre-existing owner factor");
  const [factor] = await db.insert(s.adminMfaFactors).values({ userId: owner.id, secretEncrypted: mfa.encryptAdminMfaSecret("JBSWY3DPEHPK3PXP"), verifiedAt: now(), label: "Synthetic device policy QA", counter: -1 }).returning();
  ownerFactor = factor.id;
  await db.update(s.authSessions).set({ mfaVerifiedAt: now() }).where(eq(s.authSessions.userId, owner.id));
  const step = mfa.issueVerifiedAdminStepUp(owner, request(endpoint, ownerFixture.token), factor.id);
  const stepHeaders = { cookie: `${auth.SESSION_COOKIE}=${ownerFixture.token}; ${mfa.ADMIN_STEP_UP_COOKIE}=${step.token}` };
  assert.equal((await mutation("a", "end_sessions")).status, 200);
  assert.equal(await activeCount(), 2);
  assert.equal((await device("a")).revokedAt, null);
  assert.equal(await auth.getSessionUser(request("/api/profile", sessionA.token)), null);
  const freshA = await auth.createSession(student.id, login("a"));
  assert.notEqual(freshA.token, sessionA.token);
  pass("ending sessions retains enrollment and requires a new session without consuming another slot");
  assert.equal((await mutation("a", "revoke_block")).status, 200);
  await assert.rejects(auth.createSession(student.id, login("a")), error => error instanceof deviceService.DeviceLimitError && error.code === "DEVICE_RETURN_BLOCKED");
  assert.equal(await auth.getSessionUser(request("/api/profile", freshA.token)), null);
  assert.equal(await activeCount(), 1);
  await auth.createSession(student.id, login("c"));
  assert.equal((await mutation("a", "allow_return")).status, 200);
  assert.notEqual((await device("a")).revokedAt, null);
  assert.equal(await activeCount(), 2);
  await assert.rejects(auth.createSession(student.id, login("a")), error => error instanceof deviceService.DeviceLimitError && error.code === "DEVICE_LIMIT_REACHED");
  pass("allow-return neither restores enrollment nor bypasses the two-device capacity or old revoked credentials");
  assert.equal((await mutation("c", "revoke_block")).status, 200);
  const reentered = await auth.createSession(student.id, login("a"));
  assert.equal((await device("a")).id, rowA.id);
  assert.equal(await activeCount(), 2);
  assert.equal(await auth.getSessionUser(request("/api/profile", freshA.token)), null);
  assert.equal((await auth.getSessionUser(request("/api/profile", reentered.token)))?.id, student.id);
  pass("authorized return reuses the durable device record, not a revoked session; the audit history remains");
  assert.equal((await mutation("a", "block_until", { durationHours: 24 })).status, 200);
  await assert.rejects(auth.createSession(student.id, login("a")), error => error instanceof deviceService.DeviceLimitError && error.code === "DEVICE_TEMPORARILY_BLOCKED");
  await db.update(s.authDevices).set({ blockedUntil: "2000-01-01T00:00:00.000Z" }).where(eq(s.authDevices.id, rowA.id));
  const afterExpiry = await auth.createSession(student.id, login("a"));
  assert.equal(await auth.getSessionUser(request("/api/profile", reentered.token)), null);
  assert.equal((await auth.getSessionUser(request("/api/profile", afterExpiry.token)))?.id, student.id);
  pass("temporary bans enforce the server deadline; expiry permits only a freshly authenticated session");
  assert.equal((await mutation("a", "require_approval")).status, 200);
  await assert.rejects(auth.createSession(student.id, login("a")), error => error instanceof deviceService.DeviceLimitError && error.code === "DEVICE_APPROVAL_REQUIRED");
  assert.equal((await mutation("a", "allow_return")).status, 200);
  const beforeLegacy = await device("a");
  const legacy = await controller.DELETE(request(endpoint, ownerFixture.token, { deviceId: rowA.id, reason: "إعادة محاولة نسخة تطبيق قديمة" }, stepHeaders, "DELETE"), context);
  assert.equal(legacy.status, 200); assert.equal((await legacy.json()).changed, false);
  assert.equal((await device("a")).returnPolicy, "allowed");
  assert.equal((await device("a")).policyVersion, beforeLegacy.policyVersion);
  pass("approval and allowance are distinct; a retried legacy DELETE cannot overwrite newer return permission");
  const outcomes = await Promise.allSettled(Array.from({ length: 8 }, () => auth.createSession(student.id, login("a"))));
  assert.equal(outcomes.filter(result => result.status === "fulfilled").length, 8);
  assert.equal(await activeCount(), 2);
  assert.equal((await rows()).filter(row => row.deviceId === identity("a")).length, 1);
  const activeA = await db.select().from(s.authSessions).where(and(eq(s.authSessions.userId, student.id), eq(s.authSessions.deviceId, identity("a")), isNull(s.authSessions.revokedAt)));
  assert.equal(activeA.length, 1);
  pass("eight concurrent returns consume one enrollment and leave exactly one live session for that device");
  const currentA = await device("a");
  const stale = await mutation("a", "end_sessions", { expectedRevision: currentA.policyVersion - 1 });
  assert.equal(stale.status, 409);
  assert.equal((await device("a")).policyVersion, currentA.policyVersion);
  const strangerContext = { params: Promise.resolve({ email: stranger.email }) };
  assert.equal((await controller.POST(request(`/api/admin/students/${stranger.email}/devices`, ownerFixture.token, { action: "end_sessions", deviceId: rowA.id, expectedRevision: currentA.policyVersion, reason: "معرف لا يتبع الحساب" }, stepHeaders), strangerContext)).status, 404);
  assert.equal((await device("a")).policyVersion, currentA.policyVersion);
  pass("stale revisions and another student's device ID are rejected without mutating the target");
  const maliciousOrigin = await controller.POST(request(endpoint, ownerFixture.token, { action: "end_sessions", deviceId: rowA.id, expectedRevision: currentA.policyVersion, reason: "تجربة مصدر غير موثوق" }, { ...stepHeaders, origin: "https://foreign.example" }), context);
  assert.equal(maliciousOrigin.status, 403);
  const native = await controller.POST(request(endpoint, "", { action: "end_sessions", deviceId: rowA.id, expectedRevision: currentA.policyVersion, reason: "عملية تطبيق مصرح بها" }, { authorization: `Bearer ${ownerFixture.token}`, "x-meras-client": "mobile-v1", "x-meras-platform": "android", "x-meras-mfa-step-up": step.token }), context);
  assert.equal(native.status, 200);
  pass("cross-origin cookie requests fail and the authenticated native bearer plus step-up uses the same controller");
  const response = await controller.GET(request(endpoint, ownerFixture.token), context);
  const data = await response.json();
  assert.ok(data.serverTime); assert.equal(data.deviceLimit, 2);
  assert.doesNotMatch(JSON.stringify(data), /tokenHash|secretEncrypted|passwordHash/);
  assert.equal(JSON.stringify(data).includes(identity("a")), false);
  assert.ok(data.registeredDevices.every((row: { policyVersion: unknown }) => Number.isSafeInteger(row.policyVersion)));
  assert.ok(await auth.getSessionUser(request("/api/profile", sessionB.token)), "unrelated second device remains logged in");
  pass("device snapshots disclose policy and safe metadata, not installation identifiers or authentication secrets");
  const report = { checks, passed: checks.length, database: "isolated loopback PostgreSQL", liveProviders: false, nativeCoverage: "controller protocol, not a physical-device test" };
  writeFileSync(".data/qa-device-return-report.json", JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally {
  if (ownerFactor) await db.delete(s.adminMfaFactors).where(eq(s.adminMfaFactors.id, ownerFactor));
  globalThis.fetch = savedFetch; await closeDb();
}
