/** Dedicated loopback PostgreSQL and synthetic private objects only. */
import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { and, eq, inArray, sql } from "drizzle-orm";
const local = JSON.parse(readFileSync(".data/qa-database.json", "utf8")) as { url: string };
const endpoint = new URL(local.url);
if (endpoint.hostname !== "127.0.0.1" || endpoint.pathname !== "/maras_qa" || process.env.DATABASE_URL !== local.url || resolve(process.env.UPLOAD_DIR || "") !== resolve(".data/uploads")) throw new Error("Dedicated loopback database and isolated files required");
for (const name of ["S3_ENDPOINT", "S3_BUCKET", "S3_ACCESS_KEY_ID", "S3_SECRET_ACCESS_KEY", "GEMINI_API_KEY", "GEMINI_API_KEYS", "RESEND_API_KEY", "TAP_SECRET_KEY", "RAILWAY_PROJECT_ID"]) if (process.env[name]) throw new Error("Live configuration prohibited");
const [{ getDb, closeDb }, core, schema, assignments, upload, adapters, storage] = await Promise.all([import("../db"), import("../db/schema"), import("../db/instructor-schema"), import("../lib/instructor-assignments"), import("../lib/resumable-video-upload"), import("../lib/instructor-assignment-upload"), import("../lib/storage")]);
const db = getDb(), nonce = randomUUID().slice(0, 10), course = "qa-instructor-" + nonce, now = new Date().toISOString();
const checks: string[] = [], userIds: number[] = [], assignmentIds: number[] = [], assetIds: number[] = [], uploadIds: string[] = [], sourceKeys: string[] = [];
const pass = (name: string) => { checks.push(name); console.log("PASS INSTRUCTOR", name); };
const network = globalThis.fetch; globalThis.fetch = async () => { throw new Error("External transport prohibited"); };
let owner = 0, instructor = 0, foreign = 0, contractId = 0, assignmentId = 0, lessonId = 0;
try {
 const [existingOwner] = await db.select({ id: core.users.id }).from(core.users).where(and(eq(core.users.isPlatformOwner, true), eq(core.users.role, "admin"))).limit(1);
 if (!existingOwner) throw new Error("Dedicated QA owner fixture required"); owner = existingOwner.id;
 for (const role of ["instructor", "instructor"]) {
  const [user] = await db.insert(core.users).values({ email: "qa-" + nonce + "-" + userIds.length + "@example.test", fullName: "Synthetic instructor QA", role, status: "active", emailVerifiedAt: now }).returning({ id: core.users.id }); userIds.push(user.id);
 }
 [instructor, foreign] = userIds;
 for (const userId of [instructor, foreign]) await db.insert(schema.instructorProfiles).values({ userId, country: "SA", gender: "male", qualification: "bachelor", specialty: "Synthetic", addressEncrypted: "synthetic-placeholder", status: "approved" });
 const [contract] = await db.insert(schema.instructorContracts).values({ userId: instructor, version: 1, status: "signed", title: "Synthetic test contract", termsAr: "بنود اصطناعية", termsEn: "Synthetic only", compensationModel: "hourly", rateHalalas: 5000, trialTermsAr: "اختبار", trialTermsEn: "test", organizationJson: "{}", instructorJson: "{}", createdBy: owner, contentHash: "a".repeat(64), signatureJson: JSON.stringify({ synthetic: true }), signatureHash: "b".repeat(64), signedAt: now }).returning(); contractId = contract.id;
 await db.insert(core.catalogInstitutions).values({ slug: course, name: course, region: "qa", type: "university" });
 await db.insert(core.catalogSpecialties).values({ slug: course, name: course });
 await db.insert(core.institutionSpecialties).values({ institutionSlug: course, specialtySlug: course });
 await db.insert(core.catalogCourses).values({ slug: course, institutionSlug: course, specialtySlug: course, title: "Synthetic assigned course", status: "published" });
 const [existingUnit] = await db.insert(core.courseUnitsDb).values({ courseSlug: course, title: "Existing live curriculum fixture", position: 4, status: "published" }).returning();
 const existingLessonId = course + "-existing";
 const [existingAsset] = await db.insert(core.videoAssets).values({ courseSlug: course, lessonId: existingLessonId, objectKey: "qa-fixtures/" + course + "/existing.mp4", contentType: "video/mp4", sizeBytes: 16, status: "ready", processingStatus: "ready", durationSeconds: 90, hlsMasterObjectKey: "qa-fixtures/" + course + "/master.m3u8" }).returning(); assetIds.push(existingAsset.id);
 await db.insert(core.lessonsDb).values({ id: existingLessonId, courseSlug: course, unitId: existingUnit.id, title: "Existing fixture lesson", status: "published", videoAssetId: existingAsset.id });
 await assert.rejects(db.transaction(tx => assignments.createInstructorAssignment(tx, owner, { userId: foreign, contractId, courseSlug: course })), { status: 409 });
 const concurrent = await Promise.allSettled([0, 1].map(() => db.transaction(tx => assignments.createInstructorAssignment(tx, owner, { userId: instructor, contractId, courseSlug: course, instructions: "Synthetic QA assignment" }))));
 assert.equal(concurrent.filter(result => result.status === "fulfilled").length, 1); assert.equal(concurrent.filter(result => result.status === "rejected").length, 1);
 assignmentId = (concurrent.find(result => result.status === "fulfilled") as PromiseFulfilledResult<typeof schema.instructorAssignments.$inferSelect>).value.id; assignmentIds.push(assignmentId);
 pass("assignment creation requires matching signed contract and serializes duplicate course assignment");
 await assert.rejects(assignments.authorizedInstructorAssignment(db, assignmentId, foreign), { status: 404 });
 for (const field of ["videoAssetId", "objectKey", "status", "publish"]) await assert.rejects(db.transaction(tx => assignments.editInstructorAssignment(tx, instructor, assignmentId, { action: "saveUnit", title: "Unit", expectedRevision: 1, [field]: "forged" })), { status: 400 });
 const edits = await Promise.allSettled([0, 1].map(() => db.transaction(tx => assignments.editInstructorAssignment(tx, instructor, assignmentId, { action: "saveUnit", title: "Synthetic unit", expectedRevision: 1 }))));
 assert.equal(edits.filter(result => result.status === "fulfilled").length, 1); assert.equal(edits.filter(result => result.status === "rejected").length, 1);
 const unitId = (edits.find(result => result.status === "fulfilled") as PromiseFulfilledResult<{ id: number }>).value.id;
 const lesson = await db.transaction(tx => assignments.editInstructorAssignment(tx, instructor, assignmentId, { action: "saveLesson", unitId, title: "Synthetic instructor lesson", expectedRevision: 2 })); lessonId = lesson.id!;
 assert.equal((await db.select().from(core.lessonsDb).where(eq(core.lessonsDb.courseSlug, course))).length, 1);
 pass("cross-instructor access and client video/status injection are denied; concurrent stale edits cannot overwrite and drafts remain unpublished");
 const bytes = Buffer.from([0, 0, 0, 24, 102, 116, 121, 112, 105, 115, 111, 109, 0, 0, 0, 0]);
 const spec = { ...assignments.instructorVideoNamespace(assignmentId, lessonId), contentType: "video/mp4", sizeBytes: bytes.length, hashes: [createHash("sha256").update(bytes).digest("hex")], requestKey: randomUUID() };
 const authorize = adapters.instructorAssignmentUploadAuthorization(db, instructor, assignmentId), target = adapters.instructorAssignmentUploadTarget(assignmentId, 3);
 const started = await upload.startResumableVideo(db, instructor, spec, authorize, target); uploadIds.push(started.id); sourceKeys.push("private/video-source/" + spec.courseSlug + "/" + spec.lessonId + "/" + started.id + ".upload");
 assert.equal((await assignments.authorizedInstructorAssignment(db, assignmentId, instructor)).revision, 3);
 await assert.rejects(upload.resumableVideoStatus(db, foreign, started.id, adapters.instructorAssignmentUploadAuthorization(db, foreign, assignmentId)), { status: 404 });
 await db.update(schema.instructorProfiles).set({ status: "suspended" }).where(eq(schema.instructorProfiles.userId, instructor));
 await assert.rejects(upload.resumableVideoStatus(db, instructor, started.id, authorize), { status: 403 });
 await db.update(schema.instructorProfiles).set({ status: "approved" }).where(eq(schema.instructorProfiles.userId, instructor));
 await upload.writeResumableVideoPart(db, instructor, started.id, 0, new Request("https://qa.example", { method: "PUT", body: bytes }), authorize);
 await assert.rejects(upload.completeResumableVideo(db, instructor, started.id, authorize, undefined, 0, adapters.instructorAssignmentUploadTarget(assignmentId, 99)), { status: 409 });
 const complete = await upload.completeResumableVideo(db, instructor, started.id, authorize, undefined, 0, target); assetIds.push(complete.asset!.id);
 assert.equal((await upload.completeResumableVideo(db, instructor, started.id, authorize, undefined, 0, target)).reused, true);
 assert.equal((await assignments.authorizedInstructorAssignment(db, assignmentId, instructor)).revision, 4);
 assert.equal((await db.select().from(core.lessonsDb).where(eq(core.lessonsDb.courseSlug, course))).length, 1);
 assert.equal((await db.select().from(schema.instructorLessons).where(eq(schema.instructorLessons.id, lessonId)))[0].videoAssetId, complete.asset!.id);
 pass("private upload checks live contract/account on every chunk, rejects stale completion and links one private asset without touching published lessons");
 await assert.rejects(db.transaction(tx => assignments.editInstructorAssignment(tx, instructor, assignmentId, { action: "submit", expectedRevision: 4 })), { status: 409 });
 const attempt = randomUUID(), prefix = "private/video-derived/" + complete.asset!.id + "/" + attempt;
 await db.update(core.videoAssets).set({ processingStatus: "ready", processingProgress: 100, durationSeconds: 120, hlsMasterObjectKey: prefix + "/master.m3u8", derivativesPrefix: prefix }).where(eq(core.videoAssets.id, complete.asset!.id));
 await db.transaction(tx => assignments.editInstructorAssignment(tx, instructor, assignmentId, { action: "submit", expectedRevision: 4 }));
 await assert.rejects(upload.resumableVideoStatus(db, instructor, started.id, authorize), { status: 409 });
 await assert.rejects(upload.completeResumableVideo(db, instructor, started.id, authorize, undefined, 0, target), { status: 409 });
 await assert.rejects(db.transaction(tx => assignments.editInstructorAssignment(tx, instructor, assignmentId, { action: "deleteLesson", id: lessonId, expectedRevision: 5 })), { status: 409 });
 await db.transaction(tx => assignments.reviewInstructorAssignment(tx, owner, assignmentId, { action: "return_changes", expectedRevision: 5, reason: "Synthetic correction request" }));
 await db.transaction(tx => assignments.editInstructorAssignment(tx, instructor, assignmentId, { action: "submit", expectedRevision: 6 }));
 pass("submission waits for processed HLS and locks old uploads/content until owner returns specific changes");
 const publication = await db.transaction(tx => assignments.reviewInstructorAssignment(tx, owner, assignmentId, { action: "publish", expectedRevision: 7, reason: "Synthetic publication approval" }));
 assert.equal(publication.revision, 8);
 const repeated = await db.transaction(tx => assignments.reviewInstructorAssignment(tx, owner, assignmentId, { action: "publish", expectedRevision: 8, reason: "Synthetic retry of approved publication" })); assert.equal(repeated.reused, true); assert.equal(repeated.revision, 8);
 const publishedLessons = await db.select().from(core.lessonsDb).where(eq(core.lessonsDb.courseSlug, course));
 assert.equal(publishedLessons.length, 2); assert.equal(publishedLessons.find(row => row.id === existingLessonId)?.title, "Existing fixture lesson");
 assert.equal(publishedLessons.find(row => row.videoAssetId === complete.asset!.id)?.status, "published");
 const publishedUnits = await db.select().from(core.courseUnitsDb).where(eq(core.courseUnitsDb.courseSlug, course)); assert.equal(publishedUnits.length, 2); assert.equal(publishedUnits.find(row => row.id !== existingUnit.id)?.position, 5);
 await assert.rejects(assignments.assertDraftAsset(db, await assignments.authorizedInstructorAssignment(db, assignmentId, instructor), lessonId, complete.asset!.id), { status: 409 });
 await assert.rejects(upload.writeResumableVideoPart(db, instructor, started.id, 0, new Request("https://qa.example", { method: "PUT", body: bytes }), authorize), { status: 409 });
 pass("publication rechecks contract, appends reviewed content without altering prior lessons, is idempotent and prevents shared-asset reuse");
 const detail = await assignments.instructorAssignmentDetail(db, await assignments.authorizedInstructorAssignment(db, assignmentId, instructor));
 assert.equal(JSON.stringify(detail).includes("private/video-source"), false); assert.ok(detail.units.every(unit => unit.lessons.every(lesson => lesson.existingVideo && lesson.video === null)));
 pass("published instructor detail marks approved content without private object keys or obsolete draft preview");
 await db.update(schema.instructorContracts).set({ status: "terminated" }).where(eq(schema.instructorContracts.id, contractId));
 await assert.rejects(assignments.authorizedInstructorAssignment(db, assignmentId, instructor), { status: 403 });
 await assert.rejects(db.transaction(tx => assignments.reviewInstructorAssignment(tx, owner, assignmentId, { action: "publish", expectedRevision: 8, reason: "Synthetic revoked contract retry" })), { status: 403 });
 pass("terminated employment contract immediately revokes assigned resources and further publication actions");
 writeFileSync(".data/qa-instructor-assignments-report.json", JSON.stringify({ passed: checks.length, checks, production: false, providers: "dedicated loopback PostgreSQL and local storage", media: "synthetic container header; worker transcoding separately tested" }, null, 2));
} finally {
 globalThis.fetch = network;
 for (const id of uploadIds) await storage.deletePrefix("private/resumable/" + id, "local").catch(() => undefined);
 for (const key of sourceKeys) await storage.deleteObject(key, "local").catch(() => undefined);
 if (assignmentIds.length) await db.delete(schema.instructorAssignments).where(inArray(schema.instructorAssignments.id, assignmentIds));
 await db.delete(core.lessonsDb).where(eq(core.lessonsDb.courseSlug, course));
 if (assetIds.length) await db.delete(core.videoAssets).where(inArray(core.videoAssets.id, assetIds));
 await db.delete(core.courseUnitsDb).where(eq(core.courseUnitsDb.courseSlug, course));
 await db.delete(core.catalogCourses).where(eq(core.catalogCourses.slug, course));
 await db.delete(core.institutionSpecialties).where(eq(core.institutionSpecialties.institutionSlug, course)); await db.delete(core.catalogSpecialties).where(eq(core.catalogSpecialties.slug, course)); await db.delete(core.catalogInstitutions).where(eq(core.catalogInstitutions.slug, course));
 // Immutable evidence is removable only for these synthetic fixtures in the guarded QA database.
 if (contractId) await db.transaction(async tx => { await tx.execute(sql`SET LOCAL session_replication_role = replica`); await tx.delete(schema.instructorContracts).where(and(eq(schema.instructorContracts.id, contractId), eq(schema.instructorContracts.userId, instructor))); });
 if (userIds.length) { await db.delete(schema.instructorProfiles).where(inArray(schema.instructorProfiles.userId, userIds)); await db.delete(core.notificationsDb).where(inArray(core.notificationsDb.targetUserId, userIds)); await db.delete(core.users).where(inArray(core.users.id, userIds)); }
 if (uploadIds.length) await db.delete(core.resumableVideoUploads).where(inArray(core.resumableVideoUploads.id, uploadIds));
 for (const id of assignmentIds) await db.delete(core.notificationsDb).where(sql`${core.notificationsDb.dedupeKey} LIKE ${"instructor-assignment:" + id + ":%"}`);
 if (assignmentIds.length) await db.delete(core.auditLogs).where(and(eq(core.auditLogs.entityType, "instructor_assignment"), inArray(core.auditLogs.entityId, assignmentIds.map(String))));
 if (uploadIds.length) await db.execute(sql`DELETE FROM storage_cleanup_jobs WHERE source LIKE 'resumable-%' AND (${sql.join(uploadIds.map(id => sql`object_key LIKE ${"%" + id + "%"}`), sql` OR `)})`);
 await closeDb();
}
