/** Synthetic integration of curriculum reuse and staff boundaries; loopback only. */
import assert from "node:assert/strict";
import {readFileSync,writeFileSync,mkdirSync} from "node:fs";
import {randomUUID} from "node:crypto";
import {eq,and} from "drizzle-orm";
const local=JSON.parse(readFileSync(".data/qa-database.json","utf8")) as {url:string};
const url=new URL(local.url),origin="http://127.0.0.1:3100";
if(url.hostname!=="127.0.0.1"||url.pathname!=="/maras_qa")throw new Error("Loopback QA database required");
const security=JSON.parse(readFileSync(".data/qa-security.json","utf8"));
Object.assign(process.env,security,{DATABASE_URL:local.url,APP_URL:origin,NEXT_PUBLIC_SITE_URL:origin,NODE_ENV:"development",DATABASE_SSL:"false"});
for(const key of ["RESEND_API_KEY","SMTP_HOST","GEMINI_API_KEY","GOOGLE_API_KEY","GEMINI_API_KEYS","TAP_SECRET_KEY","S3_ENDPOINT","S3_BUCKET","S3_ACCESS_KEY_ID","S3_SECRET_ACCESS_KEY"])delete process.env[key];
const fixtures=JSON.parse(readFileSync(".data/qa-fixtures.json","utf8"));
const owner=fixtures.users.find((user:{role:string})=>user.role==="admin");
assert.ok(owner);
const [{getDb,closeDb},s,i,auth,assignments,uploadAdapter]=await Promise.all([import("../db"),import("../db/schema"),import("../db/instructor-schema"),import("../lib/auth"),import("../lib/instructor-assignments"),import("../lib/instructor-assignment-upload")]);
const db=getDb(),nonce="qa-20260923-"+randomUUID().slice(0,8),now=new Date().toISOString();
const report:{environment:string;checks:{name:string;passed:boolean}[];limitations:string[];syntheticCourse?:string;passed?:number;error?:string}={environment:"local PostgreSQL and HTTP API on 127.0.0.1:3100",checks:[],limitations:["Video assets are synthetic ready metadata; no real encoding or external storage.","A synthetic signed-contract record is seeded for assignment eligibility; document signing is tested separately."]};
const pass=(name:string)=>{report.checks.push({name,passed:true});console.log("PASS "+name);};
const transport=globalThis.fetch;globalThis.fetch=async(input,init)=>{const address=new URL(typeof input==="string"?input:input instanceof URL?input.href:input.url);if(address.origin!==origin)throw new Error("Only QA HTTP transport permitted");return transport(input,init);};
async function call(path:string,token:string,body?:Record<string,unknown>,extra:Record<string,string>={}){const response=await fetch(origin+path,{method:body?"POST":"GET",headers:{origin,"user-agent":"Synthetic instructor integration",...(token?{cookie:"meras_session="+token}:{}),...(body?{"content-type":"application/json"}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();return {status:response.status,data};}
async function account(label:string,role:string){const password=randomUUID()+"Aa1!",email=nonce+"-"+label+"@example.test";const[row]=await db.insert(s.users).values({email,fullName:"Synthetic instructor integration "+label,role,emailVerifiedAt:now,passwordHash:await auth.hashPassword(password),status:"active"}).returning();const request=new Request(origin+"/api/auth/login",{headers:{origin,"x-meras-device-id":"web-"+nonce+"-"+label,"user-agent":"Synthetic integration"}});const session=await auth.createSession(row.id,request);return {row,password,session};}
try{
 const teacher=await account("instructor","instructor"),other=await account("other","instructor"),staff=await account("staff","supervisor");
 for(const person of [teacher,other])await db.insert(i.instructorProfiles).values({userId:person.row.id,country:"SA",gender:"male",qualification:"bachelor",specialty:"Mathematics",addressEncrypted:"synthetic-qa-only",status:"approved"});
 const[contract]=await db.insert(i.instructorContracts).values({userId:teacher.row.id,version:1,status:"signed",title:nonce+" synthetic contract",termsAr:"بيانات اصطناعية للتحقق فقط",termsEn:"Synthetic fixture only",compensationModel:"hourly",rateHalalas:5000,trialDays:30,trialTermsAr:"اختبار اصطناعي",trialTermsEn:"Synthetic assessment",organizationJson:"{}",instructorJson:"{}",contentHash:"a".repeat(64),signatureJson:JSON.stringify({synthetic:true}),signatureHash:"b".repeat(64),signedAt:now,createdBy:owner.id}).returning();
 await db.insert(s.catalogCourses).values({slug:nonce,institutionSlug:fixtures.institution,specialtySlug:"qa-science",title:nonce+" مادة تكامل اصطناعية",status:"draft"});report.syntheticCourse=nonce;
 const[unit]=await db.insert(s.courseUnitsDb).values({courseSlug:nonce,title:"خطة الإدارة",description:"Synthetic existing curriculum",position:3,status:"draft"}).returning();
 const missingId=nonce+"-missing",existingId=nonce+"-existing";
 const[existingAsset]=await db.insert(s.videoAssets).values({courseSlug:nonce,lessonId:existingId,objectKey:nonce+"/existing.mp4",contentType:"video/mp4",sizeBytes:16,status:"ready",processingStatus:"ready",durationSeconds:90,hlsMasterObjectKey:nonce+"/master.m3u8"}).returning();
 await db.insert(s.lessonsDb).values([{id:missingId,courseSlug:nonce,unitId:unit.id,title:"درس يحتاج فيديو",position:0,freePreview:true},{id:existingId,courseSlug:nonce,unitId:unit.id,title:"درس بفيديو الإدارة",position:1,status:"published",videoAssetId:existingAsset.id}]);
 const jobs=await Promise.allSettled([1,2].map(()=>db.transaction(tx=>assignments.createInstructorAssignment(tx,owner.id,{userId:teacher.row.id,contractId:contract.id,courseSlug:nonce}))));
 assert.equal(jobs.filter(result=>result.status==="fulfilled").length,1);assert.equal(jobs.filter(result=>result.status==="rejected").length,1);
 const assignment=(jobs.find(result=>result.status==="fulfilled") as PromiseFulfilledResult<typeof i.instructorAssignments.$inferSelect>).value;
 pass("concurrent assignment creation permits one assignment only");
 const detail=await call("/api/instructor/assignments/"+assignment.id,teacher.session.token);assert.equal(detail.status,200);assert.equal(detail.data.units.length,1);assert.equal(detail.data.units[0].lessons.length,2);
 const draft=detail.data.units[0].lessons.find((lesson:{sourceLessonId:string})=>lesson.sourceLessonId===missingId);const retained=detail.data.units[0].lessons.find((lesson:{sourceLessonId:string})=>lesson.sourceLessonId===existingId);assert.equal(retained.existingVideo,true);assert.equal(retained.video,null);
 const repeated=await call("/api/instructor/assignments/"+assignment.id,teacher.session.token);assert.equal(repeated.data.units.length,1);assert.equal(repeated.data.units[0].lessons.length,2);
 pass("HTTP instructor detail imports complete existing structure once and recognizes retained admin video");
 assert.equal((await call("/api/instructor/assignments/"+assignment.id,other.session.token)).status,404);
 assert.equal((await call("/api/instructor/assignments/"+assignment.id,teacher.session.token,{action:"deleteLesson",id:draft.id,expectedRevision:1})).status,403);
 await assert.rejects(db.transaction(tx=>uploadAdapter.instructorAssignmentUploadTarget(assignment.id,1).assertLesson(tx,teacher.row.id,{...assignments.instructorVideoNamespace(assignment.id,retained.id)} as never)),{status:409});
 pass("foreign instructor access, source curriculum deletion and replacement of existing video are rejected");
 let revision=1;
 const editLesson=await call("/api/instructor/assignments/"+assignment.id,teacher.session.token,{action:"saveLesson",id:retained.id,unitId:detail.data.units[0].id,title:"درس قائم محرر",description:"بيانات معتمدة جديدة",position:7,expectedRevision:revision});assert.equal(editLesson.status,200);revision=editLesson.data.revision;
 const editUnit=await call("/api/instructor/assignments/"+assignment.id,teacher.session.token,{action:"saveUnit",id:detail.data.units[0].id,title:"وحدة محررة",description:"ترتيب معتمد",position:6,expectedRevision:revision});assert.equal(editUnit.status,200);revision=editUnit.data.revision;
 const[asset]=await db.insert(s.videoAssets).values({...assignments.instructorVideoNamespace(assignment.id,draft.id),objectKey:nonce+"/draft.mp4",contentType:"video/mp4",sizeBytes:16,status:"ready",processingStatus:"ready",processingProgress:100,durationSeconds:120,hlsMasterObjectKey:nonce+"/draft/master.m3u8"}).returning();
 await db.update(i.instructorLessons).set({videoAssetId:asset.id}).where(eq(i.instructorLessons.id,draft.id));
 const submit=await call("/api/instructor/assignments/"+assignment.id,teacher.session.token,{action:"submit",expectedRevision:revision});assert.equal(submit.status,200);revision=submit.data.revision;
 await db.update(s.lessonsDb).set({videoAssetId:existingAsset.id}).where(eq(s.lessonsDb.id,missingId));
 await assert.rejects(db.transaction(tx=>assignments.reviewInstructorAssignment(tx,owner.id,assignment.id,{action:"publish",expectedRevision:revision,reason:"Synthetic conflict verification"})),{status:409});
 const[afterConflict]=await db.select().from(i.instructorAssignments).where(eq(i.instructorAssignments.id,assignment.id));assert.equal(afterConflict.status,"submitted");assert.equal(afterConflict.revision,revision);
 pass("concurrent admin video change aborts publication atomically without advancing assignment");
 await db.update(s.lessonsDb).set({videoAssetId:null}).where(eq(s.lessonsDb.id,missingId));
 const published=await db.transaction(tx=>assignments.reviewInstructorAssignment(tx,owner.id,assignment.id,{action:"publish",expectedRevision:revision,reason:"Synthetic verified publication"}));
 const again=await db.transaction(tx=>assignments.reviewInstructorAssignment(tx,owner.id,assignment.id,{action:"publish",expectedRevision:published.revision,reason:"Synthetic idempotent publication"}));assert.equal(again.reused,true);
 const units=await db.select().from(s.courseUnitsDb).where(eq(s.courseUnitsDb.courseSlug,nonce));const lessons=await db.select().from(s.lessonsDb).where(eq(s.lessonsDb.courseSlug,nonce));assert.equal(units.length,1);assert.equal(lessons.length,2);assert.equal(lessons.find(lesson=>lesson.id===missingId)?.videoAssetId,asset.id);assert.equal(lessons.find(lesson=>lesson.id===missingId)?.freePreview,true);assert.equal(lessons.find(lesson=>lesson.id===existingId)?.videoAssetId,existingAsset.id);
 const final=await call("/api/instructor/assignments/"+assignment.id,teacher.session.token);assert.equal(final.status,200);assert.ok(final.data.units[0].lessons.every((lesson:{existingVideo:boolean;video:unknown})=>lesson.existingVideo&&lesson.video===null));
 assert.equal(units[0].position,6);assert.equal(lessons.find(lesson=>lesson.id===existingId)?.title,"درس قائم محرر");assert.equal(lessons.find(lesson=>lesson.id===existingId)?.position,7);
 pass("publication reuses source IDs, applies reviewed metadata and order, preserves existing video and preview flag, and is idempotent");
 await db.insert(s.staffPermissions).values({userId:staff.row.id,permission:"catalog.view",grantedBy:owner.id});
 const login=await call("/api/auth/login","",{identifier:staff.row.email,password:staff.password});assert.equal(login.status,200);assert.equal(login.data.next,"/admin");
 const mobile=await call("/api/mobile/auth/login","",{identifier:staff.row.email,password:staff.password},{"x-meras-client":"mobile-v1","x-meras-platform":"android"});assert.equal(mobile.status,200);assert.equal(mobile.data.next,"/admin");
 pass("delegated staff login returns administration on web and native without student onboarding");
 const me=await call("/api/admin/me",staff.session.token);assert.equal(me.status,200);assert.ok(me.data.permissions.includes("catalog.view"));assert.ok(!me.data.permissions.includes("staff.manage"));
 for(const path of ["/api/admin/finance","/api/admin/staff","/api/admin/instructors/assignments?userId="+teacher.row.id])assert.equal((await call(path,staff.session.token)).status,403);
 const screen=await call("/api/admin/console?view=courses&scope=screen",staff.session.token);assert.equal(screen.status,200);for(const key of ["users","orders","sessions","audit"])assert.deepEqual(screen.data[key]||[],[]);
 assert.equal((await call("/api/admin/console",staff.session.token,{action:"saveUnit",courseSlug:nonce,title:"forbidden"})).status,403);
 await db.delete(s.staffPermissions).where(and(eq(s.staffPermissions.userId,staff.row.id),eq(s.staffPermissions.permission,"catalog.view")));
 assert.equal((await call("/api/admin/console?view=courses&scope=screen",staff.session.token)).status,403);
 pass("live staff grants constrain direct API reads and writes; revocation immediately blocks the same session");
 const ownerLogin=await call("/api/auth/login","",{identifier:owner.email,password:owner.password});assert.equal(ownerLogin.status,200);assert.equal(ownerLogin.data.next,"/admin");pass("platform owner password login returns administration");
 report.passed=report.checks.length;
}catch(error){report.error=error instanceof Error?error.message:"Unknown test failure";throw error;}finally{mkdirSync("output/playwright",{recursive:true});writeFileSync("output/playwright/instructor-integration.json",JSON.stringify(report,null,2));await closeDb();globalThis.fetch=transport;}
