/** Real isolated PostgreSQL, auth, immutable evidence and rendering. No live accounts/providers. */
import assert from 'node:assert/strict';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { eq, sql } from 'drizzle-orm';
const local=JSON.parse(readFileSync('.data/qa-database.json','utf8')) as {url:string};
const parsed=new URL(local.url);
if(parsed.hostname!=='127.0.0.1'||parsed.pathname!=='/maras_qa'||process.env.DATABASE_URL&&process.env.DATABASE_URL!==local.url)throw new Error('Exact loopback QA database required');
for(const key of ['RAILWAY_PROJECT_ID','RAILWAY_ENVIRONMENT_ID','S3_BUCKET','RESEND_API_KEY','TAP_SECRET_KEY','GEMINI_API_KEY'])if(process.env[key])throw new Error('Live configuration prohibited');
const security=existsSync('.data/qa-security.json')?JSON.parse(readFileSync('.data/qa-security.json','utf8')):{};
for(const key of ['SESSION_SECRET','ADMIN_MFA_ENCRYPTION_KEY','INSTRUCTOR_DATA_ENCRYPTION_KEY'])security[key] ||= randomBytes(32).toString('hex');
writeFileSync('.data/qa-security.json',JSON.stringify(security));
const origin='http://127.0.0.1:3100',nonce=randomUUID(),now=new Date().toISOString();
Object.assign(process.env,security,{DATABASE_URL:local.url,DATABASE_SSL:'false',APP_URL:origin,NEXT_PUBLIC_SITE_URL:origin,AUTO_SEED_CATALOG:'false',UPLOAD_DIR:process.cwd()+'/.data/qa-uploads',MARAS_LOOPBACK_QA:'true',CI:'true',GITHUB_ACTIONS:'true',STUDY_PDF_QA_NO_SANDBOX:'true'});
const [{getDb,closeDb},s,i,auth,mfa,service,template,settings,signRoute,pdfRoute,adminRoute,retention,storage]=await Promise.all([import('../db'),import('../db/schema'),import('../db/instructor-schema'),import('../lib/auth'),import('../lib/admin-mfa'),import('../lib/instructor-contracts'),import('../lib/instructor-contract-template'),import('../lib/platform-settings'),import('../app/api/instructor/contracts/[id]/route'),import('../app/api/instructor/contracts/[id]/download/route'),import('../app/api/admin/instructors/route'),import('../lib/instructor-retention'),import('../lib/storage')]);
const encryption=await import('../lib/instructor-security');
const db=getDb(),checks:string[]=[]; const pass=(text:string)=>{checks.push(text);console.log('PASS CONTRACT',text)};
const savedFetch=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('External provider requests forbidden in contract QA')};
const fixtures=JSON.parse(readFileSync('.data/qa-fixtures.json','utf8'));
function request(path:string,token='',body?:unknown,stepUp=''){return new Request(origin+path,{method:body?'POST':'GET',headers:{origin,cookie:`${auth.SESSION_COOKIE}=${token}; ${mfa.ADMIN_STEP_UP_COOKIE}=${stepUp}`,'user-agent':'Maras isolated contract QA','x-meras-device-id':'qa-contract-'+nonce,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})})}
const context=(id:number)=>({params:Promise.resolve({id:String(id)})});
async function account(label:string){const password=randomBytes(16).toString('hex')+'Qa1!';const [row]=await db.insert(s.users).values({email:`qa-contract-${nonce}-${label}@example.test`,fullName:'شارح اختبار اصطناعي '+label,passwordHash:await auth.hashPassword(password),phone:'+9665'+String(randomBytes(4).readUInt32BE()%100000000).padStart(8,'0'),role:'instructor',emailVerifiedAt:now}).returning();await db.insert(i.instructorProfiles).values({userId:row.id,country:'SA',gender:'male',qualification:'bachelor',specialty:'الفيزياء',addressEncrypted:encryption.encryptInstructorData('عنوان اختبار محلي للشارح',`address:${row.id}`),status:'approved'});const session=await auth.createSession(row.id,request('/api/auth/login'));const user=await auth.getSessionUser(request('/instructor',session.token));assert.ok(user);return {row,password,session,user};}
try{
 const ownerFixture=fixtures.users.find((u:{role:string})=>u.role==='admin');const owner=await auth.getSessionUser(request('/admin',ownerFixture.token));assert.ok(owner?.isPlatformOwner);
 for(const [key,value] of Object.entries({legal_name:'منشأة مراس للاختبار المحلي فقط',legal_address:'عنوان اصطناعي للمنشأة',commercial_registration_number:'QA-CR-ONLY',vat_number:'QA-VAT-ONLY',employment_authorization_number:'QA-RECORD-ONLY'}))await db.insert(s.platformSettings).values({key,value,isPublic:true}).onConflictDoUpdate({target:s.platformSettings.key,set:{value,isPublic:true}});
 settings.invalidatePublicSettingsCache();
 const alice=await account('alice'),bob=await account('bob');
 const employment={startDate:'2026-10-01',endDate:'',workLocation:'العمل عن بعد',weeklyHours:20,nationality:'السعودية',paymentTermsAr:'الدفع شهرياً وفق سجل الساعات المعتمدة.',paymentTermsEn:'Monthly payment against an approved record of teaching hours.',benefitsAr:'كامل المزايا والحقوق النظامية المقررة.',benefitsEn:'All applicable statutory employment benefits and rights.'};
 const payload={...template.INSTRUCTOR_CONTRACT_TEMPLATE,action:'save',userId:alice.row.id,compensationModel:'hourly',rateHalalas:5000,trialDays:30,employment};
 let contract=await service.mutateInstructorContract(owner,request('/admin',ownerFixture.token),payload);
 assert.equal(contract.status,'draft');assert.equal((await service.listInstructorContracts(alice.row.id,false)).length,0);
 await assert.rejects(service.mutateInstructorContract(owner,request('/admin'),{...payload,id:contract.id,expectedRevision:99}),{status:409});
 assert.throws(()=>service.validateEmploymentOffer({...employment,startDate:'2026-99-99'}),{status:400});
 contract=await service.mutateInstructorContract(owner,request('/admin'),{action:'offer',userId:alice.row.id,id:contract.id,expectedRevision:contract.revision});
 assert.equal(contract.status,'offered');assert.match(contract.contentHash||'',/^[a-f0-9]{64}$/);
 await assert.rejects(db.update(i.instructorContracts).set({termsAr:'Tampered'}).where(eq(i.instructorContracts.id,contract.id)));
 pass('draft visibility, stale writes, invalid employment dates and database-level offered-term changes are rejected');
 const signature=[Array.from({length:24},(_,x)=>({x:.1+x/30,y:.45+Math.sin(x)*.2}))];
 const body={accepted:true,expectedRevision:contract.revision,contentHash:contract.contentHash,signature,password:alice.password};
 assert.equal((await signRoute.POST(request('/api/instructor/contracts/'+contract.id,bob.session.token,{...body,password:bob.password}),context(contract.id))).status,409);
 assert.equal((await signRoute.POST(request('/api/instructor/contracts/'+contract.id,alice.session.token,{...body,password:'wrong'}),context(contract.id))).status,403);
 assert.equal((await signRoute.POST(request('/api/instructor/contracts/'+contract.id,alice.session.token,{...body,contentHash:'b'.repeat(64)}),context(contract.id))).status,409);
 const replies=await Promise.all([signRoute.POST(request('/api/instructor/contracts/'+contract.id,alice.session.token,body),context(contract.id)),signRoute.POST(request('/api/instructor/contracts/'+contract.id,alice.session.token,body),context(contract.id))]);
 assert.deepEqual(replies.map(r=>r.status).sort(),[200,409]);
 const success=await replies.find(r=>r.status===200)!.json();contract=success.contract;
 assert.equal(contract.status,'signed');assert.equal((await db.select().from(s.auditLogs).where(sql`${s.auditLogs.action}='instructor.contract.signed' AND ${s.auditLogs.entityId}=${String(contract.id)}`)).length,1);
 await assert.rejects(db.delete(i.instructorContracts).where(eq(i.instructorContracts.id,contract.id)));
 await assert.rejects(db.update(i.instructorContracts).set({signatureJson:'[]'}).where(eq(i.instructorContracts.id,contract.id)));
 pass('real authenticated signing checks ownership, password, exact terms and races; only one signature event commits and signed evidence cannot be altered or deleted');
 assert.equal((await pdfRoute.GET(request('/api/instructor/contracts/'+contract.id+'/download',bob.session.token),context(contract.id))).status,404);
 assert.equal((await pdfRoute.GET(request('/api/instructor/contracts/'+contract.id+'/download'),context(contract.id))).status,401);
 const pdf=await pdfRoute.GET(request('/api/instructor/contracts/'+contract.id+'/download',alice.session.token),context(contract.id));
 if(pdf.status!==200)throw new Error('PDF response '+pdf.status+' '+await pdf.text());
 const bytes=Buffer.from(await pdf.arrayBuffer());assert.match(bytes.subarray(0,8).toString(),/^%PDF-/);assert.equal(pdf.headers.get('cache-control'),'private, no-store');mkdirSync('.data/instructor-qa',{recursive:true});writeFileSync('.data/instructor-qa/signed-contract.pdf',bytes);
 pass('real Chromium produces a private downloadable bilingual signed PDF; other accounts and unauthenticated users cannot retrieve it');
 const adminDetails=await adminRoute.GET(request('/api/admin/instructors?userId='+alice.row.id,ownerFixture.token));assert.equal(adminDetails.status,428);
 assert.equal((await adminRoute.GET(request('/api/admin/instructors',alice.session.token))).status,403);
 const [factor]=await db.insert(s.adminMfaFactors).values({userId:owner.id,type:'totp',label:'Isolated QA',secretEncrypted:mfa.encryptAdminMfaSecret('JBSWY3DPEHPK3PXP'),verifiedAt:now,counter:0}).returning();
 await db.update(s.authSessions).set({mfaVerifiedAt:now}).where(eq(s.authSessions.tokenHash,createHash("sha256").update(ownerFixture.token).digest("hex")));
 const step=mfa.issueVerifiedAdminStepUp(owner,request('/admin',ownerFixture.token),factor.id);
 assert.equal((await adminRoute.GET(request('/api/admin/instructors?userId='+alice.row.id,ownerFixture.token,undefined,step.token))).status,200);
 pass('sensitive administration requires session-bound additional authentication');
 // Delegation is exercised with real session-bound grants, not a mocked role.
 const adminPdfRoute=await import('../app/api/admin/instructors/contracts/[id]/download/route');
 const adminContractsRoute=await import('../app/api/admin/instructors/contracts/route');
 const coursePickerRoute=await import('../app/api/admin/instructors/courses/route');
 const adminPdf=await adminPdfRoute.GET(request('/api/admin/instructors/contracts/'+contract.id+'/download',ownerFixture.token,undefined,step.token),context(contract.id));
 assert.equal(adminPdf.status,200);assert.match(Buffer.from(await adminPdf.arrayBuffer()).subarray(0,8).toString(),/^%PDF-/);
 pass('the administrator download endpoint returns the same signed private PDF with valid step-up');
 async function delegated(label:string,permission:string){
  const [row]=await db.insert(s.users).values({email:`qa-instructor-${nonce}-${label}@example.test`,fullName:'مشرف فريق اختبار '+label,passwordHash:await auth.hashPassword(randomBytes(18).toString('hex')+'Qa1!'),role:'supervisor',emailVerifiedAt:now}).returning();
  await db.insert(s.staffPermissions).values({userId:row.id,permission,grantedBy:owner!.id});
  const session=await auth.createSession(row.id,request('/api/auth/login'));
  const user=await auth.getSessionUser(request('/admin',session.token));assert.ok(user);
  const [mfaFactor]=await db.insert(s.adminMfaFactors).values({userId:row.id,type:'totp',label:'Team capability QA',secretEncrypted:mfa.encryptAdminMfaSecret('JBSWY3DPEHPK3PXP'),verifiedAt:now,counter:0}).returning();
  await db.update(s.authSessions).set({mfaVerifiedAt:now}).where(eq(s.authSessions.tokenHash,createHash('sha256').update(session.token).digest('hex')));
  const proof=mfa.issueVerifiedAdminStepUp(user,request('/admin',session.token),mfaFactor.id);
  return {id:row.id,token:session.token,stepUp:proof.token};
 }
 const viewer=await delegated('viewer','instructors.view'),manager=await delegated('manager','instructors.manage');
 assert.equal((await adminRoute.GET(request('/api/admin/instructors',viewer.token))).status,200);
 assert.equal((await adminContractsRoute.GET(request('/api/admin/instructors/contracts?userId='+alice.row.id,viewer.token))).status,428);
 assert.equal((await adminContractsRoute.GET(request('/api/admin/instructors/contracts?userId='+alice.row.id,viewer.token,undefined,viewer.stepUp))).status,200);
 assert.equal((await coursePickerRoute.GET(request('/api/admin/instructors/courses',viewer.token))).status,200);
 assert.equal((await adminContractsRoute.POST(request('/api/admin/instructors/contracts',viewer.token,payload,viewer.stepUp))).status,403);
 assert.equal((await adminRoute.POST(request('/api/admin/instructors',viewer.token,{action:'suspend',userId:alice.row.id,expectedRevision:1,reason:'Read-only must not write'},viewer.stepUp))).status,403);
 const viewerPdf=await adminPdfRoute.GET(request('/api/admin/instructors/contracts/'+contract.id+'/download',viewer.token,undefined,viewer.stepUp),context(contract.id));
 assert.equal(viewerPdf.status,200);assert.match(Buffer.from(await viewerPdf.arrayBuffer()).subarray(0,8).toString(),/^%PDF-/);
 assert.equal((await adminContractsRoute.POST(request('/api/admin/instructors/contracts',manager.token,payload))).status,428);
 assert.equal((await adminContractsRoute.POST(request('/api/admin/instructors/contracts',manager.token,payload,manager.stepUp))).status,200);
 for(const actor of [viewer,manager])for(const path of ['/api/admin/staff','/api/admin/finance','/api/admin/course-resources'])assert.equal(await auth.getSessionUser(request(path,actor.token)),null);
 await db.delete(s.staffPermissions).where(eq(s.staffPermissions.userId,viewer.id));
 assert.equal((await adminRoute.GET(request('/api/admin/instructors',viewer.token))).status,403);
 await db.insert(s.staffPermissions).values({userId:viewer.id,permission:'instructors.view',grantedBy:owner.id});
 fixtures.instructorTeamViewer=viewer;fixtures.instructorTeamManager=manager;
 pass('real delegated viewer reads and downloads with MFA but cannot write; manager saves drafts only with MFA, revocation is immediate, unrelated staff/finance/catalog remain denied');

 const key=`instructors/${bob.row.id}/documents/${randomUUID()}.enc`;
 await storage.putObject(key,new Response('synthetic-expired-ciphertext').body!,'application/octet-stream','local');
 const [doc]=await db.insert(i.instructorDocuments).values({userId:bob.row.id,kind:'passport',objectKey:key,storageProvider:'local',originalName:'synthetic-expired.pdf',contentType:'application/pdf',sizeBytes:20,sha256:'a'.repeat(64),scanStatus:'clean',expiresAt:'2001-01-01T00:00:00.000Z',identityLegalBasis:'Synthetic isolated retention test only'}).returning();
 await retention.expireInstructorDocuments(db);assert.equal((await db.select().from(i.instructorDocuments).where(eq(i.instructorDocuments.id,doc.id))).length,0);assert.equal((await db.select().from(s.storageCleanupJobs).where(eq(s.storageCleanupJobs.objectKey,key))).length,1);
 pass('expired identity copies are removed transactionally and physical deletion is persisted for retry');
 await db.update(s.users).set({status:'suspended'}).where(eq(s.users.id,alice.row.id));
 assert.equal((await pdfRoute.GET(request('/api/instructor/contracts/'+contract.id+'/download',alice.session.token),context(contract.id))).status,401);
 const terminated=await service.mutateInstructorContract(owner,request('/admin'),{action:'terminate',userId:alice.row.id,id:contract.id,expectedRevision:contract.revision,reason:'إنهاء تجريبي لحساب موقوف'});assert.equal(terminated.status,'terminated');
 await db.update(s.users).set({status:'active'}).where(eq(s.users.id,alice.row.id));
 const uiContract=await service.mutateInstructorContract(owner,request('/admin'),payload);
 await service.mutateInstructorContract(owner,request('/admin'),{action:'offer',userId:alice.row.id,id:uiContract.id,expectedRevision:uiContract.revision});
 pass('suspension immediately removes contract access while the owner can record termination without changing signed evidence');
 fixtures.instructor={id:alice.row.id,email:alice.row.email,password:alice.password,token:alice.session.token,deviceId:alice.session.deviceId,offeredContractId:uiContract.id,signedContractId:contract.id};fixtures.instructorOther={id:bob.row.id,email:bob.row.email,password:bob.password,token:bob.session.token};fixtures.adminStepUp=step.token;writeFileSync('.data/qa-fixtures.json',JSON.stringify(fixtures));
 writeFileSync('verification/instructor-contracts-local.json',JSON.stringify({ok:true,at:new Date().toISOString(),checks,pdfBytes:bytes.length},null,2));
}finally{globalThis.fetch=savedFetch;await closeDb()}
