/** Real database/controller checks against loopback maras_qa only. No live providers. */
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { randomBytes, randomUUID } from "node:crypto";
import { and, eq, isNull } from "drizzle-orm";
const local = JSON.parse(readFileSync(".data/qa-database.json", "utf8")) as { url: string };
const parsed = new URL(local.url);
if (parsed.hostname !== "127.0.0.1" || parsed.pathname !== "/maras_qa") throw new Error("Dedicated loopback maras_qa database required");
if (process.env.DATABASE_URL && process.env.DATABASE_URL !== local.url) throw new Error("Refusing another database");
if (process.env.S3_BUCKET || process.env.BUCKET || process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEYS || process.env.RESEND_API_KEY || process.env.TAP_SECRET_KEY) throw new Error("No live credentials permitted");
const origin = "https://maras-qa.example";
Object.assign(process.env, { DATABASE_URL: local.url, DATABASE_SSL: "false", APP_URL: origin, NEXT_PUBLIC_SITE_URL: origin, UPLOAD_DIR: `${process.cwd()}/.data/uploads`, SESSION_SECRET: randomBytes(40).toString("hex"), ADMIN_MFA_ENCRYPTION_KEY: randomBytes(32).toString("hex"), REFERRAL_HASH_SALT: randomBytes(32).toString("hex"), AUTO_SEED_CATALOG: "false", RUN_DB_MIGRATIONS: "false" });
const [{ getDb, closeDb }, s, auth, mfa, account, staff, resourceApi, loginApi, mobileLogin, mfaApi, mobileMfaApi, accountApi, referralsApi, referralRedirect, ref, registerApi, storage] = await Promise.all([
  import("../db"), import("../db/schema"), import("../lib/auth"), import("../lib/admin-mfa"), import("../lib/account-mfa"),
  import("../app/api/admin/staff/route"), import("../app/api/admin/course-resources/route"), import("../app/api/auth/login/route"), import("../app/api/mobile/auth/login/route"),
  import("../app/api/auth/mfa/route"), import("../app/api/mobile/auth/mfa/route"), import("../app/api/account/mfa/route"), import("../app/api/referrals/route"), import("../app/r/[code]/route"), import("../lib/referrals"), import("../app/api/auth/register/route"), import("../lib/storage"),
]);
const db = getDb(); const now = new Date().toISOString(); const nonce = randomUUID().slice(0, 8);
const fixture = JSON.parse(readFileSync(".data/qa-fixtures.json", "utf8")) as { users: { id: number; role: string; token: string; deviceId: string; email: string }[] };
const ownerFixture = fixture.users.find(u => u.role === "admin")!;
const [ownerRow] = await db.select().from(s.users).where(eq(s.users.id, ownerFixture.id));
const owner = auth.sessionUserFromRow(ownerRow);
assert.equal(owner.isPlatformOwner, true);
const password = `${randomBytes(18).toString("base64url")}Aa1!`;
const passwordHash = await auth.hashPassword(password);
const userIds: number[] = [];
async function makeUser(label: string, role = "student") {
  const [row] = await db.insert(s.users).values({ email: `qa-sec-${nonce}-${label}@example.test`, fullName: `حساب اختبار ${label}`, role, passwordHash, universitySlug: "qa-university", specialty: "علوم الاختبار", academicLevel: "المستوى الأول", emailVerifiedAt: now, profileCompletedAt: now, onboardingCompletedAt: now }).returning();
  userIds.push(row.id); return auth.sessionUserFromRow(row);
}
function req(path: string, token = "", body?: unknown, extras: Record<string, string> = {}, method?: string) {
  return new Request(origin + path, { method: method || (body === undefined ? "GET" : "POST"), headers: { origin, "user-agent": "Maras-isolated-QA", "x-meras-device-id": `qa-device-${nonce}`, ...(token ? { cookie: `${auth.SESSION_COOKIE}=${token}` } : {}), ...(body === undefined ? {} : { "content-type": "application/json" }), ...extras }, body: body === undefined ? undefined : JSON.stringify(body) });
}
const nativeHeaders = { "x-meras-client": "mobile-v1", "x-meras-platform": "android" };
const checks: string[] = [];
function pass(message: string) { checks.push(message); console.log(`PASS ${message}`); }
async function expectCode(run: Promise<unknown>, code: string) { await assert.rejects(run, error => (error as { code?: string }).code === code); }
const savedFetch = globalThis.fetch;
globalThis.fetch = async () => { throw new Error("Live network calls are disabled in security QA"); };
let ownerFactorId: number | null = null;
try {
  const a = await makeUser("mfa"), staffUser = await makeUser("staff", "supervisor"), blocked = await makeUser("blocked", "supervisor"), referrer = await makeUser("referrer");
  const enrollmentRequest = req("/api/account/mfa");
  const first = await auth.createSession(a.id, enrollmentRequest);
  const second = await auth.createSession(a.id, req("/api/auth/login", "", undefined, { "x-meras-device-id": `qa-second-${nonce}` }));
  const signed = req("/api/account/mfa", first.token);
  const setupResponse = await accountApi.POST(req("/api/account/mfa", first.token, { action: "setup", password }));
  assert.equal(setupResponse.status, 200); const setup = await setupResponse.json() as { secret: string };
  const counter = Math.floor(Date.now() / 30_000);
  const enable = await accountApi.POST(req("/api/account/mfa", first.token, { action: "verify", password, code: mfa.totpCodeForCounter(setup.secret, counter - 1) }));
  assert.equal(enable.status, 200); const enabled = await enable.json() as { recoveryCodes: string[] };
  assert.equal(enabled.recoveryCodes.length, 10);
  const storedCodes = await db.select().from(s.accountMfaRecoveryCodes).where(eq(s.accountMfaRecoveryCodes.userId, a.id));
  assert.ok(storedCodes.every(row => /^[a-f0-9]{64}$/.test(row.codeHash) && !enabled.recoveryCodes.includes(row.codeHash)));
  const [factor] = await db.select().from(s.adminMfaFactors).where(and(eq(s.adminMfaFactors.userId, a.id), isNull(s.adminMfaFactors.disabledAt)));
  assert.notEqual(factor.secretEncrypted, setup.secret); assert.equal(mfa.decryptAdminMfaSecret(factor.secretEncrypted!), setup.secret);
  assert.equal((await auth.getSessionUser(signed))?.id, a.id);
  assert.equal(await auth.getSessionUser(req("/api/profile", second.token)), null);
  pass("student MFA enrollment encrypts the factor, hashes 10 recovery codes and revokes other sessions atomically");
  await expectCode(auth.createSession(a.id, enrollmentRequest), "MFA_LOGIN_REQUIRED");
  pass("no alternate createSession caller can bypass an enabled factor");
  const primary = await loginApi.POST(req("/api/auth/login", "", { identifier: a.email, password }));
  assert.equal(primary.status, 200); assert.equal((await primary.json()).mfaRequired, true); assert.ok(!primary.headers.get("set-cookie")?.includes("meras_session="));
  pass("web password login issues only a short-lived MFA challenge, not a session");
  const mobilePrimary = await mobileLogin.POST(req("/api/mobile/auth/login", "", { identifier: a.email, password }, nativeHeaders));
  const mp = await mobilePrimary.json(); assert.equal(mp.mfaRequired, true); assert.equal(mp.token, undefined);
  const validCode = mfa.totpCodeForCounter(setup.secret, counter);
  const wrongCode = validCode === "000000" ? "999999" : "000000";
  await expectCode(auth.createSession(a.id, enrollmentRequest, true, { challengeToken: mp.challengeToken, code: wrongCode }), "MFA_CODE_INVALID");
  await expectCode(auth.createSession(a.id, req("/api/auth/mfa", "", undefined, { "x-meras-device-id": `qa-foreign-${nonce}` }), true, { challengeToken: mp.challengeToken, code: validCode }), "MFA_CHALLENGE_INVALID");
  await expectCode(auth.createSession(a.id, enrollmentRequest, false, { challengeToken: mp.challengeToken, code: validCode }), "MFA_CHALLENGE_INVALID");
  pass("wrong OTP, a different device and a changed remember flag cannot consume the challenge");
  const nativeVerified = await mobileMfaApi.POST(req("/api/mobile/auth/mfa", "", { challengeToken: mp.challengeToken, code: validCode }, nativeHeaders));
  assert.equal(nativeVerified.status, 200); const nativeResult = await nativeVerified.json(); assert.equal(typeof nativeResult.token, "string"); assert.ok(!nativeVerified.headers.has("set-cookie"));
  assert.equal((await auth.getSessionUser(req("/api/profile", nativeResult.token)))?.id, a.id);
  await expectCode(auth.createSession(a.id, enrollmentRequest, true, { challengeToken: mp.challengeToken, code: validCode }), "MFA_CHALLENGE_INVALID");
  const replay = await account.beginLoginMfa(a.id, enrollmentRequest);
  await expectCode(auth.createSession(a.id, enrollmentRequest, true, { challengeToken: replay!.challengeToken, code: validCode }), "MFA_CODE_INVALID");
  pass("native MFA returns a usable bearer only after proof; used challenges and OTP counters cannot replay");
  const recoveryAttempt = await account.beginLoginMfa(a.id, enrollmentRequest);
  const raced = await Promise.allSettled(Array.from({ length: 8 }, () => auth.createSession(a.id, enrollmentRequest, true, { challengeToken: recoveryAttempt!.challengeToken, code: enabled.recoveryCodes[0] })));
  assert.equal(raced.filter(r => r.status === "fulfilled").length, 1);
  const recovered = (raced.find(r => r.status === "fulfilled") as PromiseFulfilledResult<Awaited<ReturnType<typeof auth.createSession>>>).value;
  const another = await account.beginLoginMfa(a.id, enrollmentRequest);
  await expectCode(auth.createSession(a.id, enrollmentRequest, true, { challengeToken: another!.challengeToken, code: enabled.recoveryCodes[0] }), "MFA_CODE_INVALID");
  pass("eight concurrent recovery submissions create one session and consume the recovery code once");
  const expired = await account.beginLoginMfa(a.id, enrollmentRequest);
  await db.update(s.accountMfaChallenges).set({ expiresAt: "2000-01-01T00:00:00.000Z" }).where(eq(s.accountMfaChallenges.tokenHash, await auth.hashOpaqueToken(expired!.challengeToken)));
  await expectCode(auth.createSession(a.id, enrollmentRequest, true, { challengeToken: expired!.challengeToken, code: enabled.recoveryCodes[1] }), "MFA_CHALLENGE_INVALID");
  const webChallenge = await account.beginLoginMfa(a.id, enrollmentRequest);
  const webVerified = await mfaApi.POST(req("/api/auth/mfa", "", { code: enabled.recoveryCodes[1] }, { cookie: `${account.MFA_CHALLENGE_COOKIE}=${webChallenge!.challengeToken}` }));
  assert.equal(webVerified.status, 200); assert.equal((await webVerified.json()).token, undefined); assert.match(webVerified.headers.get("set-cookie")!, /meras_session=/);
  assert.equal((await mobileMfaApi.POST(req("/api/mobile/auth/mfa", "", {}))).status, 403);
  pass("expired challenges fail; web MFA uses HttpOnly cookies and the native endpoint requires the app protocol");
  // Explicitly reset ONLY the synthetic counter to exercise rollback without waiting 30s.
  await db.update(s.adminMfaFactors).set({ counter: counter - 1 }).where(eq(s.adminMfaFactors.id, factor.id));
  const beforeCodes = await account.accountMfaStatus(a.id);
  await expectCode(account.changeAccountMfa(a, req("/api/account/mfa", recovered.token), validCode, "disable"), "SESSION_REQUIRED");
  const [stillEnabled] = await db.select().from(s.adminMfaFactors).where(eq(s.adminMfaFactors.id, factor.id));
  assert.equal(stillEnabled.disabledAt, null); assert.equal(stillEnabled.counter, counter - 1);
  assert.deepEqual(await account.accountMfaStatus(a.id), beforeCodes);
  pass("a revoked session rolls back factor changes, counters and recovery-code updates");
  const ss = await auth.createSession(staffUser.id, req("/api/auth/login"));
  const bs = await auth.createSession(blocked.id, req("/api/auth/login"));
  assert.equal(await auth.getSessionUser(req("/api/admin/course-resources", bs.token)), null);
  await db.insert(s.staffPermissions).values([{ userId: staffUser.id, permission: "catalog.view", grantedBy: owner.id }, { userId: staffUser.id, permission: "students.view", grantedBy: owner.id }]);
  assert.equal((await auth.getSessionUser(req("/api/admin/course-resources", ss.token)))?.id, staffUser.id);
  for (const path of ["/api/admin/staff", "/api/admin/finance", "/api/admin/videos/direct", "/api/admin/unknown-area"]) assert.equal(await auth.getSessionUser(req(path, ss.token)), null, path);
  assert.equal((await staff.POST(req("/api/admin/staff", ss.token, { action: "activate", id: owner.id }))).status, 403);
  pass("supervisors are default-deny; view grants cannot sign uploads, read finance, manage staff or access unknown routes");
  await assert.rejects(db.update(s.users).set({ role: "supervisor", isPlatformOwner: false }).where(eq(s.users.id, owner.id)));
  await assert.rejects(db.update(s.users).set({ status: "suspended" }).where(eq(s.users.id, owner.id)));
  await assert.rejects(db.delete(s.users).where(eq(s.users.id, owner.id)));
  await assert.rejects(db.update(s.users).set({ isPlatformOwner: true, role: "admin" }).where(eq(s.users.id, staffUser.id)));
  pass("database constraints independently reject owner deletion, suspension, demotion and a second owner");
  const [of] = await db.insert(s.adminMfaFactors).values({ userId: owner.id, secretEncrypted: mfa.encryptAdminMfaSecret("JBSWY3DPEHPK3PXP"), counter: -1, verifiedAt: now, label: "Synthetic security QA only" }).returning(); ownerFactorId = of.id;
  await db.update(s.authSessions).set({ mfaVerifiedAt: now }).where(eq(s.authSessions.userId, owner.id));
  const ownerRequest = req("/api/admin/staff", ownerFixture.token);
  const proof = mfa.issueVerifiedAdminStepUp(owner, ownerRequest, of.id);
  const ownerHeaders = { cookie: `${auth.SESSION_COOKIE}=${ownerFixture.token}; ${mfa.ADMIN_STEP_UP_COOKIE}=${proof.token}` };
  const staffMutation = { action: "save", id: staffUser.id, email: staffUser.email, fullName: staffUser.fullName, permissions: ["catalog.manage", "records.delete"] };
  assert.equal((await staff.POST(req("/api/admin/staff", ownerFixture.token, staffMutation))).status, 428);
  assert.equal((await staff.POST(req("/api/admin/staff", ownerFixture.token, { ...staffMutation, permissions: ["staff.manage"] }, ownerHeaders))).status, 400);
  const edited = await staff.POST(req("/api/admin/staff", ownerFixture.token, staffMutation, ownerHeaders)); assert.equal(edited.status, 200);
  assert.equal(await auth.getSessionUser(req("/api/profile", ss.token)), null);
  assert.equal((await staff.POST(req("/api/admin/staff", ownerFixture.token, { ...staffMutation, id: owner.id, email: owner.email }, ownerHeaders))).status, 403);
  pass("owner staff edits require fresh step-up, reject owner-only delegated grants and revoke affected sessions");
  const staffSnapshot = await staff.GET(ownerRequest); const roster = await staffSnapshot.json();
  assert.ok(roster.staff.find((u: { id: number }) => u.id === owner.id)?.isPlatformOwner);
  assert.doesNotMatch(JSON.stringify(roster), /tokenHash|secretEncrypted|passwordHash|credentialId/);
  pass("staff/session oversight exposes safe metadata but no tokens, passwords or MFA secrets");
  const objectKey = `qa-security/${nonce}/lesson.txt`;
  await storage.putObject(objectKey, new Response("synthetic learning resource").body!, "text/plain", "local");
  const [resource] = await db.insert(s.courseResources).values({ courseSlug: "qa-physics", lessonId: "qa-physics-lesson", title: "ملف اختبار الحذف", objectKey, originalName: "lesson.txt", contentType: "text/plain", sizeBytes: 27, studentVisible: true, scanStatus: "clean", status: "active" }).returning();
  const deletePath = `/api/admin/course-resources?id=${resource.id}`;
  assert.equal((await resourceApi.DELETE(req(deletePath, ownerFixture.token, undefined, {}, "DELETE"))).status, 428);
  assert.equal((await db.select().from(s.courseResources).where(eq(s.courseResources.id, resource.id))).length, 1);
  assert.ok(await storage.getObject(objectKey));
  assert.equal((await resourceApi.DELETE(req(deletePath, ownerFixture.token, undefined, ownerHeaders, "DELETE"))).status, 200);
  assert.equal((await db.select().from(s.courseResources).where(eq(s.courseResources.id, resource.id))).length, 0);
  assert.equal(await storage.getObject(objectKey), null);
  pass("file deletion preserves the row/object before MFA and removes both after verified confirmation");
  const refSession = await auth.createSession(referrer.id, req("/api/auth/login"));
  const refData = await (await referralsApi.GET(req("/api/referrals", refSession.token, undefined, { host: "0.0.0.0:8080", "x-forwarded-host": "evil.example" }))).json();
  assert.equal(new URL(refData.referral.shareUrl).origin, origin);
  const redirected = await referralRedirect.GET(new Request("https://0.0.0.0:8080/r/test", { headers: { "x-forwarded-host": "evil.example" } }), { params: Promise.resolve({ code: refData.referral.code }) });
  const target = new URL(redirected.headers.get("location")!); assert.equal(target.origin, origin); assert.equal(target.pathname, "/register"); assert.equal(target.searchParams.get("ref"), refData.referral.code);
  pass("shared referral and redirect retain the code and reject private/host-poisoned origins");
  const registeredEmail = `qa-sec-${nonce}-registered@example.test`;
  const phone = `05${String(parseInt(nonce.replace(/-/g,""),16) % 100_000_000).padStart(8,"0")}`;
  const registered = await registerApi.POST(req("/api/auth/register", "", { fullName: "طالب جديد اختبار الإحالة", email: registeredEmail, phone, password, universitySlug: "qa-university", specialty: "علوم الاختبار", academicLevel: "المستوى الأول", termsAccepted: true }, { cookie: `meras_referral=${refData.referral.code}`, "x-meras-device-id": `qa-ref-register-${nonce}` }));
  assert.equal(registered.status, 201, JSON.stringify(await registered.clone().json()));
  const registeredUser = (await registered.json()).user; userIds.push(registeredUser.id);
  const [attribution] = await db.select().from(s.referralAttributions).where(eq(s.referralAttributions.referredUserId, registeredUser.id));
  assert.equal(attribution.referrerUserId, referrer.id); assert.equal(attribution.status, "pending");
  await Promise.all(Array.from({ length: 8 }, () => db.transaction(tx => ref.recordReferralRegistrationTx(tx, { referralCode: refData.referral.code, referredUserId: registeredUser.id, request: req("/api/auth/register") }))));
  assert.equal((await db.select().from(s.referralAttributions).where(eq(s.referralAttributions.referredUserId, registeredUser.id))).length, 1);
  assert.equal(await db.transaction(tx => ref.recordReferralRegistrationTx(tx, { referralCode: refData.referral.code, referredUserId: referrer.id, request: req("/api/auth/register") })), null);
  pass("real registration attributes the referral cookie once, stays pending before payment and rejects self-referral");
  const audit = await db.select().from(s.auditLogs).where(eq(s.auditLogs.actorEmail, a.email));
  const serializedAudit = JSON.stringify(audit);
  assert.ok(!serializedAudit.includes(setup.secret) && !serializedAudit.includes(password) && enabled.recoveryCodes.every(code => !serializedAudit.includes(code)));
  pass("account security audits record actions without authentication secrets");
  // Keep a non-owner viewer account for browser permission/empty-state checks.
  await db.insert(s.staffPermissions).values({ userId: blocked.id, permission: "catalog.view", grantedBy: owner.id });
  writeFileSync(".data/qa-security-fixtures.json", JSON.stringify({ origin: "http://127.0.0.1:3100", supervisor: { id: blocked.id, email: blocked.email, token: bs.token } }));
  const report = { passed: checks.length, checks, database: "isolated loopback PostgreSQL", liveRequests: 0, deviceCoverage: "controller-level web/native protocol, not physical devices" };
  writeFileSync(".data/qa-security-report.json", JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
} finally {
  if (ownerFactorId) await db.delete(s.adminMfaFactors).where(eq(s.adminMfaFactors.id, ownerFactorId));
  globalThis.fetch = savedFetch; await closeDb();
}
