import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BadgeCheck, BookOpen, CheckCircle2, ChevronLeft, Clock3, FileText, Gift, GraduationCap, Infinity, Languages, LockKeyhole, MessageCircle, PlayCircle, ShieldCheck, Star, UsersRound } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { SecureVideoPlayer } from "@/components/secure-video-player";
import { CourseCard } from "@/components/course-card";
import { CourseReviews } from "@/components/course-reviews";
import { CourseCoverImage } from "@/components/course-cover-image";
import { courses as staticCourses } from "@/lib/data";
import { getCourseCatalog, getCoursesCatalog } from "@/lib/catalog-store";

type Props = { params: Promise<{ slug: string }> };
export const dynamic = "force-dynamic";
export function generateStaticParams() { return staticCourses.map((course) => ({ slug: course.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const course = await getCourseCatalog((await params).slug);
  if (!course) return {};
  const description = `${course.description} شاهد درسًا تجريبيًا مجانيًا قبل الاشتراك.`;
  return { title: course.title, description, openGraph: { title: `${course.title} | مراس العلم`, description, images: [] }, twitter: { title: `${course.title} | مراس العلم`, description, images: [] } };
}

export default async function CoursePage({ params }: Props) {
  const course = await getCourseCatalog((await params).slug);
  if (!course) notFound();
  const courses = await getCoursesCatalog();
  const related = courses.filter((item) => item.slug !== course.slug && (item.specialty === course.specialty || item.universitySlug === course.universitySlug)).slice(0, 3);
  const freeLesson = course.units.flatMap((unit) => unit.lessons).find((lesson) => lesson.free);
  const previewLesson = course.units.flatMap((unit) => unit.lessons).find((lesson) => lesson.free && lesson.ready);
  return <main><SiteHeader />
    <section className="course-detail-hero"><div className="course-detail-glow" /><div className="container"><div className="breadcrumbs breadcrumbs-light"><Link href="/">الرئيسية</Link><ChevronLeft size={13} /><Link href="/courses">المواد</Link><ChevronLeft size={13} /><span>{course.title}</span></div><div className="course-detail-grid"><div className="course-detail-copy"><div className="course-badges"><span><BadgeCheck size={14} /> متوافق مع محتوى المقرر</span>{previewLesson && <span><PlayCircle size={14} /> درس مجاني</span>}</div><h1>{course.title}</h1><p className="course-detail-en">{course.titleEn} {course.code && `· ${course.code}`}</p><p className="course-detail-description">{course.description}</p><div className="course-detail-context"><Link href={`/universities/${course.universitySlug}`}><GraduationCap size={15} /> {course.university}</Link><span><BookOpen size={15} /> {course.specialty}</span></div><div className="course-detail-rating"><span><Star size={17} fill="currentColor" /> {course.rating}</span><u>{course.ratingsCount} تقييمًا</u><i /><span><UsersRound size={17} /> {course.students.toLocaleString("ar-SA")} طالب</span><i /><span><Clock3 size={17} /> {course.duration}</span></div><div className="course-instructor-mini"><span>{course.instructor.replace(/^(د\.|م\.|أ\.)\s*/, "")[0]}</span><div><small>إعداد وشرح</small><strong>{course.instructor}</strong></div><BadgeCheck size={18} /></div></div><div className={`course-detail-art bg-gradient-to-br ${course.color}`}><span className="course-cover-grid" />{course.coverImage ? <CourseCoverImage className="course-detail-image" src={course.coverImage} alt={`غلاف ${course.title}`} sizes="(max-width: 900px) 100vw, 44vw" priority /> : <div>{course.icon}</div>}<small>{course.titleEn}</small><strong>{course.code || "مراس"}</strong></div></div></div></section>
    <section className="course-detail-body"><div className="container course-detail-layout"><div className="course-main-column">
      <section className="course-preview-block" id="preview"><div className="block-title"><div><span className="section-kicker">جرّب قبل الاشتراك</span><h2>الدرس التجريبي المجاني</h2><p>{previewLesson?.title || freeLesson?.title || "سيظهر الدرس بعد رفع الفيديو من الإدارة"}</p></div>{previewLesson && <span className="free-badge"><Gift size={16} /> مجاني بالكامل</span>}</div>{previewLesson ? <SecureVideoPlayer title={previewLesson.title} preview courseSlug={course.slug} lessonId={previewLesson.id} /> : <div className="course-video-unavailable">هذا الدرس جزء من هيكل المادة، ولم يُرفع الفيديو المعتمد بعد.</div>}</section>
      <section className="course-about-block"><h2>ماذا ستتعلّم؟</h2><div className="learning-points"><span><CheckCircle2 size={17} /> فهم أساسيات المادة بصورة مترابطة</span><span><CheckCircle2 size={17} /> حل أمثلة وتمارين من مستوى المقرر</span><span><CheckCircle2 size={17} /> معرفة طريقة التعامل مع أسئلة الاختبارات</span><span><CheckCircle2 size={17} /> مراجعة منظمة توفر وقت المذاكرة</span></div></section>
      <section className="course-curriculum"><div className="curriculum-head"><div><h2>محتويات المادة</h2><p>{course.units.length} وحدات · {course.lessons} درسًا · {course.duration}</p></div><span>عرض جميع الوحدات</span></div>{course.units.map((unit, unitIndex) => <details key={unit.title} open={unitIndex === 0}><summary><span><b>{unitIndex + 1}</b><strong>{unit.title}<small>{unit.lessons.length} دروس</small>{unit.description && <em>{unit.description}</em>}</strong></span><ChevronLeft size={18} /></summary><div className="lessons-list">{unit.lessons.map((lesson, index) => <div key={lesson.id}><span><i>{lesson.type === "pdf" ? <FileText size={16} /> : <PlayCircle size={16} />}</i><strong>{index + 1}. {lesson.title}{lesson.free && lesson.ready && <em>مجاني</em>}{lesson.description && <small>{lesson.description}</small>}</strong></span><span>{lesson.duration}{lesson.free && lesson.ready ? <Link href="#preview">تشغيل</Link> : <LockKeyhole size={14} />}</span></div>)}</div></details>)}</section>
      <section className="instructor-block"><div className="instructor-avatar">{course.instructor.replace(/^(د\.|م\.|أ\.)\s*/, "")[0]}</div><div><span className="section-kicker">إعداد المادة</span><h2>{course.instructor}</h2><p>محتوى جامعي منظم إلى وحدات ودروس، ويخضع للتحديث والإشراف من فريق المنصة.</p><div><span><Star size={15} fill="currentColor" /> {course.ratingsCount ? `${course.rating} من ${course.ratingsCount} تقييم موثّق` : "بانتظار أول تقييم موثّق"}</span><span><UsersRound size={15} /> {course.students} اشتراك فعلي</span><span><PlayCircle size={15} /> {course.lessons} درسًا</span></div></div></section>
      <CourseReviews courseSlug={course.slug} catalogRating={course.rating} catalogCount={course.ratingsCount} />
    </div><aside className="course-purchase-card"><div className="purchase-price"><span>سعر المادة</span><div><strong>{course.price}</strong><b>ر.س</b>{course.oldPrice && <del>{course.oldPrice} ر.س</del>}</div></div>{course.availableForPurchase ? <Link href={`/checkout/${course.slug}`} className="button button-primary purchase-main-button">اشترك الآن <ArrowLeft size={17} /></Link> : <span className="button button-soft purchase-main-button purchase-preparing"><Clock3 size={17} /> قريبًا</span>}{previewLesson && <Link href="#preview" className="button button-ghost purchase-preview-button"><PlayCircle size={17} /> شاهد الدرس المجاني</Link>}<p className="purchase-guarantee"><ShieldCheck size={15} /> {course.availableForPurchase ? "دفع آمن ومشفّر عبر Tap" : "لن يتاح الدفع حتى اكتمال جميع الفيديوهات"}</p><ul><li><Infinity size={16} /><span>الوصول<strong>{course.access}</strong></span></li><li><PlayCircle size={16} /><span>المحتوى<strong>{course.lessons} درسًا منظمًا · {course.readyLessons || 0} جاهز</strong></span></li><li><Languages size={16} /><span>اللغة<strong>العربية مع مصطلحات إنجليزية</strong></span></li><li><MessageCircle size={16} /><span>الدعم<strong>فريق مراس متاح للمساعدة</strong></span></li></ul><small>{course.availableForPurchase ? "بالاشتراك أنت توافق على الشروط وسياسة الاسترداد." : "المادة معروضة للتعريف بمحتواها وستُفتح تلقائيًا بعد تجهيز الفيديوهات."}</small></aside></div></section>
    {related.length > 0 && <section className="section related-courses"><div className="container"><div className="section-head"><div><span className="section-kicker">قد يناسبك أيضًا</span><h2>مواد مرتبطة باهتمامك</h2></div><Link href="/courses" className="button button-ghost">كل المواد <ArrowLeft size={16} /></Link></div><div className="courses-grid">{related.map((item) => <CourseCard key={item.slug} course={item} />)}</div></div></section>}
    <SiteFooter />
  </main>;
}
