"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Bell, BookOpen, CheckCircle2, FileUp, LayoutDashboard, LifeBuoy, LogOut, Play, Receipt, Search, Settings, Sparkles, TrendingUp, UserRound, X } from "lucide-react";
import type { Institution } from "@/lib/data";
import { BrandLogo } from "@/components/brand-logo";
import { useAcademicPrograms } from "@/components/use-academic-programs";
import { AppearanceSettings } from "@/components/theme-provider";
import { useRealtimeSync } from "@/components/realtime-sync";

export type DashboardUser = { id:number; fullName:string; email:string; phone:string; universitySlug:string; specialty:string };
export type DashboardCourse = { slug:string; title:string; university:string; color:string; icon:string; progress:number; current:string; remaining:string };
export type DashboardOrder = { orderNumber:string; courseTitle:string; total:number; currency:string; status:string; createdAt:string };
export type DashboardRequest = { id:number; courseName:string; status:string; attachmentsCount:number; createdAt:string };
export type DashboardNotice = { id:number; title:string; body:string; actionUrl:string | null; actionLabel?:string | null; presentation?:string; createdAt:string; read:boolean };
export type DashboardRecommendation = { slug:string; title:string; university:string; specialty:string; price:number; color:string; icon:string; match:"تخصصك"|"جامعتك"|"تخصص مشابه" };
export type DashboardTicket = { id:number;ticketNumber:string;title:string;category:string;status:string;createdAt:string;replies:Array<{id:number;body:string;createdAt:string}> };

const nav = [
  { id:"overview", label:"نظرة عامة", icon:LayoutDashboard },
  { id:"learning", label:"موادي", icon:BookOpen },
  { id:"requests", label:"طلبات المواد", icon:FileUp },
  { id:"orders", label:"الطلبات والفواتير", icon:Receipt },
  { id:"notifications", label:"الإشعارات", icon:Bell },
  { id:"support", label:"الدعم", icon:LifeBuoy },
  { id:"account", label:"حسابي", icon:Settings },
] as const;
type StudentView = typeof nav[number]["id"];

export function StudentDashboard({ initialView = "overview", user, owned, orders, requests, notices, tickets, institutions, recommended }: { initialView?:string; user:DashboardUser; owned:DashboardCourse[]; orders:DashboardOrder[]; requests:DashboardRequest[]; notices:DashboardNotice[]; tickets:DashboardTicket[]; institutions:Institution[]; recommended:DashboardRecommendation[] }) {
  const [active, setActive] = useState<StudentView>(nav.some((item)=>item.id===initialView)?initialView as StudentView:"overview");
  const [live, setLive] = useState({ user, owned, orders, requests, notices, tickets, institutions, recommended });
  const [noticeRows, setNoticeRows] = useState(notices);
  const [syncing,setSyncing]=useState(false);
  const [syncError,setSyncError]=useState("");
  const refresh = useCallback(async () => {
    setSyncing(true);
    setSyncError("");
    try {
      const response = await fetch("/api/mobile/dashboard", { credentials: "same-origin", cache: "no-store" });
      if (!response.ok) throw new Error("تعذر مزامنة أحدث بيانات حسابك");
      const payload = await response.json() as Partial<typeof live> & { user?: DashboardUser; owned?: DashboardCourse[]; orders?: DashboardOrder[]; requests?: DashboardRequest[]; notifications?: Array<DashboardNotice & { readAt?: string | null }>; tickets?: DashboardTicket[]; institutions?: Institution[]; recommended?: DashboardRecommendation[] };
      const nextNotices = payload.notifications?.map((item) => ({ ...item, read: typeof item.read === "boolean" ? item.read : Boolean(item.readAt) }));
      if (nextNotices) setNoticeRows(nextNotices);
      setLive((current) => ({ user: payload.user || current.user, owned: payload.owned || current.owned, orders: payload.orders || current.orders, requests: payload.requests || current.requests, notices: nextNotices || current.notices, tickets: payload.tickets || current.tickets, institutions: payload.institutions || current.institutions, recommended: payload.recommended || current.recommended }));
    } catch (caught) {
      setSyncError(caught instanceof Error?caught.message:"تعذر مزامنة أحدث البيانات");
    } finally {
      setSyncing(false);
    }
  }, []);
  useRealtimeSync((payload) => {
    if (!payload.changed || payload.changed.some((channel) => ["account", "commerce", "support", "notifications", "requests", "catalog", "settings"].includes(channel))) void refresh();
  });
  const unread = noticeRows.filter((item) => !item.read).length;
  useEffect(() => {
    if (active !== "notifications") return;
    const controller = new AbortController();
    fetch("/api/mobile/notifications", { credentials: "same-origin", cache: "no-store", signal: controller.signal })
      .then(async (response) => response.ok ? await response.json() as { notifications?: Array<{ id: number; title: string; body: string; actionUrl: string | null; createdAt: string; readAt: string | null }> } : null)
      .then((payload) => {
        if (!payload || controller.signal.aborted) return;
        const rows = (payload.notifications || []).map((item) => ({ id: item.id, title: item.title, body: item.body, actionUrl: item.actionUrl, createdAt: item.createdAt, read: Boolean(item.readAt) }));
        setNoticeRows(rows);
        return fetch("/api/mobile/notifications", { method: "PATCH", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ all: true }), signal: controller.signal });
      })
      .then(() => setNoticeRows((rows) => rows.map((item) => ({ ...item, read: true }))))
      .catch(() => undefined);
    return () => controller.abort();
  }, [active]);
  const institution = live.institutions.find((item) => item.slug === live.user.universitySlug);
  let content: React.ReactNode;
  if (active === "overview") content = <Overview user={live.user} owned={live.owned} requests={live.requests} recommended={live.recommended} setActive={setActive} />;
  else if (active === "learning") content = <MyCourses owned={live.owned} />;
  else if (active === "requests") content = <Requests rows={live.requests} />;
  else if (active === "orders") content = <Orders rows={live.orders} />;
  else if (active === "notifications") content = <Notifications rows={noticeRows} onRead={(id) => setNoticeRows((rows) => rows.map((item) => item.id === id ? { ...item, read: true } : item))} />;
  else if (active === "support") content = <Support rows={live.tickets} />;
  else content = <Account user={live.user} institutions={live.institutions} />;
  const logout = async () => { await fetch("/api/auth/logout", { method:"POST" }); window.location.assign("/"); };
  return <div className="student-app" dir="rtl" aria-busy={syncing}><aside className="student-sidebar"><BrandLogo compact/><div className="student-profile-mini"><div>{live.user.fullName[0]}</div><span><strong>{live.user.fullName}</strong><small>{institution?.name || "مراس العلم"}</small></span></div><nav aria-label="أقسام حساب الطالب">{nav.map((item) => { const Icon=item.icon; return <button key={item.id} className={active===item.id?"active":""} onClick={() => setActive(item.id)} aria-current={active===item.id?"page":undefined}><Icon size={18} />{item.label}{item.id==="notifications"&&unread>0&&<i>{unread}</i>}</button>; })}</nav><div className="student-sidebar-help"><LifeBuoy size={21} /><strong>تحتاج مساعدة؟</strong><small>فريق مراس معك</small><button onClick={() => setActive("support")}>تواصل معنا</button></div><button className="student-logout" onClick={logout}><LogOut size={17} /> تسجيل الخروج</button></aside><div className="student-content"><div className="student-mobile-tabs" role="navigation" aria-label="تنقل حساب الطالب">{nav.map((item)=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setActive(item.id)} className={active===item.id?"active":""} aria-current={active===item.id?"page":undefined}><Icon size={18}/><span>{item.label}</span>{item.id==="notifications"&&unread>0&&<i>{unread}</i>}</button>;})}</div>{syncError&&<p className="form-error" role="alert">{syncError} — ستبقى آخر نسخة محفوظة ظاهرة ويمكنك المحاولة مرة أخرى عند عودة الاتصال.</p>}{content}</div></div>;
}

function DashboardTitle({ eyebrow,title,description,action }: {eyebrow?:string;title:string;description?:string;action?:React.ReactNode}) { return <div className="dashboard-title"><div>{eyebrow&&<span>{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>; }

function Overview({ user, owned, requests, recommended, setActive }:{user:DashboardUser;owned:DashboardCourse[];requests:DashboardRequest[];recommended:DashboardRecommendation[];setActive:(id:StudentView)=>void}) {
  const average = owned.length ? Math.round(owned.reduce((sum,item)=>sum+item.progress,0)/owned.length) : 0;
  const first = owned[0];
  return <><DashboardTitle eyebrow={`مرحبًا، ${user.fullName.split(" ")[0]} 👋`} title={first ? "كمّل من حيث توقفت" : "ملفك الدراسي جاهز"} description={first ? `لديك ${owned.length} مواد نشطة، وتقدمك محفوظ على جميع أجهزتك.` : "ابدأ باستكشاف المواد، أو اطلب مادتك إذا لم تجدها."} action={<Link href="/courses" className="button button-primary">استكشف المواد <Sparkles size={16}/></Link>} />
    <div className="dashboard-stat-grid"><article><i><BookOpen size={20}/></i><span><small>المواد النشطة</small><strong>{owned.length}</strong><em>مرتبطة بمشترياتك</em></span></article><article><i><FileUp size={20}/></i><span><small>طلبات المواد</small><strong>{requests.length}</strong><em>يمكن متابعتها هنا</em></span></article><article><i><CheckCircle2 size={20}/></i><span><small>متوسط التقدم</small><strong>{average}%</strong><em>محفوظ تلقائيًا</em></span></article><article><i><TrendingUp size={20}/></i><span><small>حالة الحساب</small><strong>مكتمل</strong><em>جاهز للشراء</em></span></article></div>
    {first ? <div className="continue-card"><div className={`continue-art bg-gradient-to-br ${first.color}`}><span className="course-cover-grid"/><strong>{first.icon}</strong><i><Play size={22} fill="currentColor"/></i></div><div className="continue-info"><span>تابع الآن</span><h2>{first.title}</h2><p>{first.current}</p><div className="continue-progress"><i style={{width:`${first.progress}%`}}/></div><small><b>{first.progress}% مكتمل</b><em>{first.remaining}</em></small></div><Link href={`/learn/${first.slug}`} className="button button-primary">متابعة الدرس <ArrowLeft size={16}/></Link></div> : <section className="dashboard-panel dashboard-empty-state"><i><BookOpen size={31}/></i><h2>لا توجد مواد مفعّلة بعد</h2><p>جرّب الدرس المجاني قبل الشراء، أو أرسل طلب مادة مع السلايدات ليصل مباشرة إلى فريق المحتوى.</p><div><Link href="/courses" className="button button-primary">تصفح المواد</Link><Link href="/request-course" className="button button-soft">طلب مادة ورفع الملفات</Link></div></section>}
    <div className="dashboard-two-columns"><section className="dashboard-panel"><div className="panel-head"><div><h2>موادك</h2><p>صلاحيات الوصول الفعلية</p></div><button onClick={()=>setActive("learning")}>عرض الكل <ArrowLeft size={14}/></button></div><div className="mini-course-list">{owned.slice(0,3).map((course)=><Link key={course.slug} href={`/learn/${course.slug}`}><div className={`bg-gradient-to-br ${course.color}`}>{course.icon}</div><span><strong>{course.title}</strong><small>{course.current}</small><i><b style={{width:`${course.progress}%`}}/></i></span><em>{course.progress}%</em></Link>)}{owned.length===0&&<p className="panel-empty-copy">ستظهر المواد هنا فور تأكيد الدفع من الخادم.</p>}</div></section><section className="dashboard-panel request-shortcut"><FileUp size={30}/><h2>مادتك غير موجودة؟</h2><p>ارفع اسم المادة والسلايدات أو توصيف المقرر، وسيتابع المشرف حالة الطلب معك.</p><Link href="/request-course" className="button button-soft">إنشاء طلب جديد</Link></section></div>
    <section className="dashboard-panel dashboard-recommendations"><div className="panel-head"><div><h2>مقترحة لجامعتك وتخصصك</h2><p>نرتب المطابق أولًا، ويمكنك استكشاف بقية الجامعات والتخصصات وشراء موادها أيضًا.</p></div><Link href="/courses">كل الجامعات <ArrowLeft size={14}/></Link></div>{recommended.length?<div>{recommended.map((course)=><Link href={`/courses/${course.slug}`} key={course.slug}><i className={`bg-gradient-to-br ${course.color}`}>{course.icon}</i><span><em>{course.match}</em><strong>{course.title}</strong><small>{course.university} · {course.specialty}</small></span><b>{course.price} ر.س <ArrowLeft size={14}/></b></Link>)}</div>:<p className="panel-empty-copy">لا توجد مادة منشورة مطابقة بعد. استخدم طلب مادة وارفع التوصيف ليصل إلى المشرف.</p>}</section>
  </>;
}

function MyCourses({owned}:{owned:DashboardCourse[]}) { const [filter,setFilter]=useState("all");const[query,setQuery]=useState("");const filtered=filter==="completed"?owned.filter((course)=>course.progress>=100):filter==="learning"?owned.filter((course)=>course.progress<100):owned;const rows=filtered.filter((course)=>matchesText(query,course.title,course.university,course.current));return <><DashboardTitle title="موادي" description="لا تظهر هنا إلا المواد ذات الصلاحية النشطة." action={<Link href="/courses" className="button button-primary">استكشف مواد جديدة</Link>}/><div className="filter-bar"><label className="filter-search"><Search size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="ابحث باسم المادة أو الجامعة..." aria-label="بحث في موادي"/></label><select value={filter} onChange={(event)=>setFilter(event.target.value)} aria-label="حالة التقدم"><option value="all">كل المواد</option><option value="learning">قيد التعلم</option><option value="completed">مكتملة 100%</option></select>{(query||filter!=="all")&&<button type="button" className="button button-ghost filter-reset" onClick={()=>{setQuery("");setFilter("all");}}><X size={15}/> مسح</button>}</div><p className="results-count">{rows.length.toLocaleString("ar-SA")} مادة</p>{rows.length?<div className="owned-courses-grid">{rows.map(course=><article key={course.slug}><div className={`owned-course-art bg-gradient-to-br ${course.color}`}><span className="course-cover-grid"/><strong>{course.icon}</strong><em>{course.progress}%</em></div><div><small>{course.university}</small><h3>{course.title}</h3><p>آخر درس: {course.current}</p><div className="owned-progress"><i style={{width:`${course.progress}%`}}/></div><span><b>{course.progress}% مكتمل</b><em>{course.remaining}</em></span><Link href={`/learn/${course.slug}`} className="button button-soft">متابعة التعلم <ArrowLeft size={15}/></Link></div></article>)}</div>:<EmptyPanel title="لا توجد مواد مطابقة" text={owned.length?"غيّر البحث أو حالة التقدم لعرض مواد أخرى.":"استكشف الفهرس أو اطلب مادة غير متوفرة."} actions={<><Link href="/courses" className="button button-soft">تصفح المواد</Link><Link href="/request-course" className="button button-ghost">طلب مادة</Link></>}/>}</>; }

function Requests({rows}:{rows:DashboardRequest[]}) {const[filter,setFilter]=useState("all");const[query,setQuery]=useState("");const visible=rows.filter((row)=>(filter==="all"||row.status===filter)&&matchesText(query,row.courseName,row.id,row.status));const statuses=[...new Set(rows.map((row)=>row.status))];return <><DashboardTitle title="طلبات المواد" description="طلباتك مرتبطة بملفك وتصل إلى المشرف مع المرفقات." action={<Link href="/request-course" className="button button-primary"><FileUp size={16}/> طلب مادة</Link>}/>{rows.length>0&&<><div className="filter-bar"><label className="filter-search"><Search size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="ابحث باسم المادة أو رقم الطلب..." aria-label="بحث في طلبات المواد"/></label><select value={filter} onChange={(event)=>setFilter(event.target.value)} aria-label="حالة الطلب"><option value="all">كل الحالات</option>{statuses.map((item)=><option value={item} key={item}>{statusLabel(item)}</option>)}</select>{(query||filter!=="all")&&<button type="button" className="button button-ghost filter-reset" onClick={()=>{setQuery("");setFilter("all");}}><X size={15}/> مسح</button>}</div><p className="results-count">{visible.length.toLocaleString("ar-SA")} طلب</p></>}{visible.length?<section className="dashboard-panel request-history">{visible.map((row)=><article key={row.id}><i><FileUp size={18}/></i><span><strong>{row.courseName}</strong><small>#{row.id} · {new Date(row.createdAt).toLocaleDateString("ar-SA")} · {row.attachmentsCount} مرفقات</small></span><em className={`request-status status-${row.status}`}>{statusLabel(row.status)}</em></article>)}</section>:<EmptyPanel title={rows.length?"لا توجد طلبات مطابقة":"لم ترسل طلبات بعد"} text={rows.length?"غيّر البحث أو الحالة لعرض طلبات أخرى.":"إذا لم تجد المادة، ارفع السلايدات أو التوصيف وسنبدأ تتبعها."} actions={<Link href="/request-course" className="button button-primary">إنشاء طلب مادة</Link>}/>}</>; }

function Orders({rows}:{rows:DashboardOrder[]}) {const[filter,setFilter]=useState("all");const[query,setQuery]=useState("");const statuses=[...new Set(rows.map((row)=>row.status))];const visible=rows.filter((row)=>(filter==="all"||row.status===filter)&&matchesText(query,row.orderNumber,row.courseTitle,row.status));return <><DashboardTitle title="الطلبات والفواتير" description="سجل عمليات الدفع الفعلية المرتبطة بحسابك."/>{rows.length>0&&<div className="filter-bar"><label className="filter-search"><Search size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="رقم الطلب أو اسم المادة..." aria-label="بحث في الطلبات والفواتير"/></label><select value={filter} onChange={(event)=>setFilter(event.target.value)} aria-label="حالة الدفع"><option value="all">كل الحالات</option>{statuses.map((item)=><option value={item} key={item}>{statusLabel(item)}</option>)}</select>{(query||filter!=="all")&&<button type="button" className="button button-ghost filter-reset" onClick={()=>{setQuery("");setFilter("all");}}><X size={15}/> مسح</button>}</div>}{visible.length?<><p className="results-count">{visible.length.toLocaleString("ar-SA")} عملية</p><div className="dashboard-panel table-panel"><div className="orders-table"><div className="table-row table-head"><span>رقم الطلب</span><span>المادة</span><span>التاريخ</span><span>المبلغ</span><span>الحالة</span><span></span></div>{visible.map(row=><div className="table-row" key={row.orderNumber}><span dir="ltr">#{row.orderNumber}</span><strong>{row.courseTitle}</strong><span>{new Date(row.createdAt).toLocaleDateString("ar-SA")}</span><span>{row.total.toLocaleString("ar-SA")} {currencyLabel(row.currency)}</span><em>{statusLabel(row.status)}</em><span /></div>)}</div></div></>:<EmptyPanel title={rows.length?"لا توجد عمليات مطابقة":"لا توجد عمليات شراء"} text={rows.length?"غيّر البحث أو حالة الدفع لعرض عمليات أخرى.":"لن تُفعّل أي مادة إلا بعد تأكيد الدفع من Tap على الخادم."} actions={<Link href="/courses" className="button button-primary">استكشف المواد</Link>}/>}</>; }

function Notifications({rows,onRead}:{rows:DashboardNotice[];onRead:(id:number)=>void}) {const[filter,setFilter]=useState("all");const[query,setQuery]=useState("");const visible=rows.filter((item)=>(filter==="all"||(filter==="unread"?!item.read:item.read))&&matchesText(query,item.title,item.body));return <><DashboardTitle title="الإشعارات" description="تحديثات المواد والطلبات والحساب. عند فتح هذا القسم تُعلّم الرسائل كمقروءة." action={rows.some((item)=>!item.read)?<span className="notifications-unread-badge">{rows.filter((item)=>!item.read).length} غير مقروءة</span>:undefined}/>{rows.length>0&&<div className="filter-bar"><label className="filter-search"><Search size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="ابحث في الإشعارات..." aria-label="بحث في الإشعارات"/></label><select value={filter} onChange={(event)=>setFilter(event.target.value)} aria-label="حالة القراءة"><option value="all">كل الإشعارات</option><option value="unread">غير المقروءة</option><option value="read">المقروءة</option></select>{(query||filter!=="all")&&<button type="button" className="button button-ghost filter-reset" onClick={()=>{setQuery("");setFilter("all");}}><X size={15}/> مسح</button>}</div>}{visible.length?<section className="dashboard-panel notifications-panel">{visible.map((item)=>{const href=item.actionUrl&&item.actionUrl.startsWith("/")?item.actionUrl:null;const content=<><i><Bell size={18}/></i><div><strong>{item.title}</strong><p>{item.body}</p>{href&&<small>فتح التفاصيل <ArrowLeft size={12}/></small>}</div><span>{new Date(item.createdAt).toLocaleDateString("ar-SA")}</span></>;return <article key={item.id} onClick={()=>onRead(item.id)} className={!item.read?"new":""}>{href?<Link href={href} onClick={()=>onRead(item.id)} style={{display:"contents"}}>{content}</Link>:content}</article>;})}</section>:<EmptyPanel title={rows.length?"لا توجد إشعارات مطابقة":"لا توجد إشعارات"} text={rows.length?"غيّر البحث أو حالة القراءة لعرض رسائل أخرى.":"ستصلك هنا حالة طلبات المواد وتأكيدات الشراء."}/>}</>; }

function Support({rows}:{rows:DashboardTicket[]}) {const[filter,setFilter]=useState("all");const[query,setQuery]=useState("");const statuses=[...new Set(rows.map((row)=>row.status))];const visible=rows.filter((ticket)=>(filter==="all"||ticket.status===filter)&&matchesText(query,ticket.ticketNumber,ticket.title,ticket.category));return <><DashboardTitle title="الدعم الفني" description="التذاكر والردود مرتبطة بحسابك ولا يراها غيرك وفريق الدعم." action={<Link href="/support" className="button button-primary">فتح تذكرة جديدة</Link>}/>{rows.length>0&&<div className="filter-bar"><label className="filter-search"><Search size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="رقم التذكرة أو العنوان..." aria-label="بحث في تذاكر الدعم"/></label><select value={filter} onChange={(event)=>setFilter(event.target.value)} aria-label="حالة التذكرة"><option value="all">كل الحالات</option>{statuses.map((item)=><option value={item} key={item}>{statusLabel(item)}</option>)}</select>{(query||filter!=="all")&&<button type="button" className="button button-ghost filter-reset" onClick={()=>{setQuery("");setFilter("all");}}><X size={15}/> مسح</button>}</div>}{visible.length?<section className="dashboard-panel support-ticket-history">{visible.map((ticket)=><Link className="support-ticket-card" href={`/support?ticket=${ticket.id}`} key={ticket.id}><header><span><strong>{ticket.title}</strong><small dir="ltr">#{ticket.ticketNumber}</small></span><em>{statusLabel(ticket.status)}</em></header><p>{categoryLabel(ticket.category)} · آخر تحديث {new Date(ticket.createdAt).toLocaleDateString("ar-SA")}</p><div className="support-ticket-card-footer"><span>{ticket.replies.length ? `${ticket.replies.length} ردود في المحادثة` : "بانتظار رد فريق الدعم"}</span><b>فتح المحادثة <ArrowLeft size={14}/></b></div></Link>)}</section>:<section className="dashboard-panel support-contact"><LifeBuoy size={33}/><h2>{rows.length?"لا توجد تذاكر مطابقة":"لا توجد تذاكر بعد"}</h2><p>{rows.length?"غيّر البحث أو الحالة لعرض تذاكر أخرى.":"اذكر رقم الطلب أو اسم المادة لتسريع المعالجة."}</p><Link href="/support" className="button button-soft">تواصل مع الدعم</Link></section>}</>; }

function Account({user,institutions}:{user:DashboardUser;institutions:Institution[]}) {
  const [form,setForm]=useState(user); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  const institution = useMemo(()=>institutions.find((item)=>item.slug===form.universitySlug),[form.universitySlug,institutions]);
  const catalog = useAcademicPrograms(form.universitySlug);
  const save = async (event:React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setMessage(""); try { const response=await fetch("/api/profile",{method:"PATCH",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(form)}); const result=await response.json() as {error?:string}; setMessage(response.ok?"تم حفظ بياناتك بنجاح":result.error||"تعذر الحفظ"); } catch { setMessage("تعذر الاتصال بالخادم. تحقق من الشبكة ثم حاول مرة أخرى."); } finally { setSaving(false); } };
  return <><DashboardTitle title="إعدادات الحساب" description="يجب أن تبقى بياناتك مكتملة لتتمكن من الشراء وطلب المواد."/><div className="dashboard-two-columns account-grid"><form className="dashboard-panel account-form" onSubmit={save}><div className="account-avatar"><span>{form.fullName[0]}</span><b>{institution?.name}</b></div><label>الاسم الكامل<input required minLength={5} value={form.fullName} onChange={(event)=>setForm({...form,fullName:event.target.value})}/></label><div className="two-fields"><label>رقم الجوال<input required value={form.phone} onChange={(event)=>setForm({...form,phone:event.target.value})} dir="ltr"/></label><label>البريد الإلكتروني<input value={form.email} disabled dir="ltr"/></label></div><div className="two-fields"><label>الجامعة<select required value={form.universitySlug} onChange={(event)=>setForm({...form,universitySlug:event.target.value,specialty:""})}>{institutions.map((item)=><option key={item.slug} value={item.slug}>{item.name}</option>)}</select></label><label>التخصص<select required disabled={catalog.loading} value={form.specialty} onChange={(event)=>setForm({...form,specialty:event.target.value})}><option value="">{catalog.loading?"جارٍ التحميل...":"اختر تخصصك"}</option>{form.specialty&&!catalog.programs.some((item)=>item.name===form.specialty)&&<option value={form.specialty}>{form.specialty}</option>}{catalog.programs.map((item)=><option key={`${item.name}-${item.degree}`} value={item.name}>{item.name} — {item.degree}</option>)}</select></label></div>{(message||catalog.error)&&<p className={message.startsWith("تم")?"auth-success":"form-error"}>{message||catalog.error}</p>}<button className="button button-primary" disabled={saving||catalog.loading}>{saving?"جارٍ الحفظ...":"حفظ التغييرات"}</button></form><section className="dashboard-panel security-card"><UserRound size={27}/><h2>الأمان والجلسات</h2><p>الجلسة الحالية محمية بملف تعريف HttpOnly ولا يمكن لجافاسكربت قراءة رمزها.</p><Link href="/forgot-password">تغيير كلمة المرور <ArrowLeft size={14}/></Link><button className="danger" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST",credentials:"same-origin"});window.location.assign("/");}}>تسجيل الخروج</button></section></div><AppearanceSettings /></>;
}

function EmptyPanel({title,text,actions}:{title:string;text:string;actions?:React.ReactNode}) { return <section className="dashboard-panel dashboard-empty-state"><i><BookOpen size={28}/></i><h2>{title}</h2><p>{text}</p>{actions&&<div>{actions}</div>}</section>; }
function matchesText(query:string,...values:Array<string|number|null|undefined>){const terms=query.trim().toLocaleLowerCase("ar").split(/\s+/).filter(Boolean);if(!terms.length)return true;const text=values.join(" ").toLocaleLowerCase("ar");return terms.every((term)=>text.includes(term));}
function statusLabel(status:string) { return ({ new:"جديد",open:"مفتوح",in_progress:"قيد المعالجة",resolved:"تم الحل",closed:"مغلق",assigned:"مسند لمشرف",reviewing:"قيد المراجعة",planned:"مخطط له",producing:"قيد الإنتاج",available:"متاح",pending:"قيد الانتظار",initiated:"بانتظار الدفع",paid:"مدفوع",failed:"غير مكتمل",refunded:"مسترد بالكامل",partially_refunded:"مسترد جزئيًا",reversed:"معكوس",chargeback:"اعتراض مالي",expired:"منتهي",cancelled:"ملغي",voided:"مُبطل" } as Record<string,string>)[status] || "حالة غير معروفة"; }
function currencyLabel(currency:string) { return ({ SAR:"ر.س",USD:"دولار" } as Record<string,string>)[currency] || "عملة غير معروفة"; }
function categoryLabel(category:string) { return ({ technical:"تقنية",payment:"الدفع",course:"المواد",account:"الحساب",other:"أخرى" } as Record<string,string>)[category] || "تصنيف غير معروف"; }
