export const ADMIN_ACTION_ROUTE_OPTIONS = [
  { key: "/courses", label: "استكشاف المواد" },
  { key: "/universities", label: "الجامعات والكليات" },
  { key: "/request-course", label: "طلب مادة" },
  { key: "/support", label: "الدعم" },
  { key: "/contact", label: "التواصل" },
  { key: "/cart", label: "السلة" },
  { key: "/favorites", label: "المفضلة" },
  { key: "/notifications", label: "الإشعارات" },
  { key: "/dashboard", label: "لوحة الطالب" },
  { key: "/dashboard?view=learning", label: "موادي" },
  { key: "/dashboard?view=requests", label: "طلبات المواد" },
  { key: "/dashboard?view=orders", label: "الطلبات والفواتير" },
  { key: "/dashboard?view=notifications", label: "إشعارات الحساب" },
  { key: "/dashboard?view=support", label: "محادثات الدعم" },
  { key: "/dashboard?view=account", label: "إعدادات الحساب" },
  { key: "/supervisor", label: "مساحة المشرف" },
  { key: "/supervisor?view=requests", label: "طلبات المشرف" },
  { key: "/admin", label: "لوحة الإدارة" },
  { key: "/login", label: "تسجيل الدخول" },
  { key: "/register", label: "إنشاء حساب" },
] as const;

